chipsalliance/verible

AUTHORS.md
Fixed the formatting of the Authors page so it renders correctly on GitHub pages.
=> Fixed formatting of Authors page

verilog/analysis/checkers/BUILD, verilog/analysis/checkers/legacy_generate_region_rule.cc, verilog/analysis/checkers/legacy_generate_region_rule.h, verilog/analysis/checkers/legacy_generate_region_rule_test.cc, verilog/analysis/checkers/legacy_genvar_declaration_rule.cc, verilog/analysis/checkers/legacy_genvar_declaration_rule.h, verilog/analysis/checkers/legacy_genvar_declaration_rule_test.cc, verilog/tools/lint/BUILD, verilog/tools/lint/testdata/generate-label-module-body.sv, verilog/tools/lint/testdata/generate_begin_module.sv, verilog/tools/lint/testdata/generate_label_module.sv, verilog/tools/lint/testdata/generate_label_prefix.sv, verilog/tools/lint/testdata/legacy_generate_region.sv, verilog/tools/lint/testdata/legacy_genvar_declaration.sv
Closes #525
Note that this does not remove `v2001-generate-begin` rule mentioned in the issue.
=> Check for genvar and generate region

.editorconfig
This file is supported by most editors/IDEs (https://editorconfig.org/)
=> Add .editorconfig to provide basic code indentation rules.

.clang-format, CONTRIBUTING.md
Putting the requested style in the clang config file makes
it easiest to refer to and possibly can be automatically
be picked up by the contributors' IDE.
Update CONTRIBUTING file to now include that this is not
done automatically anymore on import but needs to be prepared
by the contributor.
=> Add a .clang-format file and update CONTRIBUTING.md

releasing/centos.dockerfile, releasing/docker-generate.sh, releasing/ubuntu.dockerfile
Close #666.
This PR is a subset of #622 and it's based on #666. The main modification here is using template dockerfiles, for reducing the complexity of `docker-generate.sh`.
=> ci: use template dockerfiles

.github/workflows/run-clang-format.sh
Previously, we choose a particular clang-format built-in style
('Google'), but since we now have a .clang-format configuration file
use that instead to make sure we always apply the same rules.
Issues #653
=> Now that we have a .clang-format, use that file as reference.

verilog/analysis/checkers/token_stream_lint_rule.cc
=> Add a missing space in documentation generation.

.github/workflows/verible-ci.yml
👋 hello there! I'm a fellow Googler who works on projects that leverage GitHub Actions for CI/CD. Recently I noticed a large increase in our queue time, and I've tracked it down to the [limit of 180 concurrent jobs](https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration) for an organization. To help be better citizens, I'm proposing changes across a few repositories that will reduce GitHub Actions hours and consumption. I hope these changes are reasonable and I'm happy to talk through them in more detail.
- Only run GitHub Actions for pushes and PRs against the main branch of the repository. If your team uses a forking model, this change will not affect you. If your team pushes branches to the repository directly, this changes actions to only run against the …
=> Improve Actions hygiene

.github/workflows/verible-ci.yml
Github actions resource allowance is limited, so skip building all
artifacts in pull reqeuests. The checks and tests shall be sufficient
for now.
=> Don't build all release artifacts on every pull request commit.

verilog/tools/formatter/verilog_format.cc
The formatter was quite noisy when it didn't have to change
anything. Make that only happen when --verbose is chosen.
=> Don't violate the 'no news are good news' principle.

verilog/formatting/formatter_test.cc, verilog/formatting/token_annotator.cc
Fix missing space before hashtag in class declarations extending parameterized class:
```
class aes_env_cfg extends cip_base_env_cfg #(
.RAL_T(aes_reg_block)
);
```
Fixes #444
=> formatter: Fix missing space before hashtag

verilog/analysis/verilog_linter.h
There might be old code that expects a certain amount of parameters.
Add a default parameter for now to make these compatible.
=> Make functions in header source-compatible with old code.

verilog/formatting/formatter_test.cc, verilog/formatting/tree_unwrapper.cc
Expands constraints blocks with more than one partition, e.g. if-statements
```
constraint xx {
if (a) b;
}
```
But keeps constraints blocks with simple statements unexpanded, e.g.
```
constraint only_vec_instr_c {soft only_vec_instr == 0;}
```
Fixes #445
=> formatter: Fix constraints blocks formatting

verilog/parser/BUILD
=> Compiling bison output creates a warning. Exempt.

.github/workflows/run-clang-format.sh
* -style=file does not seem to work in CI; more investigation
needed. For now: use Google style explicitly.
* Always format all files in repo to avoid corner-cases
with git branches.
=> clang-format: use style Google; always format all files.

.github/settings.sh, .github/workflows/script.sh, common/util/BUILD
* Enable all warnings .. and disable the subset that are
already in the code-base.
* Disable one specific warning that popped up directly
in the BUILD file.
=> Run CI with -Werror

common/analysis/command_file.lex, verilog/parser/verilog.lex
Working towards a more platform-independent build.
Issues #260 #307 #726
=> Flex: Switch off dependencies on <unistd.h> header and isatty()

verilog/analysis/symbol_table.cc, verilog/analysis/verilog_project.cc, verilog/analysis/verilog_project.h, verilog/analysis/verilog_project_test.cc, verilog/tools/kythe/BUILD, verilog/tools/kythe/kythe_facts_extractor.cc, verilog/tools/kythe/kythe_facts_extractor.h, verilog/tools/kythe/verilog_kythe_extractor.cc
Virtual file: file for which we have the path & content, but not the physical file. This is required for running the indexing server
=> [kythe] Extend VerilogProject to support adding virtual files

verilog/analysis/checkers/BUILD, verilog/analysis/checkers/struct_union_name_style_rule.cc, verilog/analysis/checkers/struct_union_name_style_rule.h, verilog/analysis/checkers/struct_union_name_style_rule_test.cc
=> Grant exceptions for custom struct-union-name-style

WORKSPACE, verilog/CST/numbers.cc
And use absl::StrContains() with a char, that wasn't available
before.
=> Upgrade to latest absl.

WORKSPACE, bazel/python_anytree.BUILD, bazel/python_six.BUILD
`six` is already installed as a system package on popular GNU/Linux distributions. This is not a case on e.g. macOS.
Tested on Ubuntu with manually removed system `six` package.
Fixes #739
=> Add `six` Python package as `anytree` dependency

common/util/file_util.cc, common/util/file_util.h, common/util/file_util_test.cc
Files that are directories are now reported in a readable
way.
Issues #743
=> Improve error message when reading files.

verilog/analysis/verilog_project.cc, verilog/analysis/verilog_project.h, verilog/analysis/verilog_project_test.cc
This class is an extended version of InMemoryVerilogSourceFile.
It wraps a TextStructureView object and allows to skip loading and
parsing phase.
=> verilog/analysis: Add ParsedVerilogSourceFile class

verilog/analysis/symbol_table.cc, verilog/analysis/symbol_table.h, verilog/analysis/symbol_table_test.cc
Fixes segfault caused by missing support of enumeration types:
```
F0211 18:06:09.305649 13750 symbol_table.cc:1522] Check failed: node.Parent() == nullptr
```
Test case:
```
enum { x1, x2, x3 } xx;
```
=> [SymbolTable] Add support of enumeration types

.github/workflows/macos-compile.yml, WORKSPACE, verilog/CST/numbers.cc
=> Add MacOS platform compatibility check CI

.github/bin/verify-kythe-extraction.sh, .github/workflows/verible-ci.yml, WORKSPACE, verilog/tools/kythe/BUILD, verilog/tools/kythe/verification_test.sh
io_bazel.
Instead of linking the Kythe verification binary, use precompiled one
from Github Workflow.
Remove Kythe verification test from the general list of tests and
introduce it as an explicit Github workflow step.
Replace bash unit test library from io_bazel with poor man's simple test
suite (remove large dependency -- if we need bash xUnit test framework,
there are smaller ones available).
Related to #760
=> [kythe] Remove the dependency on linked Kythe verification binary and

verilog/analysis/verilog_analyzer.h, verilog/analysis/verilog_excerpt_parse.cc, verilog/parser/verilog_lexical_context_test.cc
It was set and never used. Remove for now to reduce clutter; if
the need ever arises to have something like that, we should
implement it then.
=> Remove unused use_parser_directive_comments VerilogAnalyzer option.

verilog/CST/identifier_test.cc, verilog/CST/tasks_test.cc
=> Avoid unnecessary copy in range loop.

.github/bin/build-and-test.sh, .github/workflows/verible-ci.yml
script.sh was from a very early stage of our github actions
when this was all we did. These days, the name does not make
sense anymore.
=> Rename 'script.sh' to 'build-and-test.sh'

.github/workflows/windows-compile.yml, WORKSPACE, bazel/bison.bzl, bazel/flex.bzl, bazel/win_flex_bison.BUILD, bazel/win_flex_bison.bzl
As a first step towards compiling on Windows (#307), use [WinFlexBison](https://github.com/lexxmark/winflexbison) on Windows instead of compiling m4/flex/bison (which doesn't work)
=> Added support for win_flex_bison on Windows

.github/workflows/macos-compile.yml, .github/workflows/windows-compile.yml
After #772, we don't need to build Kythe in its entirety
anymore. It required a system installed flex/bison, don't
need that anymore now.
=> CI: don't use system installed flex/bison anymore.

.github/workflows/verible-ci.yml, releasing/centos/8/compiler.dockerstage, releasing/centos/common/compiler.dockerstage, releasing/ubuntu/common/compiler.dockerstage, releasing/ubuntu/xenial/compiler.dockerstage
These are not needed anymore.
WIP: In this first change in the pull request, the
building of the release artefacts is enabled to
see if they run through. Next step: put verible-ci.yml
back into original state.
=> Remove flex/bison requirements while building releases.

WORKSPACE
The last released version does not use TEST_TMPDIR set by
bazel and always falls back to /tmp for running tests. That
makes them less hermetic.
(Unfortunately, that only fixes it on Linux, for MacOS I
have an upstream patch open).
The last release was in Oct 2019, so taking github HEAD.
=> Upgrade googletest to github HEAD.

WORKSPACE
Split commit from #781. Current glog version does not compile on Windows, the new one does.
=> Updated glog to latest glog library

.github/workflows/windows-compile.yml, verilog/CST/verilog_treebuilder_utils_test.cc
The `WrongClose` test was failing on Windows with
```
external/com_google_googletest/googletest/src/gtest-port.cc(865): error: Failed
Syntax error at index 0 in simple regular expression "}": '}' is unsupported.
Stack trace:
00007FF780051A8F: testing::internal::RE::Init
00007FF78002BC9F: testing::internal::RE::RE
00007FF78002BAAC: testing::ContainsRegex<const char *>
00007FF78002B72C: testing::internal::MakeDeathTestMatcher
00007FF780023CF7: verilog::`anonymous namespace'::MakeParenGroupTest_WrongClose_Test::TestBody
00007FF78009B000: testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test,void>
00007FF780085E3F: testing::internal::HandleExceptionsInMethodIfSupported<testing::Test,void>
00007FF78006C8B9: testing::Test::Run
00007FF78006D58C: testing::TestInfo::Run …
```
=> Fix verilog_treebuilder_utils_test on Windows

.github/workflows/windows-compile.yml, common/formatting/align.cc
Please verify if the `.base()` has a purpose. On Windows, compilation failed with:
```
common/formatting/align.cc(598,42): error: no member named 'base' in 'std::_Vector_iterator<std::_Vector_val<std::_Simple_types<verible::VectorTree<verible::UnwrappedLine>>>>'
const int indentation = rows.front().base()->Value().IndentationSpaces();
~~~~~~~~~~~~ ^
```
=> Fixed common/formatting/align.cc on Windows

.github/bin/build-and-test.sh
Since we run with -Werror, we want the most warnings enabled
we can.
=> Remove not needed-anymore exemptions of warnings in CI.

verilog/formatting/formatter_test.cc, verilog/formatting/tree_unwrapper.cc, verilog/formatting/tree_unwrapper_test.cc
There is an indentation problem with the current patch, so until
that is found and fixed, skip the code in question.
Reference pull request: #755
Issues #352
=> Comment out initializer list improvement until regression found.

.github/workflows/windows-compile.yml, bazel/BUILD, bazel/sh_test_with_runfiles_lib.bzl, bazel/sh_test_with_runfiles_lib.sh, common/strings/patch.cc, common/tools/BUILD, common/tools/patch_tool.cc, common/tools/patch_tool_test.sh, common/tools/verible-transform-interactive-test.sh, verilog/analysis/symbol_table_test.cc, verilog/tools/diff/BUILD, verilog/tools/diff/diff_format_lex_error_test.sh, verilog/tools/diff/diff_format_match_test.sh, verilog/tools/diff/diff_format_mismatch_test.sh, verilog/tools/diff/diff_obfuscate_match_test.sh, verilog/tools/diff/diff_obfuscate_mismatch_test.sh, verilog/tools/diff/diff_user_errors_test.sh, verilog/tools/formatter/BUILD, verilog/tools/formatter/format_file_badlines_test.sh, verilog/tools/formatter/format_file_lex_error_test.sh, verilog/tools/formatter/format_file_lines_test.sh, verilog/tools/formatter/format_file_syntax_error_test.sh, verilog/tools/formatter/format_file_test.sh, verilog/tools/formatter/format_inplace_test.sh, verilog/tools/formatter/format_stdin_inplace_test.sh, verilog/tools/formatter/format_stdin_test.sh, verilog/tools/kythe/BUILD, verilog/tools/kythe/kythe_proto_output.cc, verilog/tools/kythe/verilog_kythe_extractor_test.sh
Verible now compiles on Windows! Work is not over, as not all test succeeds yet. The changes to make it compile is minimal, only replacing `unistd.h` with the appropriate Windows equivalent.
Making testing works, which is very much a WIP, revolves around 2 cookie-cutter fix that needs review:
1. On Windows, bazel doesn't symlink runfiles by default (you must have a recent Windows and enable developer mode for it) and instead create a `MANIFEST` file with the requested runfiles (refer to this [issue](https://github.com/bazelbuild/bazel/issues/8843)). Using the `--enable_runfiles` flag caused other issues with *very* long path that made some test fail. I couldn't fix that long path issue, it would require renaming some tests that have excessively long names.
Instead, I modified the …
=> Compiling on Windows

common/strings/patch.cc, common/tools/patch_tool.cc, common/util/file_util.cc, common/util/file_util.h
This encapsulates the isatty() call and the different
includes needed on Unix and Windows.
Issues #307
=> Provide IsInteractiveTerminalSession().

common/util/vector_tree.h
We implicitly extract the result in our predicate.
=> Document the fact that we ignore the std::mismatch return value.

.github/workflows/windows-compile.yml, verilog/tools/lint/BUILD, verilog/tools/lint/lint_tool_test.sh, verilog/tools/obfuscator/BUILD, verilog/tools/obfuscator/obfuscate_test.sh, verilog/tools/preprocessor/BUILD, verilog/tools/preprocessor/verilog_preprocessor_test.sh, verilog/tools/project/BUILD, verilog/tools/project/project_tool_test.sh, verilog/tools/syntax/BUILD, verilog/tools/syntax/verilog_syntax_test.sh
First step: run all to see which pass.
=> Expanding Windows tests running in CI 

.bazelrc
- Use `common` options instead of separate `build`, `run`, `test` command options.
- Prevents invalidation of bazel cache due to changed compiler options.
Reduces compile time of consecutive bazel build, test, run commands.
- A single `build` option line per platform works also since `test` and
`run` command options inherit options from `build`, according to
https://docs.bazel.build/versions/master/guide.html#bazelrc-syntax-and-semantics
- Extends abseil compile fix (--features=-supports_dynamic_linker) from macos:test to macos:build and macos:run.
=> Use `common` for platform-specific bazel configs:

.github/bin/build-and-test.sh, WORKSPACE
We still have to keep the fallthrough-warning disabled in our
CI due to another place in our code-base; that will be
addressed separately, then the warning enabled.
=> Use latest gflags, which does not produce a fallthrough-warning.

verilog/formatting/formatter_test.cc, verilog/formatting/tree_unwrapper.cc
=> formatter: Fix crash caused by an alignment of null statement

.bazelrc
Seems like `.py` files are not directly (i.e. in `CreateProcess` system function) executable on Windows.
This change has been tested with https://github.com/google/verible/pull/823 (commit/build status before rebase: https://github.com/google/verible/commit/e74e9ed18966217fb1aaffa032019686cfd30863)
=> Fix `workspace_status_command` on Windows

common/text/token_info_json.cc, common/text/token_info_json.h, common/text/token_info_json_test.cc, verilog/CST/BUILD, verilog/CST/verilog_tree_json.cc, verilog/CST/verilog_tree_json_test.cc, verilog/tools/syntax/BUILD, verilog/tools/syntax/README.md, verilog/tools/syntax/verilog_syntax.cc
Adds `text` field containing token text to all token nodes except those representing operators and keywords.
Closes #743
=> Include tokens text in JSON output

verilog/tools/lint/verilog_lint.cc
=> Don't use 'auto' type if not needed.

.bazelrc, .github/bin/build-and-test.sh, .github/workflows/verible-ci.yml, common/formatting/align.cc
Compiling with address sanitizer options revealed a memory overrun. Fix the problem and also add address sanitizer compilation to CI.
=> Make asan clean

verilog/formatting/format_style.h, verilog/formatting/formatter_test.cc, verilog/formatting/tree_unwrapper.cc, verilog/formatting/tree_unwrapper_test.cc, verilog/tools/formatter/verilog_format.cc
Add a switch to the formatter to always expand coverpoint declarations, even if they would fit on one line.
The option is `--expand_coverpoints` and is disabled by default.
Fixes #813.
=> Optionally expand coverpoints

verilog/CST/numbers.cc
=> Use a new absl::StrContains() functionality to clarify code.

common/formatting/token_partition_tree.cc, common/formatting/token_partition_tree_test.cc, verilog/formatting/formatter_test.cc, verilog/formatting/tree_unwrapper.cc, verilog/parser/verilog.y
Demo:
```systemverilog
string seq_names[] = {"uart_sanity_vseq",
"uart_tx_rx_vseq",
"uart_fifo_full_vseq",
"uart_fifo_overflow_vseq",
"uart_fifo_reset_vseq",
"uart_common_vseq",  // for intr_test
"uart_intr_vseq",
"uart_noise_filter_vseq",
"uart_rx_start_bit_filter_vseq",
"uart_rx_parity_err_vseq",
"uart_tx_ovrd_vseq",
"uart_perf_vseq",
"uart_loopback_vseq"};
```
```systemverilog
string abc[] = {"a",
"b",  //
"c"};
```
```systemverilog
string abc[] = {"a",
"b",  //
"c"  //
};
```
```systemverilog
string abc[] = {  //
"a",
"b",
"c"
};
```
```systemverilog
string seq_names_without_comments[] = {"uart_sanity_vseq",
"uart_tx_rx_vseq",
"uart_fifo_full_vseq",
"uart_fifo_overflow_vseq",
"uart_fifo_reset_vseq",
"uart_common_vseq",
"uart_intr_vseq",
"uart_noise_filter_vseq", …
```
=> Formatter: Align multiline string initializer

README.md, verilog/analysis/checkers/README.md, verilog/tools/lint/README.md
The links still point to the old github organization and render 404.
=> Fix all documentation links

README.md, shell.nix
Make it simple and hermetic to set-up the build environment
on systems with the nix package manager.
Inspired by https://github.com/chipsalliance/Surelog/pull/1606
=> Provide build-environment set-up for nix.

verilog/formatting/formatter_test.cc, verilog/formatting/token_annotator.cc
Fixes #359.
Also fixes #431 - only adds test cases with comments, it seems the indentation issue was resolved some time ago.
=> Keep '?' with condition in ternaries

.github/workflows/verible-ci.yml
E.g. on the toplevel project page, clicking on the check-marker
pops up a smallish window with the results of the various tests.
But since the prefix is so long, they are all abbreviated to
'verible-ci / Che…', which is not very helpful.
=> Make CI names fit into length limited titles.

.github/workflows/verible-ci.yml, verilog/analysis/checkers/BUILD, verilog/analysis/checkers/undersized_binary_literal_rule.cc, verilog/analysis/checkers/undersized_binary_literal_rule.h, verilog/analysis/checkers/undersized_binary_literal_rule_test.cc
The numbers to check are configuration parameters; available are
the boolean parameters 'bin' (default on, pre-existing rule),
'oct' and 'hex' (both default off).
=> Extend the undersized binary literal rule to also check Hex and Oct.

common/analysis/linter_test_utils.h, verilog/analysis/checkers/undersized_binary_literal_rule_test.cc
The test infrastructure that has been implemented in the
test added in #903 is useful for other AutoFix unit-tests.
=> Move initial unittest infrastructure for AutoFix to test-utils.

verilog/analysis/verilog_linter.cc, verilog/analysis/verilog_linter.h, verilog/tools/lint/README.md, verilog/tools/lint/lint_tool_test.sh, verilog/tools/lint/verilog_lint.cc, verilog/tools/lint/verilog_style_lint.bzl
The autofix choices were easy to set in a way that
it would accidentally overwrite the input file (setting
--autofix=yes and forgetting output file). This patch
makes the choice explicit and in particular requires
to choose 'inplace' option to modify output.
* no
* patch-interactive
* patch
* inplace-interactive
* inplace
The `yes` option does not exist anymore, as it is replaced
by the more detailed choices. Hopefully that will not break
too many users at this point. The github action though
is probably affected.
While at it, make the default output stdout for the patch
choices (and move error messages to stderr). That way, the
tool is behaving like other command line tools.
=> Provide more detailed choices for linter autofix.

common/analysis/linter_test_utils.h, verilog/analysis/checkers/endif_comment_rule.cc, verilog/analysis/checkers/endif_comment_rule_test.cc, verilog/analysis/checkers/forbid_consecutive_null_statements_rule_test.cc, verilog/analysis/checkers/no_trailing_spaces_rule_test.cc, verilog/analysis/checkers/posix_eof_rule_test.cc, verilog/analysis/checkers/suggest_parentheses_rule_test.cc, verilog/analysis/checkers/uvm_macro_semicolon_rule_test.cc
Add the boilderplate and test for typical fixes.
=> Augment unit-tests of AutoFix rules to test for fixes.

verilog/analysis/checkers/BUILD, verilog/analysis/checkers/truncated_numeric_literal_rule.cc, verilog/analysis/checkers/truncated_numeric_literal_rule.h, verilog/analysis/checkers/truncated_numeric_literal_rule_test.cc, verilog/analysis/default_rules.h
Detects number literals that have a shorter bit-width than the
digits provided, e.g. 16'h1FFFF.
Decimal numbers are only dealt with correctly up to 128 bits,
beyond that, only some lower-bound estimates are applied so
it might miss complain opportunity there. Given that super-long
constants are very likely not given as decimal, this
tradeoff is accepted.
=> Add a lint rule that detects truncated number literals.

verilog/analysis/symbol_table.cc, verilog/analysis/symbol_table.h, verilog/analysis/symbol_table_test.cc
Support implicit declarations as defined in SystemVerilog LRM `6.10: Implicit declarations`
=> [SymbolTable]: initial support for implicit declarations

verilog/analysis/verilog_linter.cc
.. otherwise markdown doesn't recognize the
new paragraph.
=> Add a newline after the parameters.

.clang-tidy, .github/bin/run-clang-tidy.sh, .github/workflows/verible-ci.yml, .gitignore, BUILD, WORKSPACE
* Use bazel rule to generate compilation database.
* Run clang-tidy with some initial useful warnings enabled.
The output file is currently just displayed in the CI log,
but once that is clean, we can fail-on-warning
Fixes: #653
=> Add clang-tidy script, to be run from the CI.

.github/bin/install-python.sh, .github/workflows/verible-ci.yml, common/analysis/lint_rule_status.h, common/analysis/matcher/matcher_builders.h, common/formatting/align.cc, common/formatting/token_partition_tree.cc, common/parser/parser_param.h, common/strings/split.h, common/text/concrete_syntax_tree.h, common/text/macro_definition.h, common/text/tree_utils.h, verilog/CST/type.cc, verilog/CST/type.h, verilog/analysis/checkers/truncated_numeric_literal_rule.cc, verilog/analysis/symbol_table.cc, verilog/analysis/verilog_linter.h, verilog/formatting/formatter.cc, verilog/formatting/tree_unwrapper.cc, verilog/tools/kythe/indexing_facts_tree.h, verilog/tools/syntax/verilog_syntax.cc
These are outside verilog/tools/kythe, which requires a bit
more work.
=> Fix clang-tidy warnings, resulting in empty clang tidy output.

.github/bin/run-clang-tidy.sh, .github/workflows/verible-ci.yml
=> Fail CI if clang-tidy reports an issue.

.github/bin/smoke-test.sh
Just making sure ingesting the input files doesn't make
them crash.
=> Run smoke tests on all verible binaries.

.github/bin/run-clang-tidy.sh, BUILD, WORKSPACE
With the resolution of
https://github.com/grailbio/bazel-compilation-database/issues/84
... we can now use a fileset, reducing duplication.
=> Use fileset for compilation database target.

common/analysis/lint_rule_status.cc, common/analysis/lint_rule_status.h, verilog/analysis/checkers/undersized_binary_literal_rule.cc, verilog/analysis/checkers/undersized_binary_literal_rule.h, verilog/analysis/checkers/undersized_binary_literal_rule_test.cc
e.g. 32'h1 now provides two suggestions
* 32'd1
* 32'h00000001
=> For undersized literals with value one: also suggest decimal.

.github/bin/run-clang-tidy.sh, BUILD, WORKSPACE
This breaks building on centos 7/8, possibly due
to bazel version incompatibility; needs to be figured
out.
=> Undo compilation database with fileset.

common/formatting/align.cc, common/formatting/align.h, verilog/formatting/align.cc, verilog/formatting/format_style.h, verilog/formatting/formatter_test.cc, verilog/tools/formatter/verilog_format.cc
This PR depends on https://github.com/chipsalliance/verible/pull/865
The PR's unique commits are:
* `9a39375` Pass FormatStyle to Verilog's ColumnsSchemaScanners
* `47fe30a` Cleanup non_tree_column_scanner
* `bef221e` Add left_border_override column property
* `8b6db2c` Add options for right-aligning dimensions in port declarations
* `962c448` Right-aligning dimensions in port declarations: add tests
---
Two new flags are added:
* `--port_declarations_right_align_packed_dimensions`, which aligns packed dimensions in port declarations to the right:
```systemverilog
import "DPI-C" context function void func(
input  bit                      foo,
input  bit              [    2] foobar,
input  bit              [24:16] bar,
input  bit      [   2:0][ 31:0] baz,
input  bit [  4][  24:0][ 16:0] …
```
=> Add options for right-aligning dimensions in port declarations

verilog/analysis/checkers/no_trailing_spaces_rule.cc, verilog/analysis/checkers/no_trailing_spaces_rule_test.cc
`no-trailing-spaces` rule reports issues in every line of files which use `\r\n` line endings.
Example file: https://github.com/chipsalliance/UHDM-integration-tests/blob/master/tests/AssignmentPattern/top.sv
~~The solution uses `std::isblank` which means only spaces and tabs in the end of lines will cause errors.~~
~~A useful comparison of `isblank` and `isspace` can be seen in the table in the bottom of this page:
https://en.cppreference.com/w/cpp/string/byte/isspace~~
EDIT:
The suggested test case has shown that the idea of solving the problem with `isblank` won't work.
Right now the code drops one `\r` character from the end of the line if it exists.
=> Use isblank instead of isspace for trailing spaces detection

shell.nix
This allows building with `nix-shell --pure`.
Without the jdk package builds will fail when using `--pure`:
```text
Error in fail: Auto-Configuration Error: Cannot find Java binary bin/java in /home/alex/.cache/bazel/_bazel_alex/install/a1b2cf98f1aadcf49735c7833d8c2677/embedded_tools/tools/jdk/nosystemjdk; either correct your JAVA_HOME, PATH or specify embedded Java (e.g. --javabase=@bazel_tools//tools/jdk:remote_jdk11)
```
=> Add jdk to nix-shell.

verilog/analysis/checkers/undersized_binary_literal_rule.cc, verilog/analysis/checkers/undersized_binary_literal_rule.h, verilog/analysis/checkers/undersized_binary_literal_rule_test.cc, verilog/tools/lint/README.md
Autofixes for undersized zero literals, e.g. 32'h0 provide
as one alternative to fix it to a simple '0. Thus the alternatives
for a zero constant `32'h0` are now
1. `'0`
2. `32'h00000000`
3. `32'd0`
=> Provide an additional alternative for autofixing zero literals.

verilog/analysis/verilog_linter.cc, verilog/analysis/verilog_linter.h, verilog/analysis/verilog_linter_test.cc, verilog/tools/lint/lint_tool_test.sh, verilog/tools/lint/verilog_lint.cc
Most lint rules with autofix have exactly one choice of fixes,
but there are some that have 2 or even three alternatives.
Provide a way to choose if there are multiple options.
The short choices are then including the digits
'1', '2', etc. The default 'y' is equivalent to choosing
choice 1.
If there are multiple options, print all of these and
mark as "1. alternative", "2. alternative", etc.
Also while at it: improve interactive sessions by always
printing the available patch first (or patches, if there are
alternatives), as the user typically will not
choose blindly, so make the initial 'print' automatic.
=> Provide UI choice if there are multiple autofix alternatives.

verilog/formatting/formatter_test.cc, verilog/formatting/formatter_tuning_test.cc, verilog/formatting/token_annotator.cc, verilog/formatting/tree_unwrapper.cc, verilog/formatting/tree_unwrapper_test.cc
Fixes https://github.com/chipsalliance/verible/issues/887
Formatted test cases from the issue:
```systemverilog
module X ();
assign myvar = check ? {10'b0, foo} : (bar && (baz == '0)) ? hello_longlonglong :
world_longlonglong ? temp1_longlonglong : temp2_longlonglong;
endmodule : X
```
```systemverilog
module X ();
assign {dc_wrap, dc_htbt_d} = !(htbt_ctr_q == blink_param_x_i) ?
{1'b0, dc_htbt_q} : ((dc_htbt_q == duty_cycle_a_i) && pattern_repeat) ?
{1'b0, duty_cycle_a_i} : (htbt_direction) ? {1'b0, dc_htbt_q} - {1'b0, blink_param_y_i} -
1'b1 : {1'b0, dc_htbt_q} + {1'b0, blink_param_y_i} + 1'b1;
endmodule : X
```
```systemverilog
module X ();
assign {phase_wrap, off_phase} = {1'b0, phase_delay_scaled[15:0]} +
{1'b0, duty_cycle_scaled[15:0]};
endmodule : X
```
Todo:
* unit tests
Ideas for …
=> Fix formatting of ternaries

common/util/user_interaction.cc, common/util/user_interaction.h, verilog/analysis/verilog_linter.cc
Use bold and inverse to improve readability of lint autofix
sessions.
=> Interactive lint autofix application: use terminal highlight.

common/analysis/lint_rule_status.cc, common/analysis/lint_rule_status.h, common/analysis/lint_rule_status_test.cc, verilog/analysis/checkers/forbid_consecutive_null_statements_rule.cc, verilog/analysis/checkers/no_trailing_spaces_rule.cc, verilog/analysis/checkers/posix_eof_rule.cc, verilog/analysis/checkers/suggest_parentheses_rule.cc, verilog/analysis/checkers/undersized_binary_literal_rule.cc, verilog/analysis/checkers/uvm_macro_semicolon_rule.cc, verilog/analysis/verilog_linter.cc, verilog/tools/lint/README.md
Since we have a chance to show a description of a lint autofix
in the potential UI or github pull, add descriptions to all of
them.
Remove the AutoFix constructors that allow to skip adding a
description, thus AutoFix implementors are always required
to add a description.
=> Add autofix-hints to all autofixes.

common/formatting/align.cc, common/formatting/basic_format_style.cc, verilog/analysis/symbol_table.cc, verilog/analysis/verilog_equivalence.cc, verilog/analysis/verilog_linter.h, verilog/analysis/verilog_linter_configuration.cc, verilog/formatting/tree_unwrapper.cc, verilog/tools/diff/verilog_diff.cc, verilog/tools/kythe/verilog_kythe_extractor.cc, verilog/tools/lint/verilog_lint.cc, verilog/tools/syntax/verilog_syntax.cc
Objects with non-trivial construction should not be
initialized at global scope.
=> EnumMap: don't construct globally.

.github/bin/run-clang-tidy.sh, .github/workflows/verible-ci.yml
Current version used by default in actions CI is clang-tidy-10; make
sure we're explicit in requesting exactly that as later versions might
have additional warnings which we should enable deliberately.
=> Pin clang-tidy version used to stay consistent.

common/formatting/align.cc
Same thing tested with CHECK_GT() right above. Also, prefer
CHECK() to assert()
=> Remove superfluous assert()

common/formatting/align.cc
For some reason, it can't see through CHECK_GT(), while it
could with assert().
=> Tell clang-tidy that suspected div-by-zero can't happen.

common/util/logging.h
... acutally use the `__FILE__` and `__LINE__` when printing
the crash.
Issues: #917
=> Make ABSL_DIE_IF_NULL() more useful.

WORKSPACE
Absl doesn't build with glibc 2.34, which is now being rolled out by
more and more Linux distributions. Update to the lastest patch version
of the same LTS release to include the relevant build fixes.
https://github.com/abseil/abseil-cpp/commit/278e0a071885a22dcd2fd1b5576cc44757299343
are the only changes over the last version.
=> Update absl dependency to 20210324.2

.clang-tidy, common/analysis/file_analyzer.h, common/util/vector_tree.h, verilog/formatting/tree_unwrapper.h
=> Enable more clang tidy warnings; fix fallout.

verilog/analysis/verilog_linter.cc, verilog/analysis/verilog_linter_configuration.cc, verilog/tools/lint/verilog_lint.cc
LOG(WARNING) does not show up by default unless some magic
environment variables are set, but we want genuine warnings that
should be visible as feedback to the user ... visible.
Issues #959
=> Log messages that are meant to be user-visible to std::cerr

verilog/analysis/BUILD, verilog/analysis/verilog_linter_configuration_test.cc
=> Use better overload for single-character find()

.github/bin/build-and-test.sh, .github/workflows/verible-ci.yml
Do a blaze shutdown so that the cache storage can access files on
Windows.
Possibly due to non-posix filesystem semantics, it seems to be
impossible to package files that are still open on Windows. A blaze
shutdown helped the situation.
While at it, also do a blaze shutdown in the general build matrix,
can't harm.
=> Make windows bazel cache work.

.github/bin/run-clang-tidy.sh, .github/workflows/verible-ci.yml
clang-tidy takes almost 30min in the CI, so let's remember the
content hashes of all files we processed so that we only have to
look at changed files.
=> Only clang-tidy files whose content hash changed

.github/bin/smoke-test.sh
That way, it is not necessary to unfold the part that
might contain interesting fixed issues.
=> Put the smoke-test results in the toplevel output.

.github/workflows/verible-ci.yml
The Windows cache is using the most of all build caches
(over 3GiB), but it is also leas effective as the packaging of
the cache takes about 45 min vs. a 55min fresh build.
These 3GiB will then evict other caches so that
we have to re-build a lot of other parts of the CI: the
total cache size allowance is currently 5GiB [1].
So for now, let's disable it, but keep it prepared for a future
in which there is more space available and possibly the more
efficient zstd compression is used also on Windows.
[1]: https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy
Related: https://github.com/actions/cache/issues/442
https://github.com/actions/cache/issues/301
=> Disable use of cache in Windows for now

common/analysis/file_analyzer.cc, common/strings/line_column_map.h, common/strings/line_column_map_test.cc, common/text/text_structure.cc, common/text/text_structure.h, common/text/text_structure_test.cc, verilog/tools/ls/document-symbol-filler.cc, verilog/tools/ls/verible-lsp-adapter.cc
There are various places in which we need the line column range
for a token. Put that in one place.
=> Add convenience function: TextStructureView::GetRangeForToken().

common/text/text_structure.cc, common/text/text_structure.h, common/text/text_structure_test.cc
This is needed for operations in the language server which
often start with a cursor position.
=> Given a Line/Column, find token at that point.

common/formatting/BUILD, common/formatting/basic_format_style.h, common/formatting/basic_format_style_init.cc, common/formatting/basic_format_style_init.h, verilog/formatting/BUILD, verilog/formatting/format_style.h, verilog/formatting/format_style_init.cc, verilog/formatting/format_style_init.h, verilog/tools/formatter/BUILD, verilog/tools/formatter/README.md, verilog/tools/formatter/verilog_format.cc
Having it a separate library allows to use it also in other
binaries (such as the language server). Also this provides
a context to implement other initialization from a configuration
file.
The first commit does _not_ change or add any flags, but this is in
preparation to provide additional flags for previously not flag-configured fields.
The second commit fixes some typos in flags (by [retiring them](https://abseil.io/docs/cpp/guides/flags#removing--retiring-flags)), simplify the initialization with a macro to avoid typos and add previously missing flags.
Third commit adds flags for the basic formatting configuration, fixing #1046
=> Move FormatStyle flag initialization into separate library.

common/formatting/BUILD, common/formatting/align.cc, common/formatting/format_token.cc, common/formatting/format_token.h, common/formatting/layout_optimizer.cc, common/formatting/layout_optimizer.h, common/formatting/layout_optimizer_internal.h, common/formatting/layout_optimizer_test.cc, common/formatting/unwrapped_line.cc, common/formatting/unwrapped_line.h, common/util/iterator_adaptors.h, common/util/iterator_adaptors_test.cc, verilog/formatting/BUILD, verilog/formatting/formatter.cc, verilog/formatting/formatter_test.cc, verilog/formatting/tree_unwrapper.cc
Depends on: https://github.com/chipsalliance/verible/pull/1044
Fixes #30 
Input:
```systemverilog
`uvm_info(get_full_name(), $sformatf("Detect request with address: %0x", trans_collected.addr), UVM_HIGH)
`uvm_fatal(`gfn, $sformatf("The data 0x%0h written to the signature address is formatted incorrectly.", signature_data))
```
Results:
indent: 0 spaces
```systemverilog
`uvm_info(get_full_name(), $sformatf("Detect request with address: %0x", trans_collected.addr),
UVM_HIGH)
`uvm_fatal(
`gfn, $sformatf(
"The data 0x%0h written to the signature address is formatted incorrectly.", signature_data))
```
indent: 2 spaces
```systemverilog
`uvm_info(get_full_name(), $sformatf("Detect request with address: %0x", trans_collected.addr),
UVM_HIGH)
`uvm_fatal(
`gfn, $sformatf("The data 0x%0h written to …
```
=> Use Layout Optimizer to format nested function calls

common/lsp/lsp-protocol.yaml, verilog/tools/ls/BUILD, verilog/tools/ls/README.md, verilog/tools/ls/verible-lsp-adapter.cc, verilog/tools/ls/verible-lsp-adapter.h, verilog/tools/ls/verible-verilog-ls_test.sh, verilog/tools/ls/verilog_ls.cc
If the cursor is on a symbol, this will highlight all the symbols
in the buffer with the same name (it does _not_ take naming
scopes into account yet).
=> Basic implementation of language server document highlight.

common/tools/BUILD, common/tools/jcxxgen.cc, verilog/tools/kythe/BUILD, verilog/tools/kythe/kythe_facts_extractor.cc
=> Use absl containers, which are more efficient.

common/formatting/token_partition_tree.cc, common/formatting/token_partition_tree.h, common/formatting/token_partition_tree_test.cc, verilog/formatting/align.cc, verilog/formatting/align.h, verilog/formatting/formatter.cc
In https://github.com/chipsalliance/verible/pull/1045#discussion_r741267915 constant `style` argument has been defined as a first argument. The PR applies the same order (i.e. constants/inputs before outputs) to similar functions that are used nearby.
=> Unify argument order in formatting functions

common/formatting/align.cc, common/formatting/align.h, common/formatting/align_test.cc, verilog/formatting/align.cc
The argument order has been changed to match other functions (and Google style guide). See also #1097.
=> Refactoring: Change arguments order in TabularAlignTokens() and remove duplicated code from TabularAlignTokenPartitions()

common/text/tree_utils.h
For instance:
https://chipsalliance.github.io/sv-tests-results/#VeribleExtractor|TNoC|TNoC
https://chipsalliance.github.io/sv-tests-results/#VeribleExtractor|ariane|ariane
https://chipsalliance.github.io/sv-tests-results/#VeribleExtractor|earlgrey|earlgrey
This doesn't change any functionality, just improves logging of the particular case.
=> Add more detail to a check failure seen in some Kythe indexings.

common/formatting/BUILD, common/formatting/align.cc, common/formatting/align.h, common/formatting/align_test.cc, common/formatting/format_token.cc, common/formatting/format_token.h, common/formatting/layout_optimizer.cc, common/formatting/layout_optimizer.h, common/formatting/layout_optimizer_internal.h, common/formatting/layout_optimizer_test.cc, common/formatting/token_partition_tree.cc, common/formatting/token_partition_tree.h, common/formatting/token_partition_tree_test.cc, common/formatting/token_partition_tree_test_utils.cc, common/formatting/token_partition_tree_test_utils.h, common/formatting/unwrapped_line.cc, common/formatting/unwrapped_line.h, common/formatting/unwrapped_line_test.cc, common/formatting/verification.cc, common/formatting/verification_test.cc, common/strings/display_utils.cc, common/strings/display_utils.h, common/strings/display_utils_test.cc, verilog/formatting/BUILD, verilog/formatting/align.cc, verilog/formatting/align.h, verilog/formatting/comment_controls.cc, verilog/formatting/formatter.cc
The partition with `kInline` policy replaces spacing before its first token (i.e. token's '.before.spaces_required' value) with number of spaces equal to IndentationSpaces().
When the first token is at the beginning of a line, the spacing is added to line's indentation.
`kInline` complements `kAlreadyFormatted` partition policy, and can exist only inside partitions with such policy.
The tokens (their spacing) themselves are modified near the end of formatting pipeline, just before final partition tree is converted into a list of UnwrappedLines.
The policy is intended to add non-permanent spacing between tokens in situations where multiple token partition trees with different token spacings can coexist (e.g. in multiple layouts passed to Layout Optimizer).
Currently partitions with this …
=> Add new partition policy: kInline

common/formatting/BUILD
That way, it is not accidentally used in final binaries.
=> Make sure a library used for testing is tagged as such.

verilog/tools/kythe/kythe_facts_extractor.cc
This is a stop-gap as these null scopes were encountered in the
field, further analysis is needed.
Issues #1128
=> Handle null scopes gracefully in ReferenceExtendsInheritance().

.github/bin/smoke-test.sh, verilog/CST/verilog_nonterminals.h, verilog/parser/verilog.y, verilog/parser/verilog_parser_unittest.cc
A naive attempt to fix  #717.
I have introduced a new node `kAssignmentPatternExpression` to handle the struct literals (inspired by the parser from [tree-sitter-verilog](https://github.com/tree-sitter/tree-sitter-verilog)).
I have zero experience with yacc so I've probably overlooked things. 
Any comments or feedback would be welcome.
=> Add explicit typed structure literals

verilog/tools/ls/README.md
Add documentation on how to enable the verible language server with neovim using the built-in client.
=> Add nvim-lspconfig to language server documentation

.github/workflows/verible-ci.yml, README.md, bazel/bison.bzl, bazel/flex.bzl, verilog/parser/BUILD
This should allow us to skip the problematic update of the m4 dependency. Other operating systems can keep using the outdated version, Linux should be allowed to use host tools.
Closes #1122 
Closes #957
=> Use host m4/flex/bison on linux

.github/workflows/verible-ci.yml, README.md, bazel/bison.bzl, bazel/flex.bzl, verilog/parser/BUILD
Reverts chipsalliance/verible#1132
This needs more work as releases stop working with it as the releases need a local bison/flex installed ; a first attempt to do this in #1135 showed that this then creates issues with older versions of bison/flex.
So we probably need an approach in which we _optionally_ can choose to use to use the local m4; something along the lines of [this comment](https://github.com/chipsalliance/verible/pull/1132#issuecomment-1006614936)
But for now, revert this to unbreak.
=> Revert "Use host m4/flex/bison on linux"

releasing/supported_bases.txt
The Release file in the repository is gone for the security updates, so the apt-get update seems to fail because of that. https://github.com/chipsalliance/verible/runs/4798055615?check_suite_focus=true
Unless there is a simpler work-around, given that Groovy is a short-term distribution and reached [EOL last summer](https://fridge.ubuntu.com/2021/07/25/ubuntu-20-10-groovy-gorilla-end-of-life-reached-on-july-22-2021/), not having a release seems fine.
=> Remove ubuntu groovy release.

common/formatting/unwrapped_line.cc, common/formatting/unwrapped_line.h, common/formatting/unwrapped_line_test.cc, verilog/formatting/BUILD, verilog/formatting/comment_controls.cc, verilog/formatting/comment_controls.h, verilog/formatting/comment_controls_test.cc, verilog/formatting/formatter.cc, verilog/formatting/formatter.h, verilog/formatting/formatter_test.cc
emits a range of lines.
This is needed for use in the language server that generally only
requests a user-requested sub-set of lines to be formatted.
We can't just use the regular FormatVerilog() with a sub-range,
as it is not possible to determine which of the formatted output
lines correspond to the original region, hence we need a function
that _only_ outputs the code from the original region.
=> Add FormatVerilogRange() formatting functions that only formats and

verilog/tools/ls/lsp-parse-buffer.cc
... instead of hardcoded 'all the rules'.
=> Get Linter configuration for language server from flags.

verilog/formatting/formatter.cc, verilog/formatting/formatter.h, verilog/tools/ls/BUILD, verilog/tools/ls/lsp-parse-buffer.cc, verilog/tools/ls/lsp-parse-buffer.h, verilog/tools/ls/verible-lsp-adapter.cc, verilog/tools/ls/verible-lsp-adapter.h, verilog/tools/ls/verible-verilog-ls_test.sh, verilog/tools/ls/verilog_ls.cc
For this formatting option, the regular FormatVerilog() is
used that does a validation step over the whole file to make
sure the file is not messed-up accidentally.
For that, factor out the internal part of FormatVerilog() that
takes a text structure (which is what we have available in the
language server) and writes to a string; this is then used in
the original FormatVerilog() that does additional checks.
=> Add full-file formatting in the language server.

common/text/text_structure.cc, common/text/text_structure.h
This in particular helps performance for expanding subtrees
that frequently rebase tokens.
=> Calculate Lines() and GetLineColumnMap() lazily once needed.

common/formatting/layout_optimizer.cc, common/formatting/layout_optimizer_test.cc
This change will prevent juxtaposition of code fragments that should never be joined into one line, e.g. `//`-comment and regular code.
Instead of aborting, an attempt of such juxtaposition emits non-fatal error and calls `stack` combinator (which is safe in all cases I can think of).
=> Prevent juxtaposition of "MustWrap" lines.

common/analysis/lint_waiver.cc, common/text/text_structure.cc, common/text/token_stream_view.cc
=> Use const references instead of const value in range loops.

.clang-tidy, common/analysis/lint_rule_status.cc, common/analysis/lint_waiver.cc, common/formatting/align.cc, common/formatting/layout_optimizer.cc, common/strings/diff.cc, common/text/concrete_syntax_tree.cc, common/tools/patch_tool.cc, verilog/CST/port.cc, verilog/analysis/checkers/always_comb_blocking_rule.cc, verilog/analysis/checkers/forbidden_macro_rule.cc, verilog/analysis/checkers/forbidden_symbol_rule.cc, verilog/analysis/checkers/module_instantiation_rules.cc, verilog/analysis/checkers/parameter_name_style_rule.cc, verilog/analysis/checkers/plusarg_assignment_rule.cc, verilog/analysis/checkers/signal_name_style_rule.cc, verilog/analysis/checkers/truncated_numeric_literal_rule.cc, verilog/analysis/checkers/undersized_binary_literal_rule.cc, verilog/analysis/checkers/void_cast_rule.cc, verilog/analysis/verilog_excerpt_parse.cc, verilog/analysis/verilog_linter.cc, verilog/analysis/verilog_linter_configuration.cc, verilog/formatting/formatter.cc, verilog/tools/ls/verible-lsp-adapter.cc, verilog/tools/preprocessor/verilog_preprocessor.cc, verilog/tools/syntax/verilog_syntax.cc
Also organized the .clang-tidy rules to sort disabled rules.
Unfortunately, we can't have readability-qualified-auto on by
default, as it also suggests to qualify the return value of
absl::string_view::begin() with const auto* - which can be wrong
as absl::string_view might be typedefed to std::string_view whose
iterator type is implementation defined. So this change does
not touch any suggestions that involves iterators.
=> Fix some clang-tidy warnings found by readability-qualified-auto.

releasing/README.md, releasing/centos/8/compiler.dockerstage, releasing/docker-run.sh, releasing/supported_bases.txt
CentOS 8 is EOL and fails to build as a consequence
Closes #1165
=> Removed CentOS 8 release as it is EOL

verilog/tools/kythe/BUILD, verilog/tools/kythe/kythe_facts.cc, verilog/tools/kythe/kythe_facts.h, verilog/tools/kythe/scope_resolver.h
This sped up indexing of earlgray about 3x (3:30min -> 1:10min)
=> Use flat_hash_map instead of std::map in ScopeResolver.

common/formatting/layout_optimizer.cc, common/formatting/layout_optimizer_internal.h, verilog/formatting/formatter_test.cc
`style_.line_break_penalty` is already added in Stack combinator.
`kEarlierLinesFavoringPenalty` has been propagating to output layout function, which caused it to have slightly higher cost. Moreover, this penalty is not even needed - Choice operator already favors its earlier arguments when costs are the same.
The comparison function in Choice operator should return true only for lower costs, not lower or equal.
=> Fix penalties in Layout Optimizer's Wrap combinator

verilog/tools/kythe/BUILD, verilog/tools/kythe/scope_resolver.h
=> Don't use flat_hash_map where pointer stability is needed.

common/formatting/token_partition_tree.cc, common/formatting/token_partition_tree.h, common/formatting/unwrapped_line.cc, common/formatting/unwrapped_line.h, common/formatting/unwrapped_line_test.cc, verilog/formatting/tree_unwrapper.cc, verilog/formatting/tree_unwrapper.h
before:
```
{ (>>>>>>>>>>[<auto>], policy: wrap) @{3,1,0,1,1}, (origin: "`gfn, $sfor..., UVM_DEBUG")
{ (>>>>>>>>>>[`gfn ,], policy: fit-else-expand, (origin: "`gfn")) }
{ (>>>>>>>>>>[<auto>], policy: juxtaposition-or-indented-stack) @{3,1,0,1,1,1}, (origin: "$sformatf("..._pulses, i)")
{ (>>>>>>>>>>[<auto>], policy: wrap) @{3,1,0,1,1,1,0}
{ (>>>>>>>>>>[$sformatf], policy: fit-else-expand, (origin: "$sformatf")) }
{ (>>>>>>>>>>[(], policy: fit-else-expand, (origin: "(")) }
}
{ (>>>>>>>>>>>>>>[<auto>], policy: wrap) @{3,1,0,1,1,1,1}, (origin: ""a %0d b %0...m_pulses, i")
{ (>>>>>>>>>>>>>>["a %0d b %0d" ,], policy: fit-else-expand, (origin: ""a %0d b %0d"")) }
{ (>>>>>>>>>>>>>>[cfg . num_pulses ,], policy: fit-else-expand, (origin: "cfg.num_pulses")) }
{ (>>>>>>>>>>>>>>[i ) ,], policy: …
```
=> Add support for custom UnwrappedLine's Origin printer

common/lsp/json-rpc-dispatcher.cc, verilog/tools/ls/BUILD, verilog/tools/ls/lsp-parse-buffer.cc, verilog/tools/ls/verilog_ls.cc
While at it: also log size of JSON RPC requests. And fix
outdated comment for the stream splitter (buffer sizes are
dynamically adapted these days).
=> Use proper logging instead of std::cerr.

common/lsp/lsp-protocol.yaml, verilog/tools/ls/README.md
* File feature requests #1187, #1188, #1189, #1190
* Reference these in the README to easily follow progress
* Write JSON RPC protocol definition for these features.
=> Sketch out next steps in language server features

verilog/tools/kythe/kythe_facts_extractor.cc, verilog/tools/kythe/kythe_facts_extractor.h, verilog/tools/kythe/kythe_proto_output.cc, verilog/tools/kythe/kythe_proto_output.h, verilog/tools/kythe/verilog_kythe_extractor.cc
Instead of collecting the final result in an ever-growing set
before printing, write them out as they are received to
minimize memory use.
This _could_ result in the same facts be emitted multiple times
if there are duplicates (can there ?), but this is benign.
Make StreamKytheFactsEntries() the main toplevel function.
Remove the ExtractKytheFacts() that accumulates everything in
sets first.
=> Always stream the final Kythe result.

verilog/tools/kythe/kythe_facts.cc, verilog/tools/kythe/kythe_facts.h, verilog/tools/kythe/kythe_facts_extractor.cc, verilog/tools/kythe/kythe_facts_test.cc, verilog/tools/kythe/scope_resolver.cc, verilog/tools/kythe/scope_resolver.h
In a particular sample file, that reduced the processing time
from 48min to 8 seconds.
=> Replace linear search in Scope::SearchForDefinition() with map lookup.

verilog/tools/kythe/BUILD, verilog/tools/kythe/kythe_facts.h, verilog/tools/kythe/kythe_facts_extractor.cc, verilog/tools/kythe/scope_resolver.h
All strings are backed by the text structure ultimately.
There is one string that is generated ad-hoc, which is the
assembled location string "@123:456"; this is now kept in
a stable backing store.
In a test with a particular large file, this resulted in
some significant improvement:
311s -> 232s (25% improvement).
TODO: storing these vectors of strings seems like a waste
of space; couldn't we just have a string-view and a pointer to
the parent signature ?
=> Store string_view in Signature() array, not std::string.

verilog/tools/kythe/indexing_facts_tree.h, verilog/tools/kythe/kythe_facts_extractor.cc, verilog/tools/kythe/kythe_facts_extractor.h, verilog/tools/kythe/kythe_proto_output.h, verilog/tools/kythe/scope_resolver.cc, verilog/tools/kythe/scope_resolver.h
Not enabled in CI yet, there are still some non-const references
in parameters to functions.
=> Fix a few clang-tidy warnings in kythe.

verilog/tools/kythe/kythe_facts_extractor.cc, verilog/tools/kythe/scope_resolver.cc, verilog/tools/kythe/scope_resolver.h
The ScopedMemberItem struct only contains a single element,
a VName, so let's use that directly. Left the typename, so
that it will be possible to convert back to a struct if need be.
=> Use the single element in ScopedMemberItem directly.

verilog/analysis/verilog_project.cc, verilog/analysis/verilog_project.h
If we can generate detailed parse error messages, output these
instead of a generic error status. This will improve Kythe logging.
=> Project: If we have specific parse error messages, provide these.

verilog/tools/kythe/kythe_facts.cc, verilog/tools/kythe/kythe_facts.h, verilog/tools/kythe/kythe_facts_test.cc
=> With all uses of std::set gone, operator< not needed anymore.

common/text/concrete_syntax_tree.h
In a particularly large file, this sped up the formatting by
a factor of > 2x (34sec -> 16sec).
=> Unroll OR expression on initializer list in MatchesTagAnyOf()

.github/workflows/verible-ci.yml
According to this blog post, cache size was
increased from 5GiB to 10GiB.
https://github.blog/changelog/2021-11-23-github-actions-cache-size-is-now-increased-to-10gb-per-repository/
=> Re-enable bazel caching action for Windows.

.github/bin/smoke-test.sh, common/formatting/layout_optimizer.cc, common/formatting/layout_optimizer.h, common/formatting/layout_optimizer_internal.h, common/formatting/layout_optimizer_test.cc, common/formatting/unwrapped_line.cc, common/formatting/unwrapped_line.h, common/formatting/unwrapped_line_test.cc, common/util/iterator_range.h, common/util/iterator_range_test.cc, verilog/formatting/formatter.cc, verilog/formatting/formatter_test.cc, verilog/formatting/token_annotator.cc, verilog/formatting/token_annotator_test.cc, verilog/formatting/tree_unwrapper.cc, verilog/formatting/tree_unwrapper.h, verilog/formatting/tree_unwrapper_test.cc
Fixes: #1130 
Improved formatting of macro calls which takes into account many edge cases (like comments in various places of the call).
The new formatting is applied to:
* Standalone macro calls
* Macro calls nested inside standalone macro calls and other affected nested calls
Support for other cases (calls inside `if` conditions, in assignments, etc) will be done after implementing layout optimizer formatting for other structures.
Warning: the reshaping code is pretty messy, and does not work perfectly. However, it works better than current implementation. I'm going to revisit it after refactoring TokenPartitionTree and implementing kChoice partition policy. The choice operator should simplify things a lot.
There are also some other features:
* Partition policies for some Layout …
=> Improve macro call formatting

common/util/vector_tree.h
After erase(), the iterator to use it is invalid. Use
the new location it returns for the subsequent insert().
=> Fix possible correctness bug in VectorTree.

verilog/parser/verilog.y, verilog/parser/verilog_parser_unittest.cc, verilog/parser/verilog_token_classifications.cc
=> Fix to make 'infinite' usable as symbol.

verilog/formatting/verilog_token.cc, verilog/parser/verilog.lex, verilog/parser/verilog.y, verilog/parser/verilog_lexer_unittest.cc, verilog/parser/verilog_parser_unittest.cc
Right now, it is not used as a keyword anywhere, so not even
a need to make it a KeywordIdentifier.
Fixes #753
=> Make "slew" a simple SymbolIdentifier.

verilog/parser/verilog.y, verilog/parser/verilog_parser_unittest.cc, verilog/parser/verilog_token_classifications.cc
=> Allow keyword 'continuous' also to be used in an identifier context.

common/formatting/BUILD, common/formatting/layout_optimizer.cc, common/util/logging.h
This allows us a simpler change once logging is available in
absl directly.
=> Move include of vlog_is_on.h into generic logging.h

common/strings/obfuscator.h, common/strings/obfuscator_test.cc, verilog/tools/obfuscator/verilog_obfuscate.cc, verilog/transform/obfuscate.cc, verilog/transform/obfuscate.h, verilog/transform/obfuscate_test.cc
Since we can't easily ask the lexer for a definitive list of keywords
that are not SymbolIdentififier's, we simply use it as an oracle while
generating a random name.
Fixes #1072
=> Obfuscator: Make sure to not accidentally generating keywords for identifier

verilog/formatting/formatter_test.cc, verilog/formatting/tree_unwrapper.cc
o There is an empty if() block which should either be filled,
removed or documented.
o Consider splitting up a very large function.
o Remove unnecessary whitespace line and unused using-decl.
=> Document a few readability TODOs and remove unnecessary lines.

.github/bin/build-and-test.sh, common/strings/BUILD, verilog/transform/BUILD, verilog/transform/obfuscate_test.cc
While here only used in a test, this is an error-prone pattern.
Also fix slightly changed dependencies needed with the recent move
of using random identifier generation closer to the specific
verilog tool.
=> Don't rely on implicit const char* -> bool conversion.

verilog/CST/BUILD, verilog/CST/expression.cc, verilog/CST/expression.h, verilog/CST/expression_test.cc, verilog/parser/verilog_token_classifications.cc, verilog/parser/verilog_token_classifications.h, verilog/parser/verilog_token_classifications_test.cc
This reduces stack depth for long chained expressions.
Fixes #1236
=> Flatten associative binary operations.

.github/bin/smoke-test.sh, verilog/analysis/symbol_table.cc, verilog/analysis/symbol_table_test.cc
Reserve number of reference branches for calls using named parameters.
Fixes #1002
=> [symbol-table] Reserve for named call parameters

common/util/BUILD, common/util/container_proxy.h, common/util/container_proxy_test.cc
TL;DR: Utility class needed for https://github.com/chipsalliance/verible/pull/1252, potentially useful in some other cases.
---
CRTP base class for creating modification tracking STL container proxies.
The class allows safe exposition of a STL container to an user in cases where
changes to the container must be pre-/post-processed. This is done through
implementation of several event handling methods in a derived class.
Example use case: List of child nodes in a tree which sets parent when
a child is inserted.
Note that the proxy only tracks container changes. It does not track
individual elements.
Derived class interface
-----------------------
- Mandatory:
- `ContainerType& underlying_container()`,
`const ContainerType& underlying_container() const`:
Returns reference to the wrapped …
=> Add ContainerProxy

.github/bin/smoke-test.sh, verilog/parser/verilog.y, verilog/parser/verilog_parser_unittest.cc
Simplify the grammar without making a special case for wreal.
Fixes #1017
=> Treat wreal like any other primitive data type.

common/util/BUILD, common/util/vector_tree.h, common/util/vector_tree_test.cc
This PR implements `VectorTreeChildrenList` class, which extends `ContainerProxyBase` to create a wrapper for `std::vector` containing VectorTree nodes. The class automatically sets correct `parent_` pointer in each inserted node, where the "correct" pointer is passed in a constructor.
The class is used in VectorTree as a child nodes storage (`children_` member), and as a public interface for children list access and manipulation (retured as a reference from `Children()` method).
As a result VectorTree's `parent_` member is only set/modified either in VectorTree's constructor or assignment, or inside VectorTreeChildrenList.
Only VectorTree methods were modified to take advantage of this new class. Other code still uses methods like `NewChild()` for inserting nodes. I'll update the …
=> Use ContainerProxy for VectorTree's children list

verilog/formatting/tree_unwrapper_test.cc
`TokenPartitionTree` is currently an alias to `VectorTree<UnwrappedLine>`, but it will be promoted to a class soon.
=> Use TokenPartitionTree instead of VectorTree<UnwrappedLine>

common/lsp/lsp-protocol-operators.h, common/lsp/lsp-protocol-operators_test.cc, common/lsp/lsp-protocol.yaml, verilog/tools/ls/verible-verilog-ls_test.sh
codeAction requests often just include the cursor position in the
request which is an empty range. If the diagnostic in question is
a one-character range, make sure we recognize that as overlap.
=> LSP Range: allow empty range overlap predicate.

common/lsp/lsp-protocol.yaml, verilog/tools/ls/verible-lsp-adapter.cc, verilog/tools/ls/verible-lsp-adapter.h, verilog/tools/ls/verible-verilog-ls_test.sh, verilog/tools/ls/verilog_ls.cc
Specification:
https://github.com/microsoft/vscode-languageserver-node/blob/main/protocol/src/common/proposed.diagnostic.md
=> LSP: Implement proposed pull diagnostic request.

common/analysis/file_analyzer.cc, common/analysis/file_analyzer.h, common/analysis/file_analyzer_test.cc, verilog/analysis/json_diagnostics.cc, verilog/analysis/verilog_analyzer.cc, verilog/preprocessor/verilog_preprocess.cc, verilog/preprocessor/verilog_preprocess.h, verilog/tools/lint/BUILD, verilog/tools/lint/lint_tool_test.sh, verilog/tools/ls/verible-lsp-adapter.cc, verilog/tools/syntax/verilog_syntax_test.sh
So far, all messages in the lex/preprocessing/parse phase have been
of 'error severity'. However, there are issues whose severity can
be lower e.g. warning about re-definition of a macro.
In this change
* Make RejectedToken contain a severity (name of that object
is still the same, might need some re-name later)
* Change printing of rejected tokens to include the severity
and don't talk about a 'rejected token', but just the token
a hand; that does sound more user-friendly (the 'rejected'
sounds more like an artifact of parsing).
CAVE: this might trip up scripts of users that grep for
messages.
* Surface preprocessing re-definition as warning message.
* Do _not_ include the preprocessing warning yet in the output
of the parser; merely LOG(INFO) it at this point.
(Reason: might be too …
=> Parsing/Preprocessing: add the concept of 'warning'.

common/analysis/file_analyzer.cc, common/analysis/file_analyzer_test.cc, common/analysis/lint_rule_status.cc, common/analysis/lint_rule_status_test.cc, common/strings/line_column_map.cc, common/strings/line_column_map_test.cc, verilog/analysis/verilog_linter_test.cc, verilog/tools/lint/lint_tool_test.sh, verilog/tools/syntax/verilog_syntax_test.sh
If the token mentioned in a syntax error covers more than one character,
print syntax error with the full column range.
=> Format syntax errors always with column range.

common/text/macro_definition.h, verilog/preprocessor/verilog_preprocess.cc
Use the token that represents the name.
=> Report name of redefined macro, not body.

verilog/tools/ls/verible-lsp-adapter.cc, verilog/tools/ls/verible-lsp-adapter.h, verilog/tools/ls/verilog_ls.cc
While we limit the number of diagnostic messages we send in the
unsolicted notification to the editor, don't do that if explicitly
requested in the textDocument/diagnostics RPC request.
=> Don't limit the diagnostic messages for textDocument/diagnostics

verilog/preprocessor/verilog_preprocess.cc, verilog/preprocessor/verilog_preprocess.h, verilog/preprocessor/verilog_preprocess_test.cc
* Simplify testing: move repetetive parse testing into
separate macro.
* Also, simplify the warning for macro definition - directly
fill in warning.
* Document that `define stay in the filtered token stream.
=> Start documenting more behavior in preprocessor unit test.

common/analysis/linter_test_utils.h, verilog/CST/expression_test.cc, verilog/analysis/BUILD, verilog/analysis/extractors.cc, verilog/analysis/extractors.h, verilog/analysis/extractors_test.cc, verilog/analysis/verilog_analyzer.cc, verilog/analysis/verilog_analyzer.h, verilog/analysis/verilog_analyzer_test.cc, verilog/analysis/verilog_excerpt_parse.cc, verilog/analysis/verilog_excerpt_parse.h, verilog/analysis/verilog_linter.cc, verilog/formatting/formatter.cc, verilog/formatting/formatter_test.cc, verilog/parser/verilog_parser_unittest.cc, verilog/preprocessor/BUILD, verilog/tools/ls/lsp-parse-buffer.cc, verilog/tools/obfuscator/verilog_obfuscate.cc, verilog/tools/syntax/verilog_syntax.cc
Add VerilogPreprocess::Config to all analyzer convenience
methods, such as AnalyzeAutomaticMode() but as well as all
the excerpt parse methods, such as AnalyzeVerilogExpression(...).
Wire this up all the way to the tools where they are used (and tests),
but choose the safe preprocessor choice defaults for now, to be
changed later.
So no functional change right now, just preparation to make it
possible to choose configuration.
=> Surface the verilog preprocessor config up one level.

verilog/analysis/verilog_analyzer.cc
In case branch filtering is on, situations such as
```SystemVerilog
`ifdef FOO
`define BAR 1
`else
`define BAR 2
`endif
```
will not result in 'duplicate' definitions of `BAR` anymore, so
promoting this warning to an actual warning that surfaces for the user
is useful.
=> Emit preprocessor warnings when doing preprocess branch filtering.

verilog/tools/syntax/verilog_syntax.cc
I was considering making this configurable via flags, but this is
a strong case of 'this should just do the right thing'.
We _might_ need to start allowing `+define+` command line options,
but that is on my short-list of things to implement.
=> Always use branching preprocessing with the syntax checker.

verilog/analysis/verilog_analyzer.cc, verilog/analysis/verilog_analyzer.h, verilog/analysis/verilog_analyzer_test.cc
The new AnalyzeAutomaticPreprocessFallback() is attempting to
1) Parse fully with all preprocess branches enabled. If that
results into a syntax error, possibly due to incomplete
resulting SystemVerilog statements, proceed to
2) Parse, but filter out preprocessing branches.
Doing (1) first allows to retain as much as possible information
in the parse tree (useful in many contexts from linting to
language server), but the fallback to (2) allows to cover more
cases.
This then can be used in #1290 #1293 and #1294
=> Provide a automatic analyze with preprocess branch filter fallback.

verilog/tools/ls/lsp-parse-buffer.cc, verilog/tools/ls/lsp-parse-buffer.h
First attempt to parse without preprocessing to be able to
lint all preprocessing branches. However, if that fails (because
it sometimes might result in incomplete parse issues), attempt
to do the same parsing with preprocess branch filtering enabled.
=> LanguageServer: Use parse fallback with preprocessing.

verilog/analysis/verilog_linter.cc, verilog/analysis/verilog_linter.h
Parsing without filtering the preprocessing branches will work
most of the time and provide more 'material' for the linter to look
over. But if parsing fails in that case (because it can result
in invalid syntactic constructs), retry with preprocessing
branches enabled.
=> Linter: if needed, make two parse attempts with and w/o pp-branches.

WORKSPACE
The previous version is no longer available for download and breaks builds.
=> Update zlib package from 1.2.11 to 1.2.12

verilog/parser/verilog.y, verilog/parser/verilog_parser_unittest.cc
This PR introduces a fix for declaring a net with delay, which is allowed by LRM (A.2.1.3) as:
`net_declaration ::= net_type [...] data_type_or_implicit [delay3] list_of_net_decl_assignments ;`
Added test: 
```verilog
module m; 
wire #(100) x = y,z=k,foo; 
endmodule
```
Proposed modification to 'verilog.y' grammer:
- 'net_declaration' rule now accepts:
` net_type delay3 net_variable_or_decl_assigns ';'`
Explanation:
'net_declaration' rule accepts  ` net_type data_type_or_implicit net_variable_or_decl_assigns ';'`
Which pares this line correctly
```verilog
wire  [12:0] #(100) x = y; 
```
Because 'data_type_or_implicit' accepts `decl_dimensions delay3_or_drive_opt`
Notice 'decl_dimensions' is not optional here, so removing it causes a problem.
An easy workaround would be to add a new rule …
=> Fixing syntax error on wire delay value 

.github/bin/smoke-test.sh
Tools fail on some of the files. So far, we only were concerned about
crashes in tool in the smoke tests, but recently improvements have
been sen in also reducing the number of files we can't process.
This change documents how many of these failures are to be expected
to make sure we don't add regressions (if failures increase, the
smoke test will fail), but also detect when we see less than expected
failures.
=> Document for each project the expected number of tool failures.

WORKSPACE
The main URL to zlib sources from zlib.net
(https://zlib.net/zlib-1.2.12.tar.gz) will probably stop working after
new release. This is what happened with the URL to version 1.2.11.
https://zlib.net/fossils/ contains packages for versions released since
1995, so I assume the link to a package in this directory will be more
stable.
=> Add more stable URL to zlib sources.

shell.nix
=> Update shell.nix to use current stable version.

common/text/text_structure.cc, common/text/text_structure.h, common/text/text_structure_test.cc, verilog/analysis/symbol_table.cc, verilog/analysis/symbol_table_test.cc
Provide location of new and previous definition of a symbol that
is found out to be re-defined.
=> SymbolTable: provide more detailed information about re-defined symbols.

common/analysis/citation.cc, common/analysis/citation.h, common/analysis/lint_rule_status.h, verilog/analysis/checkers/create_object_name_match_rule.cc, verilog/analysis/checkers/forbidden_macro_rule.cc, verilog/analysis/checkers/forbidden_symbol_rule.cc, verilog/analysis/checkers/uvm_macro_semicolon_rule.cc, verilog/analysis/checkers/void_cast_rule.cc, verilog/analysis/descriptions.h, verilog/analysis/verilog_linter.cc
Distinguishing between dv-style and regular style seems unnecessarily
complictaed.
Co-authored-by: Sergey Sokolov <snsokolov@users.noreply.github.com>
=> Simplify style guide citations: just have one topic.

common/util/expandable_tree_view.h, common/util/expandable_tree_view_test.cc, verilog/formatting/formatter.cc
Since tree methods are now generic, there's no reason to limit `ExpandableTreeView` to `VectorTree` class.
=> ExpandableTreeView: Add support for tree types other than VectorTree.

common/util/container_proxy.h, common/util/vector_tree.h
Use of a single macro instead of a long list of methods is more readable and makes it easier to inherit correct methods.
=> ContainerProxy: Add macros for inheriting common sets of members.

common/text/macro_definition.cc, common/text/macro_definition.h, verilog/analysis/verilog_analyzer.cc, verilog/preprocessor/BUILD, verilog/preprocessor/verilog_preprocess.cc, verilog/preprocessor/verilog_preprocess.h, verilog/preprocessor/verilog_preprocess_test.cc
**Description:**
This PR introduces a way to handle macro calls, instead of substituting the macro identifier with the definition text (`PP_define_body` token), the preprocessor re-lexes the definition text, and feed the new lexed tokens to the next stage (parser by default).
**Example:**
```verilog
`define DELAY #100
module m;
wire `DELAY x=y;
endmodule
````
Old behavior:
`DELAY` is substituted with a ``PP_define_body`` token, then parser matches it to a  `GenericIdentifier`.
New behavior:
`DELAY` is substituted with 2 token describing `#` and `100`
**Changes:**
- `MacroDefinition`:
- Added a field to save the lexed macro definitions as a vector of tokens
- Added two methods to set/ get this field.
- `VerilogPreprocess`:
- Added `HandleMacroIdentifier` method which searches for the macro …
=> [WIP] implementing ExpandMacro method in the preprocessor

.github/bin/smoke-test.sh
Since we're using 'live' projects, the number of errors
we see are fluctuating. Update to current state.
=> Update expecations in the smoke test.

.github/bin/github-releases-setup.sh
On jammy, we need the additional --//bazel:use_local_flex_bison
option that was not passed to the bazel run :install failing
to produce install binaries for Ubuntu jammy.
Fixes #1369
=> Include the BAZEL_OPTS when runing :install for the release

verilog/formatting/formatter_test.cc
In an #if 0 block as it would fail right now.
=> Document #1381 with a test.

verilog/formatting/formatter_test.cc
... found with a fuzzer, so the input looks a bit random :)
=> Document UseAfterFree bug

verilog/formatting/formatter_test.cc
If-def'ed out by default so that the remaining tests pass.
Output:
```
F20220812 00:05:11.462432    12 token_partition_tree.cc:63] Check failed: parent_begin == children_begin (2 vs. 3) node:
{ (>>>>>>>>[<auto>], policy: append-fitting-sub-partitions) @{0,1,1,0}, (origin: "`c()")
{ (>>>>>>>>[(], policy: fit-else-expand, (origin: "(")) }
{ (>>>>>>>>[)], policy: fit-else-expand, (origin: "")) }
}
```
=> Document invariant violation found by fuzzer

.github/settings.sh
The USE_BAZEL_VERSION appears to be unnecessarily strict enforcement
of a particular bazel version when anything > 3.x.x should typically
work.
=> Don't force a particular bazel version.

.github/bin/build-and-test.sh
Depending on the platform, there might not be a versioned binary
such as clang-12 available. Fall back to simply clang then.
=> Use unversioned clang/clang++ if versioned binaries don't exist.

.gitignore
These files are typically user configurations never meant to
be submitted.
=> Add .envrc and .direnv to gitignore.

.github/bin/build-and-test.sh, .github/bin/generate-coverage-html.sh, shell.nix
Thus it is possible to test if a particular unit test provides all the
necessary coverage, not other tests that accidentally cover that code
path.
Update dependencies to run coverage in development environment.
=> Make it simpler to create coverage for a particular target.

WORKSPACE
They have fixes that should work on freeBSD, i.e. they
might start working on MacOS.
=> Update the install rules to latest.

verilog/formatting/BUILD, verilog/formatting/formatter_test.cc, verilog/formatting/tree_unwrapper.cc
Partial fix of #1386.
The tests that remain commented-out fail with status message:
```
Formatted output is lexically different from the input.    Please file a bug.  Details:
Mismatched token enums.  got: (MacroCallCloseToEndLine) (#711: ")") vs. (')') (#41: ")")
First mismatched token [2]: (MacroCallCloseToEndLine) (#711: ")") vs. (')') (#41: ")")
First mismatched token [2]: (MacroArg) (#710: "`c()\0;") vs. (MacroArg) (#710: "`c();")
```
The first mismatch is caused by existence of two `)` tokens (real `)` and `MacroCallCloseToEndLine`), which are detected differently due to changed formatting.
The second mismatch is caused by removal of `\0` (`\n` in the other test case).
=> Flatten whole subtree in argumentless kMacroCalls.

README.md, WORKSPACE
So now this should compile cleanly there as well.
Fixing #957
=> Use newer rules for m4, fixing the glibc 2.34 compile issues.

.github/bin/build-and-test.sh, README.md, WORKSPACE, shell.nix
This required update of rules_pkg, which in turn requires bazel 4
as minimum requirement. We're using bazel4 anyway for years, so that
is not a huge limitation.
=> Update to latest protobuf lib.

releasing/centos/common/bazel.dockerstage
=> Centos: Switch to bazel4 (a recent protobuffer change requires that)

releasing/ubuntu/common/compiler.dockerstage
Similar to the xenial and bionic distributions (that require a different
g++), also use the static libstdc++ linking for releases of the newer
ubuntus. That way we are slighly more resilient to library version
mismatch in case the download is attempted to run in
Debian distributions/releases.
Downside: larger release tar to download.
=> Unbutu releases: also link libstc++ statically for newer distributions.

.github/bin/smoke-test.sh
Upstream projects have changed, so adapt the number of reported
issues we see.
=> Update expected failures in smoke tests.

verilog/tools/ls/verilog_ls.cc
Suspect it messes with the line-endings otherwise.
Issues: #1343
=> Explicitly set stdout to binary for Windows.

verilog/tools/kythe/filelist_parser_test.py
=> Use fully qualified name for Py import.

common/tools/jcxxgen.cc, common/tools/patch_tool.cc, common/util/init_command_line.cc, common/util/init_command_line.h, common/util/subcommand.h, common/util/subcommand_test.cc, verilog/tools/preprocessor/verilog_preprocessor.cc, verilog/tools/syntax/verilog_syntax.cc
For all intendt and purposes, we're only interested in string_view
for the positional parameters and in particular do not want to encourage
modifying them (in particular since all kind of split operations can
cheaply and easily be done in the string_view domain).
The `char*` was just a leaked implementation detail of the
underlying main() entry point which happens to return a writable
buffer.
=> Make InitCommandLine() return vector of string_view instead of char*

verilog/analysis/flow_tree_test.cc, verilog/tools/preprocessor/BUILD, verilog/tools/preprocessor/verilog_preprocessor.cc
* Since we're using the flag header, need to also link the
corresponding library
* We never use token_stream_adapter, so let's not add
that dependency.
* Remove some unnecessary trailing whitespace.
=> Fix missing dependency, drop header not needed

common/analysis/violation_handler.cc, common/formatting/layout_optimizer_internal.h
We're using absl::string_view as a compatibility guarantee for
different platforms, so let's use it throughout.
=> Fix accidental use of std::string_view instead lf absl::string_view.

verilog/analysis/verilog_project.cc, verilog/analysis/verilog_project.h, verilog/analysis/verilog_project_test.cc, verilog/tools/preprocessor/BUILD, verilog/tools/preprocessor/verilog_preprocessor.cc
This PR implements: `ParseSourceFileListFromCommandline(const std::vector<absl::string_view>& cmdline_args)`
Which parses the command line arguments into a `FileList` that now contains a vector holding the definitions passed through `+define+`.
Note: `ParseSourceFileListFromCommandline` is not yet used in the preprocessor tool.
=> Adding support of +define+ in FileList.

verilog/preprocessor/verilog_preprocess.cc, verilog/preprocessor/verilog_preprocess.h, verilog/preprocessor/verilog_preprocess_test.cc, verilog/tools/preprocessor/verilog_preprocessor.cc, verilog/tools/preprocessor/verilog_preprocessor_test.sh
The goal is to register the defines passed to the processor tool through `+define+<macro>[=<value>]` into the preprocessor defines map.
Added the method `VerilogPreprocess::AddDefineFromCmdLine` wihch internally registers defines using the method `VerilogPreprocess::RegisterMacroDefinition` to ensure that everything is aligned, and these passed defines are treated the same way as macros defined by `` `define <macro> <body>``.
Suggestion:
- It might be the time to use `MacroDefinition` instead of `TextMacroDefinition` to save defines in the `FileList` struct.
But, I am not sure about who will own the data itself as `MacroDefinition` only holds Tokens (string-views).
=> Adds the defines passed through +define+ into the preprocessor.

.clang-tidy, .github/bin/run-clang-tidy.sh
There is a recent change in glog that apparently triggers some clang-tidy issues (reason: unclar currently), but make sure that such things are detected properly.
=> Make clang-tidy cache dependent on WORKSPACE

.github/workflows/verible-ci.yml
=> Disable clang-tidy in CI for now, as it results in false positives.

common/analysis/lint_waiver.h, common/text/token_info.h
The copy construction does seem to generate warnings with later compilers.
It is not quite clear to me _why_ exactly this is happening (seems to be some implementation detail of std_function.h), but using std::move instad of function copy gets this working without warning.
```
/usr/include/c++/12/bits/std_function.h: In constructor 'verilog::VerilogLinter::VerilogLinter()':
/usr/include/c++/12/bits/std_function.h:267:7: note: by argument 2 of type 'const std::_Any_data&' to 'static bool std::_Function_handler<_Res(_ArgTypes ...), _Functor>::_M_manager(std::_Any_data&, const std::_Any_data&, std::_Manager_operation) [with _Res = bool; _Functor = verilog::VerilogLinter::VerilogLinter()::<lambda(const verible::TokenInfo&)>; _ArgTypes = {const verible::TokenInfo&}]' declared here
267 | …
```
=> std::move functions passed in constructors if possible.

.github/bin/build-and-test.sh
This is not an issue in the CI as we're running an older compiler there, but running build-and-test.sh locally on a current machine can easily trigger that.
Once we have a newer protobuf (attempt #1436 failed due to non-compatible changes), this should not be necessary anymore.
=> Disable a warning for newer gcc in protobuf

verilog/analysis/flow_tree.cc, verilog/analysis/flow_tree.h
Provide a constructor in ConditionalBlock that enforces setting the whole struct correctly at instruction time. Use that constructor when emplacing_back it into our `if_blocks`.
Since the positive/negative conditional can be expressed as a boolean, use that as an opportunity to simplify the initialization and eliminate duplicate code.
=> Initialize positive condition always. Simplify ifdef/ifndef block init

verilog/tools/project/project_tool.cc
Otherwise it might print out to stderr.
=> Don't log before logging is initialized.

common/lsp/json-rpc-dispatcher.h
Recent gcc 12 emits warnings when copying functions (which looks like some result if a standard library implementation detail). This doesn't happen if we simply std::move the function, so let's do that.
=> Move std::function in constructor.

common/formatting/layout_optimizer_internal.h, verilog/analysis/symbol_table.h
Context: C++20 compatibility.
Constraint proposed in
https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p1008r1.pdf
Newer compilers will warn about it.
Derived from #1428 (by @sschaetz) which used a slightly different but more involved proposal.
=> Don't provide constructors for objects meant to be initialized in aggregate init.

.github/bin/smoke-test.sh
Upstream tools we use to test changed, changing the number of errors we generate a little. Adapt these expectations.
=> Update smoke test expectations.

common/util/expandable_tree_view.h
This is another part of making the code compatible with C++20 (started #1428 and continued in earnest in #1451). [`std::iterator`](https://en.cppreference.com/w/cpp/iterator/iterator) is deprecated starting from C++20.
=> Remove std::iterator

common/util/simple_zip.cc, common/util/simple_zip.h, common/util/simple_zip_test.cc, verilog/tools/kythe/kzip_creator.cc, verilog/tools/kythe/kzip_creator.h
That way, it is easier to use. Add a test to verify functionality.
Removed corresponding call to Finish() in KzipCreator; while at it, RAII the zip::Encoder.
=> Automatically call Finish() in zip::Encoder on destruction.

BUILD, verilog/tools/kythe/BUILD, verilog/tools/kythe/verilog_kythe_kzip_writer.cc
We only need filelist as project dependency in filelist writer.
That reduces the project-specific dependencies significantly:
before:
$ bazel query 'deps(//verilog/tools/kythe:verilog-kythe-kzip-writer)' | grep -v '^@' | wc -l
246
after:
$ bazel query 'deps(//verilog/tools/kythe:verilog-kythe-kzip-writer)' | grep -v '^@' | wc -l
37
Unfortunately, this does not result in a binary size reduction for the
stripped binary. In both cases the binary is about the same size (and
one of the larger binaries in verible), which is probably because the
linker works well in figuring out cruft.
Maybe the size comes from the additional libraries, such as proto buffer
and crypto that it is so bloated ?
Also rename `verilog-kythe-kzip-writer` to `verible-verilog-kythe-kzip-writer`, as all our verible …
=> Reduce dependencies kzip writer; fix name.

common/text/concrete_syntax_leaf.h, common/text/concrete_syntax_tree.h
Having them final makes it clear for the reader that these are the only SyntaxTree classes to worry about when working with these.
=> Make SyntaxTree{Node,Leaf} final for better documentation.

verilog/tools/kythe/kythe_facts_extractor.cc
Also, rename to previously_extracted_facts_num, to make the `return` line read like a sentence.
=> Use opportunity to make extracted_facts_num const.

common/strings/BUILD, common/strings/mem-block.h, common/text/BUILD, common/text/text_structure.cc, common/text/text_structure.h
Right now files are read into a string, then copied into another string in TextStructure. With this abstraction of the block of memory we can allow for two things
a) read files into the string that is then moved into the
TextStructure with zero copy.
b) Allow for mmap()-ing a file for platforms that support it.
This is the first change towards this goal, introducing the MemBlock concept.
=> Introduce the concept of MemBlock to prepare for zero-copy file reading.

common/analysis/file_analyzer.h, common/text/text_structure.h, common/text/text_structure_test.cc
No functional change.
Only change: make the constructors for TextStructure private and add all uses within Verible as friend classes. That way it is easy to see where refactoring efforts need to go before we can remove TextStructure.
Improvd documentation of TextStructure and TextStructureView to describe the motivation.
=> Document uses of TextStructure for easier future refactoring.

common/strings/line_column_map.h, common/strings/line_column_map_test.cc, common/text/text_structure.cc
.. no need to do the line-splitting twice.
Also, document the remaining users of raw content
input of the constructor.
Remove unnecessary Clear() method on LineColumnMap (it never can be re-populated, so Clear() does not make sense).
=> Use already pre-split lines to create LineColumnMap.

common/analysis/file_analyzer.h, common/text/text_structure.cc, common/text/text_structure.h, verilog/analysis/BUILD, verilog/analysis/verilog_analyzer.h, verilog/analysis/verilog_project.cc, verilog/analysis/verilog_project.h, verilog/analysis/verilog_project_test.cc, verilog/tools/kythe/indexing_facts_tree_extractor_test.cc
To be able to have VerilogSourceFile content be used in contexts other than Analysis (as currently needed with preprocessing), break out the file content to live in a MemBlock in VerilogSourceFile. That way it can be used independently.
Then use that all the way down the VerilogAnalyzer chain for the regular behavior.
Using shared_ptr<MemBlock> for now limits worry about ownership while refactoring is going on: everyone can have their own (referenced counted-) copy of the MemBlock, minimizing the changes needed otherwise. Once the final picture is clear, this might be simplified by having a true central owner of the MemBlock with guaranteed life-time; then handing out Stringviews from there is cheaper.
Issues #1502
=> Provide content of file in a MemBlock living in VerilogSourceFile.

.github/bin/build-and-test.sh
Instead of just one, allow to provide mulitple targets to build for the script (default if no target given: //...)
=> Allow to provide multiple targets for build-and-test

common/strings/BUILD, common/strings/mem-block.h, common/strings/mem_block.h, common/text/text_structure.h, common/util/BUILD, common/util/file_util.cc, common/util/file_util.h, common/util/file_util_test.cc, verilog/analysis/verilog_analyzer.h, verilog/analysis/verilog_project.cc, verilog/analysis/verilog_project.h
* wire it up to the first user in verilog_project.
* Provide a memory mapping impelementation of creating a `MemBlock`
* Rename `mem-block.h` to `mem_block.h` (for consistency)
=> Provide a way to read files as MemBlock.

verilog/analysis/verilog_project.cc, verilog/analysis/verilog_project.h, verilog/analysis/verilog_project_test.cc, verilog/tools/kythe/indexing_facts_tree_extractor_test.cc
No need to provide access to a full MemBlock, just the string-view is needed.
(This is to prevent accessing the MemBlock at the wrong level).
=> Narrow type to access content in VerilogSourceFile.

verilog/preprocessor/verilog_preprocess.cc, verilog/preprocessor/verilog_preprocess.h, verilog/preprocessor/verilog_preprocess_test.cc, verilog/tools/preprocessor/verilog_preprocessor.cc, verilog/tools/preprocessor/verilog_preprocessor_test.sh
The goal is to support white-spaces in the prepreprocessor.
It's done by discarding some white-spaces (will not be able to regenerate them).
In `VerilogPreprocess` sometimes a token iterator is incremented to look for a macro name, or a include file name, in these situations we will not be able to retrieve the white-spaces.
The support for white-spaces should be added to the  preprocessor standalone tool in all modes:
A discussion about this problem is at #1358
=> Support whitespaces in VerilogPreprocess

.github/bin/smoke-test.sh
The upstream projects we test against have changed, so did the expected errors slightly.
=> Update expected baseline numbers for smoketests.

common/util/subcommand.cc, common/util/subcommand.h
Without that, the commands are just shown alphabetically, but the user of the subcommands might want to group these by importance. Always provide 'help' as first command.
While at it: remove the heterogenous lookup ifdefs as we are using C++17 throughout these days.
Update the "error" text so that calling 'help invalidcommand' provides a sensible message.
=> Preserve the sequence of commands provided by the user.

common/util/bijective_map.h
We're using C++17 throughout, so these code-cluttering ifdefs are not needed anymore.
=> Remove unnecessary heterogenous lookup ifdef.

verilog/analysis/symbol_table.cc, verilog/analysis/symbol_table.h, verilog/analysis/symbol_table_test.cc
In C++20, types that declare or delete any constructors are no longer aggregates, breaking compilation of many existing uses of aggregate initialization.
Fixes include:
* removing defaultings or deletions of only the default constructor
* removing defaultings of copy/move constructors
* adding constructors that accept the arguments passed to existing aggregate initialization sites, leaving the type no longer an aggregate
* removing a set of clearly-marked-as-boiler-plate copy/move/default constructor declarations
Also adds default member initializers for trivially default constructible members that can now be left uninitialized by construction of the form `Foo f;`
=> Fix C++20-incompatible instances of aggregate initialization

verilog/formatting/formatter_test.cc, verilog/formatting/tree_unwrapper.cc
This commit removes the error message when formatting system functions without parentheses, because they are formatted well after all.
Fixes #1280,
Fixes #1223,
Fixes #1247,
Fixes #1392.
=> Fix calling system functions without parentheses

common/formatting/layout_optimizer.cc, verilog/formatting/formatter_test.cc
This PR wraps the calculation of hanging_indentation in
`TokenPartitionsLayoutOptimizer::CalculateOptimalLayout`'s `kWrap` case to never let the value be negative, as it caused a check failure down the line.
This PR fixes #1242
=> Wrap hanging_indentation calculation  to avoid negative indentation values

.github/bin/build-and-test.sh, .github/bin/install-bazel.sh, .github/bin/set-compiler.sh, .github/settings.sh, .github/workflows/verible-ci.yml
This pull request modifies the CI pipeline definition and some related scripts so that the [custom runners](https://github.com/antmicro/runner) deployment for this repository is used.
What was changed:
* the `coverage` job will use the `@bazel_tools//tools/jdk:remote_jdk11` Java toolchain, as Java is not automatically installed in the container picked for the job.
* `sudo` is no longer necessary as the execution takes place in a container where privileges are already elevated.
* the `build` jobs install and start Docker explicitly. This way, the scripts that use Docker were left unchanged.
* all jobs run on `n2-highcpu-8` GCP machines, except for `ClangTidy` which runs on `n2-standard-4` (no need for a beefy machine as it doesn't do anything expensive).
The CI does not run on branches so …
=> Custom runners ci

.github/bin/smoke-test.sh, verilog/formatting/formatter_test.cc, verilog/formatting/tree_unwrapper.cc
This PR fixes #1006
In `void TreeUnwrapper::InterChildNodeHook`, `kPortList` was listed but commented out, making the comments not align properly. In the special case mentioned in #1006, an additional comment on a subsequent line triggered a CHECK fail in `common/formatting/align.h:419`. 
The change did not break any tests from `.github/bin/generate-coverage-html.sh`.
=> Bring kPortList back as a special case for comment formatting

verilog/formatting/formatter_test.cc, verilog/formatting/tree_unwrapper.cc
This PR fixes #1055 
There was a problem where the `TK_LINE_CONT` tokens were not included while `LookAheadBeyondCurrentLeaf()` was running causing the `\` characters were not attached to their lines in the test case eg. `bind bi i FP(\` was trying to get converted to 
```
bind bi i FP(
\
```
if the check that failed was to be disabled. This has made it attach itself to the line, no longer failing the condition `first_tree_token_it->before.break_decision != SpacingOptions::MustWrap`
There is also a test that had failed before the fix and now it doesn't.
=> Fix line continuation wrapping

verilog/tools/ls/BUILD, verilog/tools/ls/verilog-language-server.cc, verilog/tools/ls/verilog-language-server.h, verilog/tools/ls/verilog_ls.cc
The BUILD file was not containing all the dependencies yet that the header includes of the verilog-language-server needed.
While at it, move some headers that are only needed in the compilation unit there.
Encourage the formatter to format the closure wrapping the read() function to look more pleasing by adding a EOL comment at a strategic place.
=> Make sure to include all the used depdnencies in the BUILD file.

README.md
The old name was verible-ci.svg and that was passing ... however now that the CI currently is failing it became apparent, that we're pointing to the wrong image (the [name](https://github.com/chipsalliance/verible/blob/master/.github/workflows/verible-ci.yml#L1) determines the svg name; that was changed in [this commit](https://github.com/chipsalliance/verible/commit/dba385b7b0ec4610ec1c6d0d03229d2418900abd))
* Outdated CI image ![](https://github.com/chipsalliance/verible/workflows/verible-ci/badge.svg)
* Correct CI image ![](https://github.com/chipsalliance/verible/workflows/ci/badge.svg)
=> Point CI badge to the right image.

verilog/formatting/formatter_test.cc
When I was looking for another issue to fix, I came across #1035, which turned out to already work and format the case in a good way. In that case, I add the test to this case, and the issue related to it can be closed.
Fixes #1035.
=> Add test for two EOL comments in KDPIImportItem

verilog/formatting/align.cc, verilog/formatting/formatter_test.cc
Fixes #1146
With this PR `ivtest/ivltests/packed_dims_invalid_class.v` no longer fails. Also, it is formatted correctly.
I also added some test cases for this case.
=> Add more variants to ClassPropertyColumnSchemaScanner

.github/bin/smoke-test.sh
Bug #1146 was fixed in #1574. So we can remove the exemption in the smoke test.
=> Document fixed bug in smoke test.

verilog/formatting/formatter_test.cc, verilog/formatting/tree_unwrapper.cc
This PR fixes the following case:
```systemverilog
module test ();
reg x;
initial begin
#20 //test
x = 1;
x = 2;
end
endmodule
```
Fixes #1113.
=> Fix comment following a delay

verilog/CST/port.cc, verilog/CST/port.h, verilog/CST/port_test.cc, verilog/analysis/checkers/port_name_suffix_rule.cc, verilog/analysis/checkers/signal_name_style_rule.cc, verilog/tools/kythe/indexing_facts_tree_extractor.cc
There are (at least) two types of nodes that represent port declarations:
* `kPortDeclaration`, which, as far as I can tell, is used for port declarations in module headers,
* `kModulePortDeclaration`, which are port declarations in module bodies.
Currently, there are no helper functions that find or operate on the second kind. But there are ones for `kPortDeclaration`. Confusingly, they all have `ModulePortDeclaration` in their names:
* `FindAllModulePortDeclarations`,
* `GetDirectionFromModulePortDeclaration`,
* `GetIdentifierFromModulePortDeclaration`.
This PR renames them to `FindAllPortDeclarations`, `GetDirectionFromPortDeclaration`, `GetIdentifierFromPortDeclaration`. More importantly, it repurposes their old names for new functions that actually are related to …
=> Add helper functions for `kModulePortDeclaration`s

verilog/formatting/formatter_test.cc, verilog/formatting/tree_unwrapper.cc
Add a size check before merging leaves in `kDPIImportItem`/`kDPIExportItem`
Also add test to cover that case.
Fixes #1198
=> Add a size check before merging leaves in kDPIImportItem/kDPIExportItem

verilog/parser/verilog_lexical_context.cc, verilog/parser/verilog_lexical_context.h
This PR implements tracking of the delays in the context of `initial/always/final` constructs, where when delaying a statement which was an event trigger, the `_TK_RARROW` would be misinterpreted as an implication. This adds another condition to the `ExpectingStatement()` method such that after a delay it returns `true`.
Fixes #1596
=> Added delay tracking to verilog_lexical_context

.github/settings.sh, verilog/tools/kythe/BUILD, verilog/tools/kythe/kythe_facts.cc, verilog/tools/kythe/kythe_facts.h, verilog/tools/kythe/kythe_facts_extractor.cc, verilog/tools/kythe/scope_resolver.cc, verilog/tools/kythe/scope_resolver.h, verilog/tools/kythe/scope_resolver_test.cc
Use two-way inverted index instead of the scope hierarchy.
Tested:
- verification tests are passing
- did a local kythe indexing of two targets using the old and new implementation -- compared the resuting xrefs file size & counters (some counters are different, but the order of magnitude is kept)
- for perf: profiled a long running target -- the Kythe scope resolution no longer dominates the CPU time (now it's 50/50 between the output (producing protos and sinking them) & creating the facts)
=> Faster and less memory hungry Kythe scope resolution implementation.

verilog/CST/identifier.cc, verilog/CST/identifier.h, verilog/CST/identifier_test.cc, verilog/CST/port.cc, verilog/CST/port_test.cc, verilog/tools/ls/BUILD, verilog/tools/ls/autoexpand.cc, verilog/tools/ls/autoexpand.h, verilog/tools/ls/autoexpand_test.cc, verilog/tools/ls/verible-lsp-adapter.cc, verilog/tools/ls/verible-lsp-adapter.h, verilog/tools/ls/verilog-language-server.cc
Adds simple AUTO statement expansion support to the language server. This feature is modeled after [Emacs' Verilog-Mode](https://www.veripool.org/verilog-mode/) AUTO expansion. For now, it is limited to only the AUTOARG statement.
The AUTO expansion is implemented as LSP code actions. Two actions are currently available: a buffer-wide expansion, which works on the entire buffer, and a range-based one, which expands all AUTO statement within the range selected by the user.
Requires #1578.
=> Emacs Verilog-Mode AUTOARG expansion in the language server

verilog/formatting/comment_controls.cc, verilog/formatting/comment_controls_test.cc
Addresses the #1549 issue.
This PR fixes the case when `formatter::DisableFormattingRanges` started disabling range with the offset greater than text length, which happened when `//verilog_format:off` was the last line without newline character at the end.
=> Fix adding disable range starting after EOF

.github/bin/smoke-test.sh, verilog/formatting/tree_unwrapper.cc
This PR Fixes a problem where formatter is trying to cast a preprocessor's operator (in the tree a Leaf) as a Node, where it causes a check failure and a hard crash. To solve it, I have added a check whether a given child is not a leaf.
Fixes #984 
Fixes #1015
=> Fixed symbol cast check failure in tree_unwrapper

common/tools/jcxxgen.cc
Otherwise, casting a 'null' value to the final object (e.g. a string) will result in an exception. This handles it as if it was a non-set value.
=> Interpret 'null' json values as empty values in optional fields.

verilog/tools/ls/BUILD, verilog/tools/ls/verilog-language-server.cc, verilog/tools/ls/verilog-language-server.h, verilog/tools/ls/verilog-language-server_test.cc
This PR utilizes the fact that Verilog Language Server is currently wrapped in a class (https://github.com/chipsalliance/verible/pull/1560) and provides a set of GTest-based tests for the class.
Currently, a fixture is implementing initializing VerilogLanguageServer and client mocking, as well as tests previously written in shell script [verible-verilog-ls_test.sh](https://github.com/chipsalliance/verible/blob/master/verilog/tools/ls/verible-verilog-ls_test.sh)
=> [LSP] Tests for VerilogLanguageServer class

verilog/tools/ls/BUILD, verilog/tools/ls/verilog-language-server_test.cc
The coverage of the document-symbol-filler had been poor due to it being hard-to-test with the shell-script test. Now this can be tested much nicer programmatically.
While at it, replace a few ASSERT with EXPECT
=> Update DocumentSymbolRequest to cover all document filler features.

verilog/CST/verilog_matchers.h, verilog/CST/verilog_matchers_test.cc, verilog/analysis/checkers/always_comb_rule_test.cc, verilog/formatting/formatter_test.cc, verilog/parser/verilog.lex, verilog/parser/verilog.y, verilog/parser/verilog_lexer_unittest.cc
The problem with #1333 was because syntax of 
```
always @(*) begin
```
were different from:
```
always @( * ) begin
```
CST from the first case:
```
Node @0 (tag: kEventControl) {
Leaf @0 (#'@' @26-27: "@")
Leaf @1 (#'*' @27-30: "(*)")
}
```
and from the second:
```
Node @0 (tag: kEventControl) {
Leaf @0 (#'@' @26-27: "@")
Node @1 (tag: kParenGroup) {
Leaf @0 (#'(' @27-28: "(")
Leaf @1 (#'*' @29-30: "*")
Leaf @2 (#')' @31-32: ")")
}
}
```
We want such cases to always split `()` into kParenGroup. So this PR removes the syntax case of `(*)` as `*` in `attributes`. This makes the syntax of such structures good and further formatting works well.
It also adds some tests that fail on the current master but work with this PR.
Fixes #1333.
=> Simplify syntax of attributes

verilog/tools/ls/verilog-language-server_test.cc
Attempting to implicitly convert the returned json object to a string can be ambiguous.
=> Make access to string content in json explicit.

verilog/CST/verilog_matchers.h, verilog/CST/verilog_matchers_test.cc, verilog/analysis/checkers/always_comb_rule_test.cc, verilog/formatting/formatter_test.cc, verilog/parser/verilog.lex, verilog/parser/verilog.y, verilog/parser/verilog_lexer_unittest.cc
Attributes that contain parenthesis are affected. Example:
```systemverilog
(* foo="bar()" *)
module top ();
endmodule
```
=> Revert #1595 as it creates regressions.

common/util/init_command_line.cc, common/util/init_command_line.h, verilog/tools/ls/BUILD, verilog/tools/ls/verilog-language-server.cc, verilog/tools/ls/verilog-language-server.h, verilog/tools/ls/verilog_ls.cc
The language server used to just output a generic version number. Change this to contain the repository version to provide more information for issued found in the field.
=> Provide a build version and use in language server.

common/util/file_util.cc, common/util/file_util.h, common/util/file_util_test.cc
Also fix a case in which an existing absolute path would become relative if the base directory to prepend was an empty string.
=> Refine test and documentation of JoinPath().

verilog/tools/ls/document-symbol-filler.cc, verilog/tools/ls/verible-lsp-adapter.h, verilog/tools/ls/verilog-language-server_test.cc
VSCode is a larger user-base, so by default don't enable symbol mapping from the document outline to match Kate.
However, to look good in vscode, another hack was needed: the icon for 'module' looks like a generic namespace icon, which is already pretty common with labelled blocks. So instead, emit a symbol whose representation looks 'nicer' in vscode.
TODO: at some point, add some editor-specific mappings that then attempt to map correctly from the initailzation string sent to the language server.
=> Don't use Kate symbol mapping by default. Choose a mapping for VSCode.

verilog/analysis/verilog_filelist.cc, verilog/analysis/verilog_filelist.h, verilog/analysis/verilog_filelist_test.cc, verilog/tools/project/project_tool.cc
This just adds confusion as it is unclear if files are relative to that path, but it does not do any of that function.
=> Remove file_list_path in filelist struct as it is not used.

common/util/file_util.cc, common/util/file_util.h, common/util/file_util_test.cc, verilog/tools/project/project_tool_test.sh
The behavior of JoinPath() used to be that paths are just concatenated inddpendent if the path in question is already absolute.
JoinPath("foo/", "bar") -> "foo/bar"  OK
JoinPath("foo", "/bar") -> "foo/bar"  questionable
This looks like it is a left-over from keeping the behavior the same from the simplistic old implementation that just concatenated strings. (https://github.com/chipsalliance/verible/commit/495dda72923d1a13422a6f3a3fd131ed3b1fff37)
However, this results in unexpected behavior. The new behavior is to keep absolute paths as-is.
JoinPath("foo", "/bar") -> "/bar"  EXPECTED
Add a test on project tool test that illustrates the problem that is solved.
=> JoinPath(): if path is already absolute, don't prepend anything.

common/text/BUILD, common/text/tree_context_visitor.cc, common/text/tree_context_visitor.h
So that they are not accidentally interpreted as importing a std:: namespace object.
While at it: remove an unused dependency.
=> Import base class constructor: document rare use of using statement.

common/lsp/lsp-protocol.yaml, common/strings/BUILD, verilog/analysis/symbol_table.cc, verilog/analysis/verilog_project.cc, verilog/analysis/verilog_project.h, verilog/tools/ls/BUILD, verilog/tools/ls/lsp-parse-buffer.cc, verilog/tools/ls/lsp-parse-buffer.h, verilog/tools/ls/symbol-table-handler.cc, verilog/tools/ls/symbol-table-handler.h, verilog/tools/ls/symbol-table-handler_test.cc, verilog/tools/ls/verilog-language-server.cc, verilog/tools/ls/verilog-language-server.h, verilog/tools/ls/verilog-language-server_test.cc
This PR is Work in Progress.
It adds support for creating a [SymbolTable](https://github.com/chipsalliance/verible/blob/master/verilog/analysis/symbol_table.cc) in the [Language Server](https://github.com/chipsalliance/verible/blob/master/verilog/tools/ls/verilog_ls.cc) and utilizing it for finding definitions.
The current status is:
Currently, the workspace directory provided by the editor is used as VerilogProject root (however, emacs uses git repository root directory as the workspace directory, if available).
=> [LSP] Add support for providing definitions from the SymbolTable

verilog/tools/ls/README.md, verilog/tools/ls/vscode/README.md, verilog/tools/ls/vscode/package.json
This README actually shows up in the plugin page in VSCode, so make it more useful by describing the available features and where to file bugs.
The original install description, move one directory up to the general page describing installation for various editors.
Change version number to 0.0.2700 as we soon hit 2700 commits after the go-to-definition change is pushed.
=> Make the README in the vscode/ directory more useful.

shell.nix, verilog/tools/ls/README.md
The verible.vsix VSCode extension is now build in the CI, so we can also offer it to be downloaded.
While at it: update developer dependencies to include nodejs to build it.
=> Document downloadability of vsix extension.

common/text/BUILD, common/text/concrete_syntax_tree.h, common/text/symbol.h, common/text/symbol_ptr.h, common/text/text_structure.h, common/text/visitors.h, verilog/CST/verilog_tree_json_test.cc, verilog/CST/verilog_tree_print_test.cc, verilog/formatting/tree_unwrapper.cc
This was mostly already happening, however a few places explicitly mentioned std::unique_ptr<Symbol> 'manually'.
=> Cleanup: Define SymbolPtr only in one place.

.github/bin/build-and-test.sh, .github/workflows/verible-ci.yml, common/text/concrete_syntax_tree.h, verilog/analysis/checkers/always_comb_blocking_rule.cc, verilog/analysis/lint_rule_registry_test.cc
There were two instances of using dynamic_cast<> that could already be implemented with calling Symbol::Kind().
Add a test that compiles without RTTI, so that it is discovered automatically when a dynamic_cast is added.
For now, keeping the binaries as-is compiled with RTTI, but they would be about 100kiB smaller without.
Leaving it for another day to check if the performance improved marginally.
=> Keep the code clean from using RTTI

verilog/tools/ls/symbol-table-handler.cc, verilog/tools/ls/verilog-language-server_test.cc
Fixes https://github.com/chipsalliance/verible/issues/1647
This PR adds a fix for the `textDocument/definition` request - when we work on currently edited file, we don't need a `verible.filelist` file to perform go-to definition jump.
Here we remove quitting `FindDefinition` function when `FileList` is not available - it will collect symbols from currently opened buffers.
=> Issue #1647 Handling `textDocument/definition` request without FileList

bazel/build-version.py
If git is not available and the GIT_DATE and GIT_VERSION environment variables are not set, fall back to a
generic string.
Fixes #1658
=> Provide a fallback git date and version.

common/util/BUILD, common/util/thread_pool.cc, common/util/thread_pool.h, common/util/thread_pool_test.cc
This is in preparation to using it for processing files in parallel, initially for large file-lists to symbolize in the language server.
=> Provide a simple platform-independent thread_pool.

common/text/text_structure.cc, verilog/analysis/verilog_analyzer_test.cc, verilog/formatting/formatter_test.cc
Fixes a syntax tree problem when processing a single `verilog_syntax` directive returning `syntax_tree_` as `nullptr`.
Fixes #1552
=> Fix a syntax tree problem when processing a single `verilog_syntax` directive

verilog/tools/ls/symbol-table-handler.h
No functional change.
Having a newline between members improves readability.
=> Readability improvement: Put methods first; separate fields.

common/parser/move_yacc_stack_symbols.sh, common/parser/record_syntax_error.sh
These are scripts critical for the build, so keep the system requirements as barebones as possible.
Issues #1669
=> If no bash is needed, simplify to use /bin/sh

WORKSPACE, bazel/installer.patch
This option is not compatible with the `install` found on MacOS.
Issues #1404
=> Patch installer to not use unnecessary option -T on install binary

verilog/analysis/symbol_table.cc, verilog/analysis/symbol_table_test.cc, verilog/tools/ls/verilog-language-server_test.cc
Fixes #1654 
SymbolTable during build has a pointer to currently processed source and string view to symbol.
When symbol is redefined in another file, the source pointer is no longer valid and resolving the location of the previous symbol in the current file was resulting in assertion error.
This commit uses the file_origin from SymbolTableNode for previous symbol to provide symbol location.
The current behaviour is that we keep the first observed definition of the symbol, while returning error in diagnostics for other redefinitions.
=> Fixed diagnostics for already existing symbol

verilog/tools/ls/verible-lsp-adapter.cc, verilog/tools/ls/verilog-language-server_test.cc
In case the text did not end with a newline, the end-position of text to replace in the formatting response did not include the remaining characters of the last line.
Fixes: #1667
=> formatting: reply to language server client full original text range.

common/lsp/lsp-protocol-enums.h, common/lsp/lsp-protocol.yaml, verilog/tools/ls/BUILD, verilog/tools/ls/verible-lsp-adapter.cc
Adds support for diagnostic severity in the language server.
Before:
After:
Signed-off-by: Krzysztof Bieganski <kbieganski@antmicro.com>
=> Add severity to language server's diagnostics

verilog/tools/ls/vscode/package.json, verilog/tools/ls/vscode/src/extension.ts
This PR changes how SystemVerilog capability is being communicated to VSCode, from `system-verilog` to just `systemverilog` - it is the default way, otherwise it produces conflicts with other packages and does not load the plugin alongside them.
Fixes #1666
=> Changed VSCode plugin language capabilities

verilog/analysis/verilog_project.cc, verilog/analysis/verilog_project.h
This is to avoid confusion with absl::Status, as
state and status are close, linguistically.
=> Rename VerilogSourceFile::State to ProcessingState

verilog/analysis/symbol_table.cc, verilog/analysis/verilog_linter.cc
Move the VLOG()-level requirements up one notch.
This makes it easier to see relevant logging if symbol table is used as a library.
Also, similar in verilog linter.
=> Reduce logging noise in symbol table.

verilog/analysis/verilog_project.cc, verilog/analysis/verilog_project.h, verilog/tools/ls/symbol-table-handler.cc, verilog/tools/ls/symbol-table-handler.h
For projects with many files, this filled the logs with all kinds of LOG(WARNING) that are not really relevant unless debugging. So moved all these to VLOG(1). Keep aggregate logs ("3000 files took 20 seconds to process") as LOG(INFO).
While at it:
* Don't call BuildSymbolTable() while in LoadProjectFileList().
It is confusing as it doesn't do anything, because it requires
the file to be analyzed first. So just do what is needed to
open the files into memory.
* Remove methods only needed internally to the private section
oof SymbolTableHandler header. Also remove unused method.
* Separate out parsing from symbol table building to log timing independently.
These changes are improving timing information needed to make relevant implementation decisions in #1682.
=> Reduce logging noise: Only aggregate to LOG(INFO), file-level VLOG(1).

.github/bin/build-and-test.sh, .github/workflows/verible-ci.yml
While we only require c++17, make sure that we don't accidentally use future-deprecated features.
=> Test also with c++23

.github/workflows/verible-ci.yml
... after container image update, the cached paths don't fit anymore (seen in the clang compile).
=> CI: Flush bazel caches

WORKSPACE
I've fixed and upstreamed this in
https://github.com/protocolbuffers/protobuf/commit/f58d0b56e37aa6a85848618018d7a17b86746bc0
... now picking up that change.
Without that, newer gcc's would complain about a
maybe uninitialized value, failing the compile if that warning was enabled to -Werror.
=> Update to latest protobuf that fixes a warning.

.github/workflows/verible-ci.yml
This was briefly broken after changing the virtual machine image; possibly due to caching old paths.
=> Re-enable asan-clang compile.

.github/bin/error-log-analyzer.py, .github/bin/smoke-test.sh
The very small syntax tests in sv-tests make it
particularly suited to find specific issues.
=> Add sv-tests to smoke tests.

.github/bin/build-and-test.sh
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105329
Is triggering issues in single-char string assignments to strings:
here:
https://github.com/chipsalliance/verible/blob/c730042f4a0ac27e7d936baaf801df225d9352cc/verilog/tools/ls/verilog-language-server.cc#L190
and here:
https://github.com/protocolbuffers/protobuf/blob/9c2211be08af10dd5964cf8b65364afaef001fdf/src/google/protobuf/io/tokenizer.cc#L588
This is a spurious warning in gcc 12.2, with c++20 and optimizations enabled and is safe to ignore. So just document why we enable -Wno-restrict.
=> Document the gcc bug that genreates a spurious warning.

shell.nix
Also, remove not spcifically needed dependencies (e.g. gcc is already in the stdenv).
=> Group dependencies according to use.

verilog/tools/ls/autoexpand_test.cc
Starting with c++20, there is a new constructor #5 for string_view in town:
https://en.cppreference.com/w/cpp/string/basic_string_view/basic_string_view
Together with concepts the initailization with {} can be ambiguous for either a std::vector<std::string_view> or a std::string_view{} initialization with two parameters that conceptually allow iterating.
Both functions would match, in the latter case the last string would be interpreted as the optional boolean ...
Unfortunately, I could not reproduce this in the CI (#1706 was for that), I suspect this only shows up with libstdc++ (which we're not using in the CI).
Long story short: dismbiguiated it by renaming the functions. An alternative would be to just remove one of the functions.
=> Work around an overload that becomes ambiguous with C++20

verilog/analysis/BUILD, verilog/analysis/symbol_table.cc, verilog/tools/ls/BUILD, verilog/tools/ls/lsp-parse-buffer.cc, verilog/tools/ls/symbol-table-handler.cc, verilog/tools/ls/verilog-language-server.cc
Make it easier to see what tests are running and help concentrate on important messages.
bazel test --test_output=streamed  //verilog/tools/ls/...
=> Reduce log chatter.

.clang-tidy, .github/bin/run-clang-tidy.sh, .github/workflows/verible-ci.yml, common/strings/mem_block.h, common/util/file_util.cc, common/util/simple_zip.cc, common/util/thread_pool.h, verilog/analysis/symbol_table.h, verilog/tools/ls/autoexpand.cc, verilog/tools/ls/verilog-language-server.h
* TIL that a #-comment in the .clang-tidy configuration silently messes up the config, resulting in ignored rules.
* Remove the comment in our clang tidy config. It has been there since 065904fa4ac24858a96fbf055d595ee5ac34c879
* Harden the run-clang-tidy.sh script to make sure such comments are not added.
* Fix the fall-out of not having complete clang-tidy rules active for a few months.
=> Fix broken clang-tidy config; fix new warnings showing up.

.github/settings.sh, .github/workflows/verible-ci.yml
Since the logs are no shell, the progress information does not happen 'in place' like in the terminal, but just fills the logs with clutter that might hide real information.
=> Don't clutter the CI logs with progress lines.

common/formatting/align_test.cc, common/formatting/layout_optimizer.cc, common/text/parser_verifier.cc, verilog/parser/verilog_lexer.cc, verilog/transform/obfuscate.cc, verilog/transform/strip_comments.cc
I prefer for (;;) over while (true). The latter slows down reading as the reader has to parse the condition.
=> Simplify endless loops.

.github/workflows/verible-ci.yml
In order to avoid clashing with other, incompatible custom runners, we have updated our GCP runners to have more specific labels. Thus, we also need to reflect this change in the workflow YAML.
=> ci: update custom runners labels

.clang-tidy, common/text/constants.h, verilog/analysis/default_rules.h, verilog/analysis/verilog_linter_constants.h
That way, we don't use up multiple storage if not needed.
=> Convert the remaining static constexpr -> inline constexpr in headers.

.clang-tidy, .github/bin/run-clang-tidy.sh
If the configuration is not provided in the command line, clang-tidy will attempt to search for every *.cc file it checks to go up the directory chain to look for .clang-tidy. That of course might fail if this is a generated file that lives in a symbolic-linked bazel-out/ of sorts.
clang-tidy versions 12 and up have a convenient --config-file option, but clang-tidy 11 only knows --config, so we use that.
=> Don't search for .clang-tidy, provide it directly in command line.

common/analysis/linter_test_utils.h, common/analysis/syntax_tree_search_test_utils.cc, common/formatting/align_test.cc, common/formatting/token_partition_tree_test_utils.h, common/lsp/message-stream-splitter_test.cc, common/strings/diff_test.cc, common/strings/display_utils_test.cc, common/strings/patch_test.cc, common/strings/range_test.cc, common/strings/string_memory_map_test.cc, common/util/auto_pop_stack_test.cc, common/util/interval_map_test.cc, common/util/interval_set_test.cc, common/util/map_tree_test.cc, common/util/range_test.cc, common/util/tree_operations_test.cc, common/util/vector_tree_test.cc, common/util/vector_tree_test_util.cc, verilog/analysis/symbol_table_test.cc, verilog/analysis/verilog_project_test.cc, verilog/formatting/tree_unwrapper_test.cc, verilog/preprocessor/verilog_preprocess_test.cc
Auto fix application of redundant-string-init, google-explicit-constructor, and modernize-use-using.
We currently don't have compilation db support for tests, this is why they are not clang-tidy clean yet.
(Currently experimenting with a different implementation of compilation database locally, which made this possible)
=> Some clang-tidy auto-fixes for tests.

common/util/simple_zip.cc
This way we emphasize that this is a local header and that the system <zlib.h> shall not be considered.
=> Given that zlib.h is imported in WORKSPACE, it is a project header.

.github/bin/make-compilation-db.sh, .github/bin/run-clang-tidy.sh, .github/workflows/verible-ci.yml, BUILD, WORKSPACE
Creating the compilation DB from within bazel has
its issues, e.g. we can't include the test targets.
In the project for creating a compilation database for baze l(https://github.com/grailbio/bazel-compilation-database), there is also an alternative way: a script that can be used to create a compilation DB for all targets by invoking bazel
with some aspects enabled.
Let's use that instead: with that, we get all targets, including test targets into the compilation database.
To avoid having to download the script manually, hash-sum check  and set up some temporary place on the users' workstation to host the script and the files it needs, we let bazel download it in the WORKSPACE file and then call into it.
While this assumes a certain layout of the bazel directory structure, this does seem …
=> Invoke grail compilation db script directly.

common/formatting/state_node_test.cc, common/strings/obfuscator_test.cc, common/util/file_util_test.cc, common/util/map_tree_test.cc, common/util/tree_operations_test.cc, common/util/user_interaction_test.cc, common/util/vector_tree_test.cc, verilog/tools/ls/verilog-language-server_test.cc
Either fixing it with (don't copy a value) or acknowledging it as explicitly wanted (when testing deep copies).
=> Address a few clang-tidy concerns.

.github/bin/run-clang-tidy.sh
The caller can supply additional clang-tidy flags that are passed as-is.
Example:
.github/bin/run-clang-tidy.sh --checks="-*,modernize-use-equals-default" --fix
=> Allow to supply additional options to the clang-tidy script.

common/analysis/line_linter_test.cc, common/analysis/line_linter_test_utils.h, common/analysis/matcher/matcher_test.cc, common/analysis/syntax_tree_linter_test_utils.h, common/analysis/text_structure_linter_test.cc, common/analysis/text_structure_linter_test_utils.h, common/analysis/token_stream_linter_test_utils.h, common/formatting/align_test.cc, common/formatting/layout_optimizer_test.cc, common/lexer/lexer_test_util.h, common/strings/diff_test.cc, common/strings/rebase_test.cc, common/text/token_info_test.cc, common/text/token_stream_view_test.cc, common/util/container_proxy_test.cc, common/util/tree_operations_test.cc, external_libs/editscript_test.cc, verilog/CST/verilog_matchers_test.cc, verilog/analysis/checkers/module_filename_rule_test.cc, verilog/analysis/checkers/package_filename_rule_test.cc, verilog/analysis/checkers/uvm_macro_semicolon_rule_test.cc, verilog/analysis/verilog_linter_configuration_test.cc, verilog/analysis/verilog_linter_test.cc, verilog/formatting/formatter_test.cc, verilog/formatting/token_annotator_test.cc, verilog/formatting/tree_unwrapper_test.cc, verilog/parser/verilog_lexical_context_test.cc, verilog/parser/verilog_parser_unittest.cc
Result of
```
.github/bin/run-clang-tidy.sh --checks="-*,modernize-use-equals-default,readability-redundant-string-init,google-readability-braces-around-statements,readability-redundant-member-init,readability-else-after-return" --fix
```
=> Apply some automated clang fixes on tests.

.clang-tidy, common/analysis/matcher/matcher_test_utils.cc, common/formatting/align_test.cc, common/lexer/lexer_test_util.h, common/strings/patch_test.cc, common/strings/split_test.cc, common/text/text_structure_test.cc, common/util/algorithm_test.cc, common/util/auto_iterator_test.cc, common/util/enum_flags_test.cc, common/util/file_util_test.cc, common/util/thread_pool_test.cc, common/util/type_traits_test.cc, verilog/CST/DPI_test.cc, verilog/CST/declaration_test.cc, verilog/CST/dimensions_test.cc, verilog/CST/expression_test.cc, verilog/CST/functions_test.cc, verilog/CST/identifier_test.cc, verilog/CST/macro_test.cc, verilog/CST/type_test.cc, verilog/analysis/checkers/numeric_format_string_style_rule_test.cc, verilog/analysis/lint_rule_registry_test.cc, verilog/analysis/symbol_table_test.cc, verilog/analysis/verilog_equivalence_test.cc, verilog/analysis/verilog_linter_test.cc
Mostly
```
.github/bin/run-clang-tidy.sh --checks="-*,performance-inefficient-vector-operation,modernize-use-emplace,performance-unnecessary-value-param,readability-else-after-return,performance-move-const-arg" --fix
```
... but also a few manual changes.
=> Some mechanical code-quality fixes.

.clang-tidy
This is emitted when there are c-strings concatenated in sequence, an often occurence in test file. The warning wants to point out that there are somtimes commas to separate.
Might be useful to address (and some already are), but given that all these instances are in tests, this is somewhat lower prio.
=> Exclude 'suspicious comma' clang-tidy warning.

.github/bin/make-compilation-db.sh
There is only a need to call bazel fetch on a fresh workspace, so only do it if the compilation database script is not there yet.
=> compile-db generation: only fetch workspace if needed.

verilog/tools/kythe/kythe_schema_constants.h
Thus the compiler won't be bothered that there is a unused constant variable.
=> Make constexpr in headers inline.

.github/bin/run-clang-tidy.sh, .github/workflows/verible-ci.yml, shell.nix
Thus not needing the specialized gnu awk.
=> clang-tidy script: Reformulate file exclusion processing using sed.

common/formatting/align.cc, common/formatting/align_test.cc, common/formatting/layout_optimizer_test.cc, common/formatting/token_partition_tree_test.cc, common/text/tree_context_visitor_test.cc, shell.nix, verilog/formatting/align.cc, verilog/preprocessor/verilog_preprocess.cc, verilog/tools/kythe/kythe_facts_extractor.cc, verilog/tools/kythe/scope_resolver_test.cc
Detected by clang-tidy-15.
The std::optional test (bugprone-unchecked-optional-access) found one real issue, but also some false-positives (that are easily worked around) in unit tests.
=> No temporary objects for emplace back. Test std::optional before use.

.github/bin/run-clang-tidy.sh, .github/workflows/verible-ci.yml, shell.nix
Name the directory based on the active configuration, so that
it is possible to play with multiple configurations without
loosing cached information. In particular this means that files with
issues don't have to be reprocessed unless changed; the corresponding
cached clang-tidy output is just re-used.
For each cc-file, store the output of clang-tidy content-addressed,
so that a minimum of reprocessing is needed: if a file with a
particular content has been processed with a particular clang-tidy,
that content is cached and retrieved quickly.
Make sure that cc files are reprocessed if any of their headers
change.
Not only does this improve performance for unchanged files, the
implementation is also much simpler as we now use named files
instead of working with lines in a cache file.
Provide …
=> clang-tidy: content-addressable results in config-dependent dir

common/analysis/line_linter_test.cc
In C++20, a new constructor for std::string_view (of which absl::string_view is an alias in most cases starting in C++17), causes a double-braced pair of string literals in this context to be treated as a std::vector of a single string_view which is constructed from both literals.
This new constructor is intended to take a pair of begin and end iterators, but can also accept two string literals (since they are iterators of char, after all). In that case, a string_view over all of the intervening memory is returned. That is not the intention here.
=> Fix c++20 string_view constructor ambiguity.

.github/bin/run-clang-format.sh
The 'grep' did not actually recognize the |-or operator in the regular expression, so never actually worked for the intended purpose. Fix that here.
=> Use egrep to properly exclude directories not to be formatted.

verilog/analysis/verilog_linter.h, verilog/tools/ls/BUILD, verilog/tools/ls/lsp-file-utils.cc, verilog/tools/ls/lsp-file-utils.h, verilog/tools/ls/lsp-parse-buffer.cc, verilog/tools/ls/symbol-table-handler.cc, verilog/tools/ls/symbol-table-handler.h, verilog/tools/ls/verilog-language-server.cc, verilog/tools/ls/verilog-language-server_test.cc
This PR:
* Moves conversions of LSP URI to paths and vice versa to a separate library
* Enables checking `.rules.verible_lint` by default
* Adds mechanism in parsed buffers to check for `.rules.verible_lint` up in directory hierarchy, starting from linted file, to load linter rules
* Adds tests for verifying reactions of `VerilogLanguageServer` for `.rules.verible_lint` file
@hzeller - I am not sure about changing the default value of the `--rules-config-search` to `true`. This flag is available from the level of `verible-verilog-ls` - not sure whether I should change the flag value to `true` via `SetFlag` in a function delivered with `VerilogLanguageServer`, or change this default value directly in `verilog_linter`.
=> Add loading linter rules from .rules.verible_lint

common/formatting/align.h, common/formatting/align_test.cc, common/formatting/format_token.cc, common/formatting/format_token.h, common/formatting/format_token_test.cc, common/formatting/layout_optimizer_internal.h, common/formatting/layout_optimizer_test.cc, common/formatting/line_wrap_searcher.cc, common/formatting/line_wrap_searcher_test.cc, common/formatting/state_node.cc, common/formatting/state_node.h, common/formatting/state_node_test.cc, common/formatting/token_partition_tree.cc, common/formatting/token_partition_tree_test.cc, common/formatting/unwrapped_line.cc, common/formatting/unwrapped_line_test.cc, verilog/formatting/formatter.cc, verilog/formatting/token_annotator.cc, verilog/formatting/token_annotator_test.cc, verilog/formatting/tree_unwrapper.cc
Just applying the
https://google.github.io/styleguide/cppguide.html#Enumerator_Names
rule.
=> Fix constant prefix for enums SpacingOptions, GroupBalancing, SpacingDecision

.clang-tidy, .github/bin/run-clang-tidy-cached.cc
This is an interesting read: https://abseil.io/tips/112 TL;DR: yes, using emplace_back() can improve performance, but there can also be surprising effects. So using it might depend on the context, but it is not necessarily a 'should always' suggestion (but if we have them in the .clang-tidy, the CI will fail).
While at it, expand the set of directories that should be excluded as they don't contain the main project code.
=> Don't suggest to use emplace_back() all the time.

verilog/tools/ls/symbol-table-handler.cc, verilog/tools/ls/verilog-language-server.cc, verilog/tools/ls/verilog-language-server.h
If the file list is not found we should show it in the default logs (VERIBLE_LOGTHRESHOLD=0), not only the verbose logs. This makes it easier to discover if there are issues (e.g. #1786).
Also remove one default parameter - things are easier to see when explicitly called.
Now looking at the verilog-language-server_test, and autoexpand_test it is clear that each of them do some search for a file-list. In tests, unless we explicitly test for the searching capability, we always should specify these and not allow auto-searching. So maybe some infrastructure needed there to provide that at construction time (even if it is only used in tests). Left for a later change.
=> Make it more visible if the file list is not found.

verilog/tools/ls/autoexpand.cc, verilog/tools/ls/autoexpand_test.cc, verilog/tools/ls/lsp-parse-buffer.h, verilog/tools/ls/symbol-table-handler.cc, verilog/tools/ls/verible-lsp-adapter.cc
Handing out the shared_ptr<> of the current()/last_good() buffer will make sure that ongoing operations will have a valid copy even if it is replaced asynchronously.
Just API update, no actual asynchronous operations happening yet.
While at it: add documentation to the function calls as well as thread guarantees.
=> Prepare code to be ready for asynchronous buffer updates.

common/text/concrete_syntax_tree.cc, common/text/tree_utils.cc
This PR contains two fixes:
1. Before this change, checking for equality of `SyntaxTreeNode`s did not take into
account the node tag. This meant two trees with different tags inside would be
considered equal. This patch simply adds a check for the node tag to the
equality function.
2. `TreeVisitorRecursive` visits an entire tree, traversing it in pre-order. In
contrast, `SymbolVisitor` only visits a single `Symbol` and needs to manually be
applied for subtrees. This is what already happens in `FirstSubtreeFinder` with
the intention that if it finds the first match, it can return early. However,
`FirstSubtreeFinder` inherits from `TreeVisitorRecursive`, which means it
traverses the entire tree anyway, and the manual applications within it only
create additional, unnecessary work. This …
=> Fix syntax tree equality checking and `FirstSubtreeFinder`'s base class

common/tools/BUILD, common/tools/jcxxgen.cc
std::regex is not optimized for performance and can be quite slow on different platforms.
While it does not matter in this particular tool, this is to test it in a small context so that we then can apply it in other places where performance matters.
=> Start using RE2 instad of std:;regex

common/text/tree_utils.cc, common/text/tree_utils.h, common/text/tree_utils_test.cc, verilog/tools/ls/autoexpand.cc, verilog/tools/ls/autoexpand_test.cc
This patch addresses situations where AUTOs are expanded in incorrect contexts, such as expanding `AUTOINST` under a port actual, instead of directly in module instantiation parens.
The syntax tree is traversed until the deepest node that encompasses a given AUTO expansion is found. If the node kind is expected for the expansion, it can be applied. Otherwise, the expansion is discarded. For example, `AUTOINST` expansion can only be done directly under module instantiation, but not any deeper in the tree, e.g. in a port actual.
=> Prevent expansion of misplaced AUTOs

common/analysis/matcher/BUILD, common/analysis/matcher/matcher_test_utils.cc, common/text/tree_utils.cc, common/text/tree_utils.h, common/text/tree_utils_test.cc
This aids debugging while working on such matchers.
To make it visually more obvious of 'holes' in the children list, add an option to RawTreePrinter to include null-children.
=> Matcher tests: print the corresponding symbol tree on failure.

common/util/file_util.cc, common/util/file_util_test.cc, verilog/tools/formatter/verilog_format.cc, verilog/tools/syntax/verilog_syntax.cc
The status messages due to opening files might be created deeply in the code, so it is good if issues with files percolate up with the filename included.
=> File opening status messages: always include filename.

common/util/file_util.cc, common/util/file_util.h, common/util/file_util_test.cc
When we started, we did not have StatusOr<> available, but it makes a lot of sense for file::GetContents() similar to the newer GetContentAsMemBlock().
Provide a new function, similar to it sibling
GetContentAsMemBlock()
absl::StatusOr<std::string> GetContentAsString();
Provide an adapter function that behaves just as the old file::GetContents(). To be replaced in subsequent change(s) until finally removed.
=> Revise an old filesystem function to return StatusOr<>

verilog/tools/ls/autoexpand.cc, verilog/tools/ls/autoexpand_test.cc
This handles the case where all AUTO expanded ports of a particular type (e.g. `inout` ports) are removed. Previously the corresponding AUTO would be unaffected; now it's being reduced to just the AUTO comment.
This patch also adds a test that verifies this behavior.
=> Remove AUTO expanded ports if they no longer exist

.github/workflows/verible-ci.yml
A clang-tidy report is more helpful if actionable :)
=> CI: Output the details for a clang-tidy run if necessary.

WORKSPACE, bazel/fix-uninitialized-var.patch
Will open an issue upstream, but for now, this fixes the clang-analyzer-optin.cplusplus.UninitializedObject we see.
=> Work around uninitialized value in absl call_once.

common/analysis/lint_waiver.cc, common/strings/BUILD, common/strings/mem_block.h, common/strings/patch.cc, common/strings/patch.h, common/strings/patch_test.cc, common/tools/patch_tool.cc, common/util/file_util.cc, common/util/file_util.h, common/util/file_util_test.cc, verilog/analysis/verilog_filelist.cc, verilog/analysis/verilog_linter.cc, verilog/analysis/verilog_linter_configuration.cc, verilog/analysis/verilog_linter_test.cc, verilog/tools/diff/verilog_diff.cc, verilog/tools/formatter/verilog_format.cc, verilog/tools/kythe/verilog_kythe_kzip_writer.cc, verilog/tools/obfuscator/verilog_obfuscate.cc, verilog/tools/preprocessor/verilog_preprocessor.cc
... including the necessary changes from return value of absl::Status to absl::StatusOr<std::string>.
Remove old file::GetContents() function.
=> Replace calls to GetContents() with GetContentAsString()

verilog/tools/ls/BUILD, verilog/tools/ls/autoexpand.cc
* Replaces all usage of `std::regex` with `RE2` in AUTO expansion code,
* Simplifies some of the code that used to pass `std::cmatch`es around.
Closes #1794.
=> Use `RE2` instead of `std::regex` in AUTO expansion

verilog/tools/ls/vscode/README.md
The README is displayed insided the vscode plug-in page, as well as on the [marketplace page](https://marketplace.visualstudio.com/items?itemName=CHIPSAlliance.verible)
Since we don't bundle a binary with the plug-in yet, this guides new users better how to set-up things.
=> Clarify where to get the binaries in VSCode plug-in readme.

BUILD, common/formatting/BUILD, common/util/BUILD, verilog/formatting/BUILD, verilog/tools/formatter/BUILD, verilog/tools/formatter/verilog_format.cc
Some were public, but didn't need to be.
The only public items are the final binaries.
=> Be more specific about library visibilities.

.github/bin/error-log-analyzer.py, .github/workflows/verible-ci.yml
Added a last-resort method to detect include statements containing the filename of the tested file, such that if it was included, the syntax errors would be attributed to the file being taken out of context. This change was made during the preparation for #1839.
=> Ripgrep based output analysis in smoke-test-analyzer

common/util/file_util.cc, common/util/file_util.h, common/util/file_util_test.cc, verilog/analysis/checkers/module_filename_rule.cc, verilog/analysis/checkers/package_filename_rule.cc, verilog/tools/lint/lint_tool_test.sh
Fixes https://github.com/chipsalliance/verible/issues/1359. Went ahead and fixed the package_filename_rule too. 
As I'm not familiar with the tool, I don't know if every time we consume stdin input the filename is always "-", or if we should have an array of possible stdin filenames to match against. For example: 
```c++
static const char *STDIN_FILENAMES[NUM_STDIM_NAMES] = {
"-",
"stdin",
"something something"
};
```
I'm not sure if adding tests for this would be an easy task, but I suspect it isn't.
=> Avoid performing filename lint rules for stdin

common/formatting/align.cc, verilog/analysis/checkers/line_length_rule.cc, verilog/analysis/verilog_analyzer.cc, verilog/formatting/align.cc, verilog/formatting/token_annotator.cc
Observing the language server output with
VERIBLE_VLOG_DETAIL=1 showed some too detailed logging in places.
For macro expansion parsing: include original filename when logging issues.
=> Adapt verbosity of some logging for improved usefulness.

.bazelrc
Looks like bazel is not supplying that by default.
Issues #1856
=> Add -lm link options explicitly for BSD

common/text/text_structure.cc, common/text/text_structure.h
Given that we're dealing with memory addresses, this is likely some int64 type.
=> Fix an assumption that std::distance is a simple int.

verilog/analysis/checkers/line_length_rule.cc
Making sure to not wander outside of range. Discovered by fuzzing.
b/269962677
=> line-length-rule: Be more robust in walking token iterators.

.bazelrc, .github/bin/build-and-test.sh, .github/bin/generate-matrix.py, .github/bin/github-releases-setup.sh, .github/workflows/verible-ci.yml, README.md, bazel/BUILD, bazel/variables.bzl, common/tools/BUILD, releasing/centos/common/compiler.dockerstage, releasing/docker-run.sh, verilog/tools/diff/BUILD, verilog/tools/formatter/BUILD, verilog/tools/kythe/BUILD, verilog/tools/lint/BUILD, verilog/tools/ls/BUILD, verilog/tools/obfuscator/BUILD, verilog/tools/preprocessor/BUILD, verilog/tools/project/BUILD, verilog/tools/syntax/BUILD
This PR adds `--//bazel:create_portable_executables` flag, which allows to generate portable binaries. It can be useful for e.g. creating VS Code extension where only generated binaries will be needed -- without additional shared libraries.
This flag can be used with `build` command, e.g.:
```
bazel build -c opt --//bazel:create_portable_executables //...
```
=> Adding flag for portable build of Verible binaries

verilog/CST/expression.cc, verilog/CST/expression.h, verilog/CST/expression_test.cc, verilog/analysis/checkers/BUILD, verilog/analysis/checkers/forbid_negative_array_dim.cc, verilog/analysis/checkers/forbid_negative_array_dim.h, verilog/analysis/checkers/forbid_negative_array_dim_test.cc
Attempt to fix https://github.com/chipsalliance/verible/issues/382. I'm sure the code could use some improvements, so happy to accomodate any feedback!
Edit:
Sorry for the several updates, after making the pull request I realized that there are some corner cases (parenthesis, ...) so I tried to fix some of those. It still won't pick up things like +(-5) but I can't see an easy way to fix that.
=> Add new lint rule for negative array dimensions

.github/workflows/verible-ci.yml
Also restores condition in `Build` stage.
This is a followup to #1842
=> Change name of jobs building statically linked executables

README.md
The pre-packaged versions of Verible are a bit unknown, so link to them in the README.
=> Link to homebrew and Nix packages of Verible.

common/analysis/violation_handler.cc, common/strings/patch.cc, common/tools/patch_tool.cc, common/util/user_interaction.cc, common/util/user_interaction.h
Not only stdin is queried, but also if the output stream we attempt to write to is also a terminal (as this is used to determine if we use terminal code to output bold or inverse text).
=> Refine interactive terminal session detecation.

common/strings/patch.cc, common/strings/patch.h, common/util/user_interaction.cc, common/util/user_interaction.h
Hello, as the issue seemed stale I took the liberty of making a pull request, hope that's ok.
This would be my preferred approach to add coloring to the terminal output, but let me know if you think other solution is better.
Once we agree on how to add the colors, I'd be happy to make it configurable (ON/OFF, Different color palletes) if you want.
Current output:
* the typo in '---' NEW instead of '+++' has already been corrected
The issue says "Possibly detect terminal type as well". Could you ellaborate on what that means?
TODO:
=> Color the diffs/hunks presented to the user #526

.clang-format, .github/bin/run-clang-format.sh
This changes the .clang-format to not derive the pointer alignment from the prevalence in the file, but always make sure the formatting matches C/C++ semantic (right-aligned).
The files in the code-base used different styles mostly based on who edited the files first.
The CI clang-format will not enforce it at this point, just whenever files are edited and cared to be formatted locally, they get the intended formatting.
=> Nudge pointer alignment towards C/C++ semantic.

verilog/formatting/formatter_test.cc, verilog/parser/verilog.y
This PR implements support for macro calls in the struct body. The syntax allows the flexibility to use or skip the semicolon.
Fixes #1873
=> Added support for macro calls inside struct bodies

verilog/tools/ls/BUILD, verilog/tools/ls/document-symbol-filler.cc, verilog/tools/ls/lsp-conversion.h, verilog/tools/ls/symbol-table-handler.cc
We use the same conversion in multiple places, so let's give it a name and put in a header.
=> Move function to convert verible source range to lsp::Range in header.

verilog/formatting/formatter_test.cc, verilog/formatting/token_annotator.cc, verilog/formatting/token_annotator_test.cc
This PR adds a rule check for `compact_indexing_and_selections` in the streaming concatenation token annotation.
Fixes #1851
=> Make streaming concatenation rules check the style for compacting indexes

verilog/tools/ls/verible-lsp-adapter.cc
Fixes https://github.com/chipsalliance/verible/issues/1843. 
The comments on current() seemed a bit confusing to me when investigating the problem.
```c++
// Get the current ParsedBuffer from the last text update we received
// from the editor. This can be nullptr if it could not be parsed.
//
// Use in operations that only really makes sense on the latest view and
// only if it was parseable, e.g. suggesting edits.
std::shared_ptr<const ParsedBuffer> current() const { return current_; }
```
When reading the comments, I thought maybe doing a .reset() on current_ would solve the problem and would be cleaner than adding the extra check of parsed_correctly(). However, this doesn't work because we need to work with the incorrect buffer to provide diagnostics.
On the other hand, I don't see …
=> Language Server - Avoid trying to format code in the presence of syntax errors

.github/workflows/verible-ci.yml, verilog/tools/ls/vscode/README.md, verilog/tools/ls/vscode/package.json, verilog/tools/ls/vscode/src/download-ls.ts, verilog/tools/ls/vscode/src/extension.ts
This PR adds downloading `verible-verilog-ls` (from GitHub release with tag matching plugin's version) to VSCode extension. 
Binary is downloaded only when language server's executable (from configs `verible.path`) is not available.
=> VSCode extension: Download necessary binary

.github/bin/check-potential-problems.sh
To make sure headers are unique, always use a path relative to the toplevel.
=> Make sure include files are always fully qualified.

verilog/CST/statement.cc, verilog/CST/statement.h, verilog/CST/statement_test.cc, verilog/analysis/checkers/BUILD, verilog/analysis/checkers/always_comb_rule.cc, verilog/analysis/checkers/always_comb_rule_test.cc
Note: clang-format introduced many changes in the files. 
First attempt on adding an AutoFix for the always_comb rule. It looks somewhat decent but there are some things I'm not completely satisfied with.
After inspecting the syntax tree with the cli tool
```
Node @0 (tag: kAlwaysStatement) {
Leaf @0 (#"always" @266-272: "always")
Node @1 (tag: kProceduralTimingControlStatement) {
Node @0 (tag: kEventControl) {
"..."
}
```
My approach has been to replace the *StringSpanOfSymbol* for kEvenControl for the empty string, as the syntax tree for an 'always_comb' doesnt present this element. With this, I also noticed that when performing this transformation we're changing the syntax tree, so I don't know whether this is ok or could cause problems elsewhere.
Other issues:
- The end result …
=> Add autofix for always_comb rule

.github/bin/generate-matrix.py
As per #1926, this is a temporary workaround to unblock releasing until we properly resolve the underlying cause of `arm64/centos` failures.
=> CI: skip arm64/centos

.github/workflows/verible-ci.yml
The documentation branch (`gh-pages`) was last updated in December 2022: https://github.com/chipsalliance/verible/tree/gh-pages. That's probably because the deployment step in the CI job does depend on `matrix.mode == 'compile'` but `matrix` is not defined in the job (https://github.com/chipsalliance/verible/blob/master/.github/workflows/verible-ci.yml#L575-L599), so the condition can never be met.
This PR removes the `matrix.mode` condition.
=> ci: fix gh-pages deployment condition

verilog/tools/ls/README.md, verilog/tools/ls/vscode/package.json, verilog/tools/ls/vscode/src/extension.ts
Fixes https://github.com/chipsalliance/verible/issues/1916
This PR adds possibility to provide command-line arguments for `verible-verilog-ls` from the level of VSCode extension.
=> VSCode extension: Added possibility to provide arguments to Language Server

.github/workflows/verible-ci.yml
This PR changes `windows-latest` to `windows-2019` to allow Bazel to correctly find and use Visual Studio binaries. Currently, Bazel has problem with proper finding of necessary binaries to build the project with newest Visual Studio 2022 (since version `20230606.1` of `windows-2022`, with Bazel 6.2.1)
=> GH Actions: Reduced version of the Windows image to 2019

verilog/formatting/align.cc, verilog/formatting/formatter_test.cc
This PR adapts the `ClassPropertyColumnSchemaScanner` dimension aligning logic into `DataDeclarationColumnSchemaScanner` as it produced malformed outputs when formatting a custom type.
Fixes #1765
=> Adapt ClassProperty scanner dimension logic to declaration aligning

verilog/formatting/formatter_test.cc, verilog/formatting/token_annotator.cc, verilog/formatting/tree_unwrapper.cc
This PR removes a unnecessary check when dealing with kReferenceCallBase where the r_paren token should be added regardless of partition policy (as the style dictates that the bracket is always connected to the last token)
Fixes #1894 
Fixes #1924
=> Fix macro formatting divergence and splitting issues

verilog/analysis/symbol_table.cc, verilog/analysis/symbol_table.h, verilog/analysis/symbol_table_test.cc, verilog/parser/verilog.y, verilog/tools/ls/symbol-table-handler.cc, verilog/tools/ls/verilog-language-server_test.cc
Fixes #1673
Fixes #1668
Fixes #1783
This PR:
=> [LSP] textDocument/definition: Going to ports and module definitions

verilog/analysis/verilog_linter_configuration.cc, verilog/analysis/verilog_linter_configuration_test.cc
Issue https://github.com/chipsalliance/verible/issues/1121 pointed out a minor thing that might be confusing.
The suggestion was to change the documentation or adding the simple workaround. I went with the workaround.
This minor change also makes possible to add wrapping quotation marks when it wasn't possible before:
```
verible-verilog-lint --rules=explicit-parameter-storage-type=\"exempt_type:string\" a.sv 
```
becomes possible.
=> [LINT] Consistent rule config parsing

verilog/tools/kythe/BUILD
No need to depend on full protobuf, just the io part is what we're interested in.
=> Slightly reduce dependency.

verilog/tools/kythe/kzip_creator.cc
=> Encourage compiler to pick up openssl header from WORKSPACE first.

.github/workflows/verible-ci.yml
To make sure the artifact is released, we need to wait for MacBuild to finish.
=> Set release dependency on MacBuild

README.md
The gcc-9 mentioned before only had c++17 compatibility as experimental feature, in particular library completeness. Suggest g++ 10 as minimum (which is already very old at this point, so should not be a problem).
=> Update README with min version of gcc.

WORKSPACE, verilog/tools/kythe/BUILD, verilog/tools/kythe/kzip_creator.cc, verilog/tools/kythe/kzip_creator.h
=> Remove boringssl dependency. Replace sha256 with absl::Hash.

.github/bin/run-clang-tidy-cached.cc, common/util/BUILD, common/util/tree_operations_test.cc
This test puts a lot of burden on the compiler and compilation alone takes about 120 seconds or so. Break it up into shards in which only parts of the tests are ifdef'ed in in each shard. Now each shard takes around 20-25 seconds, less likely to dominate the critical compilation path.
=> Break tree_operations test into shards.

verilog/transform/obfuscate.cc, verilog/transform/obfuscate_test.cc
Fixes #1985. Added a simple test case along with the fix.
=> obfuscator: add missing case in ObfuscateVerilogCodeInternal

common/lsp/json-rpc-expect.cc, common/lsp/message-stream-splitter.cc, common/lsp/message-stream-splitter.h, common/lsp/message-stream-splitter_test.cc
We had a lenient mode for header parsing coming from the early days of the implementation of the LSP protocol, however, that is not used anymore. Remove it to simplify logic.
=> Simplify json rpc header parsing: remove lenient mode.

LICENSE, common/tools/BUILD
Resolve the licensing mismatch after adding sha256 code by adding the BSD-3 license to the LICENSE file (but limit it to the sha256 code). The compliance check tool is passing with this change.
Moving the code to a separate package, with a separate license didn't work -- the top level LICENSE file had to be updated anyway. This is the simplest & easiest to maintain solution.
I addition, add default_applicable_licenses to common/tools/BUILD package to silence the compliance check tool.
=> Cover sha256 code with BSD-3 license. Add default_applicable_licenses to common/tools/BUILD package.

.github/workflows/verible-ci.yml
Bazel fails with LLVM 16, which is now installed on Windows CI.
Fix version 15 for now.
The issue is [resolved in bazel](https://github.com/bazelbuild/bazel/pull/19430), but not released yet.
=> Fix Windows LLVM to version 15 until bazel 6.4

.github/bin/smoke-test.sh, common/analysis/command_file_lexer.h, common/util/tree_operations_test.cc, external_libs/editscript_test.cc, verilog/analysis/symbol_table.cc, verilog/analysis/symbol_table_test.cc, verilog/analysis/verilog_linter.cc, verilog/analysis/verilog_project.cc, verilog/formatting/tree_unwrapper_test.cc
Make absl::Status that is to be returned non-const, so that the compiler can apply move.
Remove an unnecessary double-copy of a ostream string.
=> Fix some standard headers missed in the last PR.

.github/bin/smoke-test.sh, common/util/tree_operations_test.cc
C++20 auto-generates the != operator from ==. However, if that operator accepts a potentiallly different type, this might result in an ambiguous operator (-Wambiguous-reversed-operator). This provides the explicitly defined operator.
=> C++20 preparation: make operator != non-ambiguous.

verilog/analysis/symbol_table.cc
This situation seems to arise if we have possibly multiple parent references when fed a bunch of possibly unrelated files with naming overlap. Don't crash in this case.
=> SymbolTable: Gracefully handle current CHECK-fail

verilog/tools/ls/BUILD
The only relevant visible part is the binary, that is already marked public.
Context: cl/580583239
=> Reduce unnecessary visibility.

.github/bin/install-bazel.sh, .github/bin/install-kythe-tools.sh, .github/workflows/verible-ci.yml
By default, it comes with bazel 7, but that won't work with our version of protobuf.
We can't update protobuf, as that doesn't work with bazel 4, which we currently have as minimum requirement.
=> Pin bazel version to version 6 in MacOS

.github/bin/smoke-test.sh
Also, make script a little more robust on flaky network connections (projects that could not be downloaded are considered best-effort).
Add more quotes around `"${VAR_EXPANSION}"`.
=> Update smoke test with new number expectations.

common/text/concrete_syntax_tree.h, common/text/tree_utils.cc, common/util/iterator_adaptors.h, verilog/CST/type.cc, verilog/tools/kythe/indexing_facts_tree_extractor.cc
This is work towards being able to exchange the container for easier and faster memory management.
We can't quite replace the mutable container hand-out yet as there is still one location that calls a container function (pop_back()).
Issues: #1523
=> SyntaxTreeNode: hand out ranges not containers.

verilog/tools/kythe/kzip_creator.cc, verilog/tools/kythe/kzip_creator.h
gcc12 complains that some attribute of fclose() is not kept ('ignoring attributes on template argument 'int (*)(FILE*)'). Changing this to a deleter type which is anyway more clean.
=> Use a deleter type insteadl of function pointer to close FILE.

verilog/formatting/tree_unwrapper.cc
The TreeUnwrapper::ReshapeTokenPartitions() is getting pretty big.
=> Break out long case-block into its own function.

common/util/init_command_line.cc, common/util/logging.h
In the unreleased head of absl, a
[VLOG()](https://github.com/abseil/abseil-cpp/blob/bae260199fffe782d5a5414bb80cfe49abb1436f/absl/log/absl_vlog_is_on.h) implementation is available now.
Make sure we can compile with the current and future absl.
=> Get ready for ABSL providing a VLOG() implementation.

.github/workflows/verible-ci.yml
Now that the Build job is not running anymore, we need to get the resulting binaries from the regular CI run.
=> Actually pack up static results for release.

verilog/tools/ls/README.md
This language server can be easily configured for Emacs also through the [`verilog-ext`](https://github.com/gmlarumbe/verilog-ext/) extension package.
It supports Emacs builtin `eglot` client as well as `lsp-mode`.
=> Update Emacs config section of language server README.md

common/analysis/linter_test_utils.h, verilog/analysis/checkers/BUILD, verilog/analysis/checkers/suspicious_semicolon_rule.cc, verilog/analysis/checkers/suspicious_semicolon_rule.h, verilog/analysis/checkers/suspicious_semicolon_rule_test.cc, verilog/tools/lint/BUILD, verilog/tools/lint/testdata/forbid_consecutive_null_statements.sv, verilog/tools/lint/testdata/suspicious_semicolon.sv
Inspired by [clang-tidy's similar check](https://clang.llvm.org/extra/clang-tidy/checks/bugprone/suspicious-semicolon.html#bugprone-suspicious-semicolon).
Things to note:
- verilog/tools/lint/testdata/forbid_consecutive_null_statement.sv has been modified so it doesn't fail under this rule too.
I don't think this will flag any code that isn't wrong except the typical
```systemverilog
while(myCoolFunction());
```
which [I don't think](https://github.com/search?q=%2Fwhile%5C%28%5B%5E%5C%29%5D*%5C%29%3B%2F+language%3AVerilog++OR+language%3ASystemVerilog+&type=code&ref=advsearch) is a particular common idiom in [System]Verilog. It can be fixed with an empty `begin end`. I could also make the check more specific (require that there isn't a function or task call inside the while condition (?)). …
=> linter: Add suspicious-semicolon rule

verilog/analysis/verilog_linter_configuration.cc, verilog/analysis/verilog_linter_configuration.h, verilog/analysis/verilog_linter_configuration_test.cc
Context: https://github.com/chipsalliance/verible/issues/1994 
Already explained in the issue but I think this is way more intuitive than current behaviour. You fire up your editor and might or might not notice that the linter is going back to the default rules because your config isn't right.
If we had a fixed set of rules I guess that would be ok but it is a bit annoying when developing new rules and might also be annoying if users borrow other's `.rules.verible_lint` files with different versions of verible
=> linter: configuration: Ignore incorrect rules

common/text/concrete_syntax_tree.h, common/text/tree_utils.cc
The container is now ready to be replaced with other implementations for nicer node allocations.
Issues: #1523
=> Remove last trace of child container assumptions in SyntaxTreeNode.

common/strings/string_memory_map.h, common/strings/string_memory_map_test.cc, common/util/interval_set.h, common/util/interval_set_test.cc, verilog/analysis/verilog_project.cc, verilog/analysis/verilog_project.h, verilog/analysis/verilog_project_test.cc, verilog/tools/kythe/indexing_facts_tree_extractor_test.cc, verilog/tools/kythe/verilog_kythe_extractor.cc, verilog/tools/ls/BUILD, verilog/tools/ls/autoexpand_test.cc, verilog/tools/ls/lsp-parse-buffer.cc, verilog/tools/ls/lsp-parse-buffer.h, verilog/tools/ls/lsp-parse-buffer_test.cc, verilog/tools/ls/symbol-table-handler.cc, verilog/tools/ls/symbol-table-handler.h, verilog/tools/ls/verilog-language-server.cc
This fixes #2078.
Since some changes are somewhat independent, they are in three different commits.
This also fixes the misfeature that the string view index had to be disabled in cases the `VerilogProject` is used where it needs to remove files. So instead of a fractured class use, this is now merely a feature that can be enabled.
=> Fix string view index in UpdateFileContents()

verilog/tools/ls/README.md, verilog/tools/ls/verilog-language-server.cc
With the new environment variable VERIBLE_LS_PROJECTROOT_OVERRIDE, it is possible to override whatever project root the editor provides.
=> Provide a way to override the project root the language server uses.

common/lsp/lsp-protocol.yaml, verilog/tools/ls/symbol-table-handler.cc, verilog/tools/ls/symbol-table-handler.h, verilog/tools/ls/symbol-table-handler_test.cc, verilog/tools/ls/verilog-language-server.cc, verilog/tools/ls/verilog-language-server_test.cc
This is a rebase of original Pull Reqeust #1948 by @jbylicki See commit history there.
=> Add Symbol Renaming to the language server

common/util/init_command_line.cc, common/util/init_command_line.h
This mostly clarifies functionality (though not necessarily be needed to be called by the user, as it already happens in InitCommandLine()).
=> Break out setting log levels by environment variables.

verilog/tools/ls/BUILD, verilog/tools/ls/symbol-table-handler.cc, verilog/tools/ls/verible-verilog-ls.cc
Also, fix some includes in symbol-table-handler.cc
=> Rename verilog_ls.cc to the actual name the binary has.

verilog/tools/ls/lsp-parse-buffer.cc, verilog/tools/ls/lsp-parse-buffer_test.cc, verilog/tools/ls/symbol-table-handler.cc, verilog/tools/ls/symbol-table-handler.h, verilog/tools/ls/symbol-table-handler_test.cc, verilog/tools/ls/verilog-language-server.cc, verilog/tools/ls/verilog-language-server.h
The VerilogProject is sensitive to adding the exact same file content twice, as it buildls a string index mapping back to the file.
The symbol table was ignnoring updates with files that might not be parseable, where the `last_good()` was essentially not changing, i.e. it was pushing the same `last_good()` content (with the exact same string view content) to the project which made it not happy. This problematic handling was probably highlighted by the recent fix of #2078 which made sure all registering and unregistering of files is accounted for.
The actual fix is small, so split into two commits
* https://github.com/chipsalliance/verible/commit/75463fff739668dd75500b0bff9be4aacf747c06 is refactoring the current notification and moves from the language server to handled more locally in …
=> Fix potential double-update of a buffer in Verilog Projecdt

.github/bin/build-and-test.sh, .github/workflows/verible-ci.yml, common/text/text_structure_test.cc, verilog/tools/ls/autoexpand.cc
The weak ordering issue needs to be addressed, but for now, just document it.
Issues: #2099
=> Optimize DependsOn(); also documnt #2099

.bazelrc, shell.nix
Bazel just invokes the compiler (gcc or clang) in its basic form and expects it to figure out if the language is C or C++.
Make sure it always is told that it is C++; not all compiler installatins are set-up to auto-detect (looking at you, clang-installation-on-NixOS...).
Works around
Issue https://github.com/NixOS/nixpkgs/issues/216047
Issue https://github.com/NixOS/nixpkgs/issues/150655
=> Always pass `-xc++`: Tell the compiler the language to compile

verilog/analysis/checkers/uvm_macro_semicolon_rule.cc, verilog/analysis/checkers/uvm_macro_semicolon_rule_test.cc
Macros like `UVM_REG_DATA_WIDTH were being flagged by the rule when they shouldn't.
To the best of my knowledge, the only UVM macros that are parsed like `MacroIdentifier` and should be flagged are the ones ending with `_end`:
uvm_component_utils_end,
uvm_error_context_end,
...
More context: https://github.com/chipsalliance/verible/issues/2107
=> lint: remove false positives from uvm-macro-semicolon

WORKSPACE, common/analysis/BUILD, common/analysis/matcher/BUILD, common/formatting/BUILD, common/lexer/BUILD, common/lsp/BUILD, common/parser/BUILD, common/strings/BUILD, common/text/BUILD, common/tools/BUILD, common/util/BUILD, external_libs/BUILD, shell.nix, verilog/CST/BUILD, verilog/analysis/BUILD, verilog/analysis/checkers/BUILD, verilog/formatting/BUILD, verilog/parser/BUILD, verilog/preprocessor/BUILD, verilog/tools/kythe/BUILD, verilog/tools/ls/BUILD, verilog/transform/BUILD
The layering_check feature of bazel complained that the direct dependency for using the header was not included.
Doesn't matter much in practice, but being explicit about the dependencies is also nice.
(It will then eventually be possible to run the layering check in the CI, so that things are not forgotten accidentally)
=> For unit tests: add gtest libraries explicitly not only gtest_main.

common/analysis/BUILD, common/analysis/command_file_lexer.cc, common/analysis/command_file_lexer.h, common/analysis/lint_waiver.h
It was exported by `common/analysis:command-file-lexer` and `common/analysis:lint-waiver`
Found by github.com/hzeller/bant.
=> Don't declare lint_waiver.h to be exported by two different targets.

WORKSPACE
This is the first step to make this work on newer bazels.
=> Update bazel_rules_install. Compatible with bzlmod.

README.md, WORKSPACE
When we drop bazel 5, we will be able to either switch to bzlmod or move the options "--noenable_bzlmod" to the .bazelrc.
=> Updated platforms dependency to support bazel 7

verilog/analysis/symbol_table.cc, verilog/analysis/symbol_table.h, verilog/tools/ls/BUILD, verilog/tools/ls/hover.cc, verilog/tools/ls/hover.h, verilog/tools/ls/symbol-table-handler.cc, verilog/tools/ls/symbol-table-handler.h, verilog/tools/ls/verilog-language-server.cc, verilog/tools/ls/verilog-language-server_test.cc
Rebased from PR #1922
This will implement the method, but currently it is not offered yet in the initialization to the editor; to be enabled once tests finished.
=> Initial support for  textDocument/hover request.

WORKSPACE, bazel/nlohmann-libname.patch, common/lsp/BUILD, common/text/BUILD, common/tools/BUILD, common/tools/jcxxgen.bzl, verilog/CST/BUILD, verilog/analysis/BUILD, verilog/tools/ls/BUILD, verilog/tools/syntax/BUILD
These seem to be different otherwise in WORKSPACE and MODULE.bazel.
=> Change name of "@jsonhpp" to "@jsonhpp//:json" for WORKSPACE

BUILD, bazel/BUILD
Someone importing the project thus does not need that pull in that dependency directly.
=> Move installer to the bazel/ subdir, but provide a toplevel alias.

WORKSPACE, bazel/zlib.BUILD, common/util/BUILD
The way WORKSPACE processes dependencies, we need to define before proto.
=> Since we use zlib, don't rely on protobuf implicitly providing it.

verilog/analysis/verilog_linter_configuration.cc, verilog/analysis/verilog_linter_configuration.h, verilog/analysis/verilog_linter_configuration_test.cc
When parsing a configuration file, if the user provides more than one configuration for the same rule, the last value will be used.
As this can be confusing, let's emit a warning whenever this happens.
See https://github.com/chipsalliance/verible/issues/2136 for context.
I'd argue that this isn't **crucial** but it is pretty cheap to do and it might save a lot of time for some users
=> linter: configuration: emit warnings user configuration overrides itself

verilog/analysis/checkers/explicit_parameter_storage_type_rule.cc, verilog/analysis/checkers/explicit_parameter_storage_type_rule_test.cc, verilog/analysis/verilog_linter.cc, verilog/analysis/verilog_linter.h, verilog/analysis/verilog_linter_configuration.cc, verilog/analysis/verilog_linter_configuration.h, verilog/analysis/verilog_linter_test.cc, verilog/tools/lint/verilog_lint.cc
Adding feature to print the lint rules in a format suitable to be used as '.rules.verible_lint' as mentioned in #2148
Execute 'verible-verilog-lint --print_rules_file' to print the default rules to stdout. Users can then pipe/copy&paste the output to a file for latter use ('.rules.verible_lint' for example).
Example output:
~/git/verible/bazel-bin/verilog/tools/lint$ ./verible-verilog-lint --print_rules_file
+always-comb
+always-comb-blocking
+always-ff-non-blocking=catch_modifying_assignments:false;waive_for_locals:false
-banned-declared-name-patterns
+case-missing-default
+constraint-name-style
+create-object-name-match
-disable-statement
-endif-comment
...
=> Adding feature to print the lint rules in a format suitable to be used as '.rules.verible_lint' @see #2148

MODULE.bazel
The latest version in the bzlmod repo does have the absl dependency, so we can simplify the import.
=> Update protobuf in bzlmod

verilog/tools/ls/vscode/src/download-ls.ts, verilog/tools/ls/vscode/src/extension.ts
Resolves #2154 
Fixes several issues with the VSCode extension
1. Fixes issue on windows where users are unable to set an absolute (or relative) path to the language server.
2. Fixes issue on Linux preventing users to use ~/ paths to language server.
3. Fixed issue found while testing the above where the extension on windows dosn't extract the langauge server out of the downloaded zip file.
=> Vscode is binary found

common/analysis/line_lint_rule.h, common/analysis/syntax_tree_lint_rule.h, common/analysis/text_structure_lint_rule.h, common/analysis/token_stream_lint_rule.h, common/analysis/violation_handler.h, common/formatting/tree_unwrapper.h, common/lexer/flex_lexer_adapter.h, common/lexer/token_stream_adapter_test.cc, common/text/text_structure_test.cc, common/text/tree_context_visitor.h, verilog/tools/ls/verilog-language-server_test.cc
This helps documenting the code for the reader. For the compiler, it might open devirtualization opportunities.
Document all the methods that can not be set `final` because they are in fact overridden later. Mark as `// not yet final`. This will be useful in future automated cleanups.
=> Prefer 'final', only use 'override' where needed.

common/text/token_info.h, verilog/analysis/verilog_linter_configuration.h
If there is a copy constructor, we also would have to define an assignment operator. Since these are default anyway, just use the default as-is.
=> Remove explicit copy constructors with default implementation.

.github/workflows/verible-ci.yml, verilog/tools/lint/lint_tool_test.sh
Observed issues with recent MacOS CI.
=> lint_tool_test: On issues, print out patch that broke.

.github/bin/check-potential-problems.sh, .github/bin/run-clang-tidy-cached.cc, external_libs/editscript.h, external_libs/editscript_test.cc
Older clang-tidy did not have --config-file yet, these days they have, which simplifies things.
Fix issues found in editscript* which is now included in clang-tidy runs.
=> Simplify clang-tidy; read directly from .clang-tidy config file.

verilog/analysis/verilog_project.cc, verilog/analysis/verilog_project_test.cc
Resolves #2178 
This PR resolves issue where removing an empty file from the verible.filelist causes the language server to stop.
=> Fixes language server issue when empty file is removed from verible.filelist

common/analysis/linter_test_utils.h, verilog/analysis/checkers/BUILD, verilog/analysis/checkers/module_filename_rule.cc, verilog/analysis/checkers/module_filename_rule_test.cc
Added a simple autofix for [module-filename] lint rule to rename the module to match the filename.
=> Module file name rule autofix

verilog/CST/verilog_matchers.h, verilog/CST/verilog_matchers_test.cc, verilog/analysis/checkers/case_missing_default_rule.cc, verilog/analysis/checkers/case_missing_default_rule_test.cc
Fixes https://github.com/chipsalliance/verible/issues/1278
Currently, case-missing-default rule requires the `default` case for every case statement. This PR makes an exception for `unique case` statements as requested by the issue.
I also changed where the diagnostics point to. Previously they pointed to the leftmost token of the kCaseItemList, but now they point to the `case` keyword.
=> linter: do not require 'default' case for 'unique case'

.github/workflows/verible-ci.yml, common/analysis/BUILD
This adds the http://bant.build/ tool in the CI checking, for missing and superfluous dependencies in BUILD files and emitting a `buildozer`[^1] script to fix (The CI just checks the cleanness, the user has to run the buildozer commands and update the PR).
Fixes #655
(There is an open feature request issue on bazel for such a tool, but none exists as of now (https://github.com/bazelbuild/bazel/issues/6871).
The `bant` utility generally helps to explore targets and dependencies in bazel projects, and it has a `dwyu` (_Depend-on What You Use_)  feature which helps with clean-ups, so it pretty much provides `build_cleaner` functionality.
The `bant dwyu` works very well on the C++ projects I have tested in on (Verible is so clean as I used an earlier development version of bant on it already; …
=> Integrate `bant` BUILD dependency cleaner into CI

verilog/parser/verilog.y
Fixes issue #2181.
As suggested by @hzeller, I've ran `.github/bin/smoke-test.sh` and the output was the same before and after commenting out the faulty production rule.
=> Fix bug caused by faulty production rule

.github/workflows/verible-ci.yml
=> Use Windows CI runner 2019 (2022 has issues).

.github/workflows/verible-ci.yml
Had a look at this tonight and seems to work for me. Still using the  windows 2019 runner just to get things up and running again.
Thanks @corco for the tip.
=> Fix for Windows Builds

.readthedocs.yaml, doc/conf.py, doc/index.rst, doc/requirements.txt
Add a bunch of files that are no longer provided by default;
* `.readthedocs.yml` and `requirements.txt` for configuration of the readthedocs build.
* `conf.py` file for configuration of sphinx.
* `index.rst` file to provide a based page.
=> Fixing the Read The Docs action

verilog/parser/verilog.y
In _Syntax 6-2_ of the SystemVerilog (exert from _A.2.1.3 Type declarations_) the generic net `interconnect` is allowed but currently this is still flagged by the linter as a syntax error.
```verilog
module mod_a (output wire logic [4:0] net_a);
endmodule
module mod_b (input wire logic [4:0] net_b);
endmodule
module mod_c ();
interconnect net_interconnect;
mod_a mod_a (
.net_a(net_interconnect);
);
mod_b mod_b (
.net_b(net_interconnect);
);
endmodule
```
=> [LINT] Allow interconnection net or port (Syntax 6-2)

README.md
fixes #2163
the installation of verible on macOS is a hit and miss process. the release binaries seems to work fine when extracted and placed in bin other than that, homebrew package itself has some issues.
mentioning outright that nix has binaries available for MacOS in the installation of readme is misleading because the nixpkgs doesn't add macOS as a supported platform and it failes to compile even if you override it. this small change might be insignificant but saves countless hours of nixxing for future readers of readme until the nix pkg issue is fixed.
=> fix misleading readme #2163

.github/workflows/verible-ci.yml, MODULE.bazel
Some dependencies are written in a way that they require bazel 7, so can't use them yet.
=> Document why we're stuck in some older versions in bzlmod

common/lsp/lsp-protocol-enums.h, common/lsp/lsp-protocol.yaml
Note: this will be used in a dependent XLS change.
=> Add support for inlay hint objects in LSP generation.

verilog/analysis/checkers/enum_name_style_rule.cc, verilog/analysis/checkers/package_filename_rule.cc, verilog/analysis/checkers/signal_name_style_rule.cc
As discussed in #2213, fixing the naming style for a few constants.
=> Fixing naming style for constant expressions

verilog/analysis/symbol_table.cc, verilog/analysis/symbol_table_test.cc
This PR adds interfaces to the symbol table. This resolves verible-verilog-project not listing files with interface declarations as dependencies, and fixes the "Go to Definition" feature of the LSP for interface declarations.
Resolves #2196
=> Fixes issue where interfaces were not being added to the symbol table.

common/util/BUILD, common/util/tree_operations_test.cc, verilog/analysis/BUILD, verilog/analysis/symbol_table_test.cc
The tree_operations_test.cc and symbol_table_test.cc are usually excluded from the clang-tidy checks because clang-tidy is particularly slow on them. So there were some includes missing, which are fixed here.
=> Fix clang-tidy findings on files usually excluded.

.github/bin/run-clang-tidy-cached.cc
Get a fresh version of the clang-tidy runner from upstream.
=> Update run-clang-tidy-cached.cc from upstream.

verilog/analysis/checkers/instance_shadow_rule.cc, verilog/analysis/checkers/instance_shadow_rule.h, verilog/analysis/checkers/instance_shadow_rule_test.cc
This PR resolves #2248, fixing the issue with the lint rule 'instance-shadowing' raising violations on modport items.
The change simply ignores symbols in modports, both simple and clocking ports.
=> Instance shadowing fix modport

common/util/tree_operations_test.cc
It might not see all if-def'ed branches.
=> clang-tidy can get confused if gmock is needed.

MODULE.bazel, bazel/nlohmann_module.patch
clang-tidy complains if a symbol is not in a header directly included with the [misc-include-cleaner] check. Since the multi-header does one indirection, this results in these warnings.
Using the single-header library helps. Patch upostream bzlmod package to provide that.
TODO: check with bzlmod mintainer for nlohmann_json to maybe provide a target for that.
=> Use single-header json implementation.

common/util/sha256_test.cc
It was reporting some bogus new-delete leak there. Anyway, circumvent that by simply using regular EXPECT_EQ().
=> clang-tidy sometimes gets confused about EXPECT_THAT() matchers.

common/text/config_utils.cc, common/text/config_utils_test.cc
```
$ cat .rules.verible_lint
+always-ff-non-blocking=catch_modifying_assignments:on;
$ verible-verilog-lint file.sv --rules_config_search
E0929 18:52:13.789277   24408 verilog_linter.cc:146] Fatal error: always-ff-non-blocking : unknown parameter; supported parameters are 'catch_modifying_assignments', 'waive_for_locals'
```
Current configuration parsing hard-fails upon encountering trailing or leading semicolons in the configuration string. Let's make the process more robust and ignore them.
=> common: text: config_utils: make ParseNameValues skip empty strings

common/text/BUILD, common/text/token_info.cc, verilog/parser/verilog.y, verilog/tools/syntax/verilog_syntax_test.sh
The newline token can mean `'\n'`, but also `'\r\n'`, so printing the
token symbolic name as simply `<<\n>>` can be confusing in that context; instead,
print it as symbolic name `<<newline>>`.
Also: the actual raw text of the token is printed in a c-escaped way now,
which makes it easier to human-read if special characters are involved
(and possibly easier to process when grepping through results).
=> Give newline token symbolic name; print raw tokens c-escaped.

.github/workflows/verible-ci.yml, common/util/file_util.cc, verilog/analysis/checkers/token_stream_lint_rule.cc, verilog/analysis/checkers/token_stream_lint_rule_test.cc, verilog/tools/obfuscator/verilog_obfuscate.cc
std::fstream is much slower than the good ol' standard implementation. In addition, there are no risks of throwing exceptions.
=> If non-mmap: use stdio reading of files instead of std::stream

verilog/analysis/checkers/BUILD, verilog/analysis/checkers/forbid_line_continuations_rule.cc, verilog/analysis/checkers/forbid_line_continuations_rule.h, verilog/analysis/checkers/forbid_line_continuations_rule_test.cc
The old name was token_stream_lint_rule{.h,.cc,_test.cc} which sounds like an accidental use of a generic example name.
Renamed this now to match the actual rule it implements forbid_line_continuations_rule{.h,.cc,_test.cc}
=> Rename forbid-line-continuations rule file to match rule name

common/lsp/lsp-protocol.yaml
See https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_rename
Result is `WorkspaceEdit` which prefers `documentChanges` which contain `TextDocumentEdit[]`
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspaceEdit
(Note: we can do this with support for `changes?` in the LSP but this is the suggested way for new implementations, so figured I'd add.)
=> [LSP] Add TextDocumentEdit for textDocument/rename support.

verible/verilog/formatting/verilog-token_test.cc
UBSAN is good in knowing beforehand that tests some out-of-range mitigation, that the value in question is indeed out of range and will complain.
=> Skip a test that will fail with ubsan in case that sanitizer is enabled.

.github/bin/simple-install.sh, .github/workflows/verible-ci.yml, BUILD, MODULE.bazel, README.md, WORKSPACE, WORKSPACE.bzlmod, bazel/BUILD, verible/verilog/tools/formatter/BUILD
The upstream installer bazel utility is not updated and is not working well on all operating systems. Let's simplify that by just using the script we already have.
=> Always use included script for installing.

.github/bin/check-potential-problems.sh
.bazelversion is a very crude bazel feature that does not support semantic versioning, let alone version ranges. In combination with baselisk, it even attempts to download binaries from the 'net instead of using system-available versions.
Instead of pinning a bazel version, the repo should be kept in a state, that it works with all actively maintained bazel versions.
=> Add a potential problems check to make sure no .bazelversion is used.

bazel/absl.patch
On gcc and clang-based systems, std::string_view has the iterator behave as expected by a lot of Verible code, being a const char*.
On windows c++ lib, the iterator is its own object, which does not decay to const char*, so in that case we need to use the absl:: implementation which behaves like that.
We used to always change to the absl type, but in reality, we only need to do that on Windows; adapt the abseil patch.
Longer term, we should remove the expectation of the iterator type, but that requires access to a Windows machine to locally go through a compile/fix loop.
=> Only switch to absl::string_view implementation on Windows.

verible/common/analysis/file-analyzer.cc, verible/common/analysis/lint-rule-status.cc, verible/common/formatting/format-token_test.cc, verible/common/strings/position_test.cc, verible/common/strings/range_test.cc, verible/common/strings/split_test.cc, verible/common/text/token-info-test-util_test.cc, verible/common/text/tree-builder-test-util.cc, verible/common/text/tree-compare_test.cc, verible/common/text/tree-utils_test.cc, verible/common/util/range_test.cc, verible/verilog/analysis/checkers/BUILD, verible/verilog/analysis/checkers/forbidden-symbol-rule.cc, verible/verilog/analysis/checkers/package-filename-rule.cc, verible/verilog/analysis/checkers/parameter-name-style-rule.cc, verible/verilog/analysis/symbol-table.h, verible/verilog/analysis/verilog-linter-configuration_test.cc, verible/verilog/analysis/verilog-project.cc, verible/verilog/analysis/verilog-project_test.cc, verible/verilog/formatting/tree-unwrapper_test.cc, verible/verilog/tools/kythe/indexing-facts-tree-extractor_test.cc, verible/verilog/tools/kythe/kythe-facts.h, verible/verilog/tools/ls/symbol-table-handler_test.cc
A string_view initialized with an empty string "" is different from a string_view that is empty initialized (it holds a nullptr). Make sure that all places that deal with string_views (from a testable perspective) also accept empty() with null string views.
=> Don't initialize empty string_views. Find places that were not prepared.

MODULE.bazel
* The m4/flex/bison rules don't need the toolchain stuff.
* googletest: can be a dev_dependency
=> Simplify MODULE.bazel

.github/bin/make-compilation-db.sh, .github/bin/run-build-cleaner.sh, .github/bin/run-format.sh, .github/bin/smoke-test.sh, .github/workflows/verible-ci.yml
Move the burden to make sure all dependencies are prefetched from the caller of make-compilation-db.sh to the script itself.
=> make-compilation-db: trigger relevant dependency fetches in script.

.readthedocs.yaml
https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/
Fixes #2327.
=> Set the sphinx config file correctly.

.github/workflows/verible-ci.yml
The automatically created URLs from archives are not stable
https://github.com/orgs/community/discussions/46034
so also craete a release artifact that we packed ourselves and will stay as-is.
=> Also pack source for release.

MODULE.bazel, verible/common/formatting/BUILD, verible/verilog/analysis/BUILD, verible/verilog/tools/ls/BUILD
Essentially, allow to compile with newer abseil-cpp even though we have to stay on an older version to honor older bazel versions.
Issues: https://github.com/chipsalliance/verible/issues/2336
=> Don't complain about vlog layering check in newer abseil.

.github/bin/make-compilation-db.sh, .github/bin/run-build-cleaner.sh, MODULE.bazel
Both of these use http://bant.build/ - simplify the scripts around it.
* make compilation db: reduce need for command line tools; no egrep needed anymore.
* build cleaner: output info messaging to stderr, so that output can be sourced directly.
=> build cleaner, compilation db making: simplify

verible/common/analysis/matcher/inner-match-handlers.cc, verible/common/formatting/align.cc, verible/common/lsp/dummy-ls.cc, verible/common/lsp/jcxxgen.cc, verible/common/lsp/lsp-file-utils_test.cc, verible/common/strings/diff_test.cc, verible/common/text/text-structure.cc, verible/common/text/text-structure_test.cc, verible/verilog/CST/module.cc, verible/verilog/CST/statement.cc, verible/verilog/CST/type.cc, verible/verilog/analysis/verilog-linter-configuration.cc, verible/verilog/formatting/align.cc, verible/verilog/formatting/formatter.cc, verible/verilog/formatting/formatter_test.cc, verible/verilog/formatting/token-annotator.cc, verible/verilog/formatting/tree-unwrapper.cc, verible/verilog/tools/diff/verilog-diff.cc, verible/verilog/tools/formatter/verilog-format.cc, verible/verilog/tools/kythe/indexing-facts-tree-extractor.cc, verible/verilog/tools/lint/verilog-lint.cc, verible/verilog/tools/ls/symbol-table-handler.cc
There are a bunch of functions only really used locally, so make them explicitly static (or put in anonymous namespace). Functiont that are not in header files but are used externally (typically in their corresponding tests): mark explicitly extern.
(Hat-tip to new clang-tidy check `[misc-use-internal-linkage]`)
=> Be a bit more explicit with internal and external linkage.

.clang-tidy, verible/common/formatting/align.cc, verible/common/formatting/layout-optimizer-internal.h, verible/common/formatting/layout-optimizer.cc, verible/common/lsp/lsp-text-buffer.cc, verible/common/lsp/message-stream-splitter.cc, verible/common/text/macro-definition.cc, verible/common/text/tree-utils.h, verible/common/util/container-proxy_test.cc, verible/common/util/container-util.h, verible/common/util/file-util.cc, verible/common/util/forward.h, verible/verilog/analysis/checkers/constraint-name-style-rule.cc, verible/verilog/analysis/verilog-linter-configuration.cc, verible/verilog/formatting/token-annotator.cc, verible/verilog/tools/ls/autoexpand.cc
clang-tidy 19 finds more things :)
=> A few clang-tidy findings addressed

shell.nix, verible/common/util/container-util.h, verible/verilog/parser/verilog-lexical-context.cc, verible/verilog/tools/ls/BUILD, verible/verilog/tools/ls/autoexpand.cc
... but for now, just use clang-tidy 19 in shell.nix. TODO: Update to clang-tidy 19 in CI
=> Get ready for clang-tidy 20

verible/verilog/parser/verilog.lex
After debugging, I found that the issue was caused by RejectChar truncating multi-byte illegal characters, which led to the exception when converting JSON to string. I have made the necessary changes, and this resolves issue https://github.com/chipsalliance/verible/issues/2372.
=> fix(verilog/parser):fix the truncation bug of rejectChar #2372

verible/verilog/tools/ls/BUILD, verible/verilog/tools/ls/verible-verilog-ls.cc, verible/verilog/tools/ls/verible-verilog-ls_test.sh, verible/verilog/tools/ls/verilog-language-server.cc, verible/verilog/tools/ls/verilog-language-server.h, verible/verilog/tools/ls/verilog-language-server_test.cc
These days, editors seem to mostly use the feature to actively request diagnostics, so sending them as notification is just creating unnecessary churn and possibly are shown twice.
Default off now, but can be enabled with `--push_diagnostic_notifications`
Issues #2164 #2376
=> Don't send diagnostic notifiacations by default.

.github/bin/before-submit.sh, .github/bin/get-bant-path.sh
The compilation-db is not only useful for the clang-tidy run, but also as preparation for `bant dwyu` to see all external dependencies. Also - it is useful for development purposes of course.
=> before-submit.sh: unconditionally update compilation-db

.github/bin/make-compilation-db.sh
With the upcoming more complicated way of defining multiple configs in the .bazelrc, current bant can't look through that and exctract the `-xc++` flag anymore.
=> Make sure that -xc++ is always part of the compilation DB.

.bazelrc, .github/bin/build-and-test.sh, .github/bin/install-bazel.sh, .github/bin/install-kythe.sh, .github/bin/run-format.sh, .github/bin/run-kythe.sh, .github/settings.sh, .github/workflows/verible-ci.yml, BUILD, MODULE.bazel, verible/common/formatting/BUILD, verible/verilog/analysis/BUILD, verible/verilog/parser/BUILD, verible/verilog/tools/ls/BUILD
Bump the Kythe version for the CI. Enable the xRefs action and use newer Ubuntu
=> Re-enable Kythe xRefs publishing

MODULE.bazel
Using bazel 7 allows to bump a few more depenencies to head.
=> Bump dependencies possible with bazel 7

verible/verilog/tools/ls/verible-lsp-adapter.cc, verible/verilog/tools/ls/verilog-language-server_test.cc
Prevent a potential crash when receiving an invalid range formatting parameter.
=> Handle invalid format range in LSP adapter and add test

verible/common/formatting/basic-format-style-init.cc, verible/common/formatting/basic-format-style.cc, verible/common/formatting/basic-format-style.h, verible/verilog/formatting/BUILD, verible/verilog/formatting/comment-controls.cc, verible/verilog/formatting/comment-controls.h, verible/verilog/formatting/comment-controls_test.cc, verible/verilog/formatting/formatter.cc, verible/verilog/parser/verilog.lex, verible/verilog/tools/formatter/BUILD, verible/verilog/tools/formatter/format_line_terminator_test.sh, verible/verilog/tools/formatter/verilog-format.cc
Issue #2370 points out that inplace formatting in Windows converts `\r\n` into `\n`.
This happens because opening files in binary mode explicitly disables the otherwise implicit translation of `\n` into `\r\n` for Windows.
=> common: util: stop using binary mode in SetContents

verible/verilog/tools/ls/README.md, verible/verilog/tools/ls/verilog-language-server.cc
With `--lsp_enable_hover`, hover information is switched on for the language server. This is off by default, as it didn't have extensive testing yet; but should be useful.
Issues #1187
=> Enable hover information via flag.

MODULE.bazel, bazel/rules_cc_466.patch
The patch from
https://github.com/bazelbuild/rules_cc/pull/466
Replaces `bash` with `/bin/sh`. Not yet submitted upstream, so for now, locally as patch.
=> Make rules_cc more compatible on Posix systems.
