chipsalliance/verible

- .github/workflows/verible-ci.yml
> Fix env-MODE: got unindented in last commit

- .github/workflows/generate_matrix.sh
- .github/workflows/script.sh
- .github/workflows/verible-ci.yml
Let's try to deal with #622 in smaller and easier to review/debug chunks.
This PR is styling only. No feature changes.
> ci: cleanup

- .github/kokoro/steps/hostsetup.sh
> Make sure to have a somewhat recent version of Python for kokoro

- .github/workflows/verible-ci.yml
#670 broke the Release job (which is not executed for PRs). This PR fixes and updates it.
> ci: fix path to artifacts in Release

- verilog/analysis/checkers/always_ff_non_blocking_rule.cc
> Style: Remove redundant empty line at end of code block.

- README.md
> Add License and continuous integration badge.

- verilog/analysis/default_rules.h
- verilog/tools/lint/BUILD
Observed a crash in the field, investigating...
> Set default for line-continuation rule to false for now.

- README.md
Following up on comment in #685
> Place badges under headline.

- common/tools/BUILD
> Remove dependencies not needed in target.

- verilog/parser/BUILD
> Remove unneeded dependency.

- common/analysis/BUILD
- common/analysis/file_analyzer.cc
- common/analysis/file_analyzer.h
- common/analysis/file_analyzer_test.cc
- common/analysis/lint_rule_status.cc
- common/analysis/lint_rule_status.h
- common/analysis/lint_rule_status_test.cc
- verilog/analysis/verilog_analyzer_test.cc
- verilog/analysis/verilog_linter.cc
- verilog/analysis/verilog_linter.h
- verilog/analysis/verilog_linter_test.cc
- verilog/formatting/formatter.cc
- verilog/formatting/tree_unwrapper_test.cc
- verilog/tools/lint/lint_tool_test.sh
- verilog/tools/lint/verilog_lint.cc
- verilog/tools/syntax/verilog_syntax.cc
> option to show line with diagnostic and a marker

- common/analysis/file_analyzer.h
- common/analysis/lint_rule_status.h
- common/analysis/lint_rule_status_test.cc
- verilog/formatting/token_annotator.cc
For some reason the presubmit did not pick these up.
> Fix a couple of smallish clang format findings.

- common/analysis/BUILD
> Add a missing dependency.

- verilog/analysis/checkers/token_stream_lint_rule_test.cc
> Remove unused variable

- verilog/formatting/formatter_test.cc
- verilog/formatting/tree_unwrapper.cc
> Fix formatting.

- .github/settings.sh
- .github/workflows/script.sh
- .github/workflows/verible-ci.yml
moving the settings for bazel builds back to settings.sh
> Move Bazel opts back into settings.sh

- verilog/tools/kythe/kythe_facts.h
- verilog/tools/kythe/kythe_facts_extractor.cc
- verilog/tools/kythe/testdata/array.sv
- verilog/tools/kythe/testdata/class.sv
> Set Kythe's vname.language to an empty string for the file nodes

- verilog/analysis/checkers/port_name_suffix_rule.cc
> Add comments to port name suffix rule checker

- common/tools/verible-transform-interactive.sh
> Use mktemp that work on GNU and BSD (MacOS) systems.

- verilog/analysis/checkers/BUILD
> Remove dependency not needed anymore.

- verilog/formatting/formatter_test.cc
- verilog/formatting/token_annotator.cc
> Adjust closing parenthesis penalties

- .github/bin/script.sh
> CI: make sure all libraries that use exceptions declare so.

- verilog/parser/verilog.lex
Preparation for dialect support.
Issues #753
> Document an AMS keyword, so that it is easier to separate out later.

- verilog/formatting/formatter_test.cc
- verilog/formatting/tree_unwrapper.cc
- verilog/formatting/tree_unwrapper_test.cc
> Indent initializer lists

- WORKSPACE
- third_party/proto/kythe/BUILD
- third_party/proto/kythe/LICENSE
- third_party/proto/kythe/README.md
- third_party/proto/kythe/storage.proto
- verilog/tools/kythe/BUILD
- verilog/tools/kythe/kythe_facts_extractor.cc
- verilog/tools/kythe/kythe_facts_extractor.h
- verilog/tools/kythe/kythe_proto_output.cc
- verilog/tools/kythe/kythe_proto_output.h
- verilog/tools/kythe/verilog_kythe_extractor.cc
The only remaining dependency is proto schema which was directly imported to the project's third_party directory.
Closes #760
> [kythe] Stop depending on Kythe at the build time

- verilog/formatting/formatter_test.cc
- verilog/parser/verilog.y
> Fix wildcard port connections

- .bazelrc
- .github/workflows/macos-compile.yml
- WORKSPACE
> Upgrade to latest absl.

- .github/settings.sh
This is experimental to see if previous issues have been resolved.
> Use latest kythe for CI testing.

- .github/settings.sh
> With Kythe at latest version, we can use Bazel 4

- verilog/formatting/formatter_test.cc
- verilog/formatting/tree_unwrapper.cc
- verilog/parser/verilog.y
> Fix alignment of DPI exported functions

- .github/workflows/windows-compile.yml
- verilog/tools/lint/verilog_style_lint.bzl
- verilog/tools/syntax/export_json_examples/verible_verilog_syntax_test.py
This pull-request make every test passes on Windows!
Once merge, we should be able to release Windows binaries!
> Make remaining test pass on Windows

- common/util/file_util.cc
> Avoid copy in range-for loop

- common/formatting/align.cc
- common/formatting/align.h
- verilog/formatting/align.cc
- verilog/formatting/formatter_test.cc
> Align comments in port list

- .github/bin/build-and-test.sh
- verilog/formatting/formatter.cc
> Fix missing break

- .github/bin/build-and-test.sh
> Enable warning about switch/case fallthrough.

- verilog/formatting/formatter.cc
- verilog/formatting/formatter_test.cc
- verilog/formatting/tree_unwrapper.cc
> formatter: Refinement of indentation for function arguments

- verilog/CST/DPI.h
- verilog/CST/DPI_test.cc
- verilog/formatting/align.cc
- verilog/formatting/formatter_test.cc
- verilog/formatting/tree_unwrapper.cc
- verilog/formatting/tree_unwrapper_test.cc
- verilog/parser/verilog.y
> Align parameters in exported/imported function

- common/analysis/lint_rule_status.cc
- common/strings/diff.cc
> For testing container if empty, use empty(), not size().

- common/formatting/align.h
- verilog/formatting/align.cc
- verilog/formatting/formatter_test.cc
Fix + small refactoring of related code to make things more robust.
Fixes: https://github.com/google/verible/issues/840
> Fix check failure in comment aligning code

- README.md
- common/README.md
- common/analysis/README.md
- common/analysis/matcher/README.md
- common/formatting/README.md
- common/lexer/README.md
- common/parser/README.md
- common/strings/README.md
- common/text/README.md
- common/tools/README.md
- common/util/README.md
- doc/formatter.md
- doc/style_lint.md
- verilog/CST/README.md
- verilog/README.md
- verilog/analysis/README.md
- verilog/analysis/checkers/README.md
- verilog/formatting/README.md
- verilog/parser/README.md
- verilog/preprocessor/README.md
- verilog/tools/README.md
- verilog/tools/diff/README.md
- verilog/tools/formatter/README.md
- verilog/tools/kythe/README.md
- verilog/tools/lint/README.md
- verilog/tools/obfuscator/README.md
- verilog/tools/preprocessor/README.md
- verilog/tools/project/README.md
- verilog/tools/syntax/README.md
> Update documentation contact person.

- verilog/formatting/formatter_test.cc
- verilog/formatting/tree_unwrapper.cc
> formatter: fix formatting of bind statements

- verilog/formatting/formatter_test.cc
- verilog/formatting/tree_unwrapper.cc
> Fix indenatation of initial begin with EOL comment

- verilog/formatting/formatter_test.cc
- verilog/formatting/tree_unwrapper.cc
- verilog/formatting/tree_unwrapper_test.cc
Second take to fix #352.
Reworked partition creation, added test cases for multiple nested lists.
> Fix initializer list indentation

- .github/bin/build-and-test.sh
- .github/bin/run-clang-format.sh
- .github/bin/run-kythe.sh
- README.md
- doc/development.md
- doc/style_lint.md
- verilog/CST/README.md
- verilog/CST/declaration.cc
- verilog/CST/type.cc
- verilog/analysis/verilog_project.h
- verilog/preprocessor/README.md
> Fix URLs to point to the changed github repository.

- verilog/formatting/tree_unwrapper.cc
Test durations:
Test                                     | before feature introduction | master | this fix
-----------------------------------------|-----------------------------|--------|----------
//verilog/formatting:tree_unwrapper_test | 0.2s                        | 6.4s   | 0.2s
//verilog/formatting:formatter_test      | 3.0s                        | 29.2   | 3.1s
> Optimize GetAssignedExpressionFromDataDeclaration

- .github/bin/build-and-test.sh
- .github/workflows/verible-ci.yml
In preparation to send it to codecov
> Also run coverage tests.

- .github/bin/set-compiler.sh
- .github/workflows/verible-ci.yml
> Link the version of gcov relevant to current compiler.

- README.md
> Add codecov coverage badge to README

- .github/bin/build-and-test.sh
> Fix indentation of ci build/test script.

- common/analysis/linter_test_utils.cc
- common/analysis/linter_test_utils_test.cc
> Make the test util violation messages more intuitive to read.

- verilog/analysis/checkers/BUILD
- verilog/analysis/default_rules.h
- verilog/tools/lint/BUILD
- verilog/tools/lint/testdata/truncated_numeric_literal.sv
> Enable truncated numerical rule.

- .github/bin/install-bazel.sh
- .github/workflows/verible-ci.yml
> Let wget be a bit less verbose while downloading bazel.

- .github/bin/generate-coverage-html.sh
- CONTRIBUTING.md
Also provide script to go along with it for ease-of-use.
> Document in development doc how to run coverage locally.

- verilog/tools/syntax/verilog_syntax_test.sh
To be self-contained, avoid pulling in any external json parser but utilize shell capabilities to implement a simple json canonicalizer.
This allows to compare tool-output with an expected output ignoring the actual formatting of the json data.
Fixes #891
> Add tests for --json_export in verilog syntax shell test.

- verilog/tools/syntax/verilog_syntax_test.sh
> Fix indentation from tab to space.

- common/text/BUILD
- verilog/CST/BUILD
> Remove unnecessary BUILD dependencies.

- common/formatting/align.h
- verilog/formatting/align.cc
> Fix some smallish style issues.

- .clang-tidy
- .github/bin/run-clang-tidy.sh
- .github/workflows/verible-ci.yml
- common/formatting/state_node.cc
- common/parser/parser_param.cc
> Switch to more recent clang-tidy-12

- common/util/file_util.cc
- verilog/analysis/verilog_linter.cc
- verilog/analysis/verilog_linter.h
- verilog/analysis/verilog_linter_configuration.cc
- verilog/analysis/verilog_linter_configuration.h
- verilog/analysis/verilog_linter_configuration_test.cc
- verilog/tools/lint/verilog_lint.cc
... instead of CHECK-failing.
Issues #960
> Bubble up error messages from configuration errors to display properly.

- common/util/file_util_test.cc
> Refine permission denied test to include more information.

- verilog/tools/kythe/BUILD
> Remove unused dependency.

- common/util/file_util_test.cc
With root permissions, even a non-readable file will be readable.
So if for whatever reason the bazel test is run with root permission,
skip the test.
Fixes #963
> Skip permission test if tests are run as root.

- verilog/tools/lint/lint_tool_test.sh
> Fix sed in lint_tool_test.sh on macOS

- common/formatting/BUILD
- common/formatting/basic_format_style.h
- common/formatting/layout_optimizer.cc
- common/formatting/layout_optimizer.h
- common/formatting/layout_optimizer_internal.h
- common/formatting/layout_optimizer_test.cc
Implementation of code formatting algorithm described in https://research.google/pubs/pub44667/
The code in this PR is not integrated with Verible tools. Integration code is added in another PR.
> Layout optimizer implementation (without integration)

- common/formatting/layout_optimizer.cc
- common/formatting/layout_optimizer_internal.h
As is custom in this project. For some reason the CI clang-tidy
did not catch this.
> Readability: Pass modified parameters by pointer.

- .github/bin/run-clang-tidy.sh
Whenever the clang-tidy configuration changes, make sure that we
re-process all files by including the configuration into the
content hash creation.
> Make clang tidy 'seen' cache dependent on changes in configuration.

- README.md
- verilog/tools/ls/README.md
> Update toplevel README to point to language server.

- .github/bin/make-compilation-db.sh
- .github/bin/run-clang-tidy.sh
The script is useful in itself as the compilation database
is useful for various tools.
> Separate out building of compilation db into separate script.

- verilog/formatting/formatter_test.cc
- verilog/formatting/token_annotator.cc
- verilog/formatting/token_annotator_test.cc
> Put space between `wait` and `(`

- common/formatting/BUILD
- common/lsp/BUILD
- verilog/CST/BUILD
- verilog/formatting/BUILD
- verilog/tools/ls/BUILD
> Dependency fixing and indentation fix for BUILD files.

- verilog/tools/ls/verible-verilog-ls_test.sh
- verilog/tools/ls/verilog_ls.cc
Also slightly improve some code/test comments.
> Add test-case to show that only symbols are highlighted.

- verilog/tools/ls/verible-lsp-adapter.cc
> Reduce complexity with early-out if.

- README.md
- verilog/tools/formatter/README.md
- verilog/tools/lint/README.md
> Include links to verible-linter-action in documentation.

- common/formatting/layout_optimizer.cc
- common/formatting/layout_optimizer_internal.h
- common/formatting/layout_optimizer_test.cc
A bit of refactoring is also done in layout_optimizer_test and a new test is added.
> Refactoring: Extract `TokenPartitionTree` → `LayoutFunction` conversion code

- .github/workflows/verible-ci.yml
- WORKSPACE
This PR updates bazel_rules_install, for Windows support, and add Windows release as a zip file to the CI process
> Added Windows release

- common/lsp/lsp-protocol.yaml
- verilog/formatting/BUILD
- verilog/tools/ls/BUILD
- verilog/tools/ls/README.md
- verilog/tools/ls/verible-lsp-adapter.cc
- verilog/tools/ls/verible-lsp-adapter.h
- verilog/tools/ls/verible-verilog-ls_test.sh
- verilog/tools/ls/verilog_ls.cc
> Wire up selection range formatting in language server.

- .github/bin/smoke-test.sh
> Document a new issue with the latest ivtest version.

- verilog/analysis/verilog_analyzer.cc
- verilog/preprocessor/verilog_preprocess.cc
> Remove unnecessary using declarations.

- .github/bin/build-and-test.sh
- common/formatting/layout_optimizer_test.cc
> Add  -Wctad-maybe-unsupported in CI (for clang) (also prepare for gcc-11 new warning)

- verilog/CST/BUILD
- verilog/CST/net_test.cc
- verilog/formatting/align.cc
- verilog/formatting/verilog_token_test.cc
> Add missing dependency; remove superfluous `using`

- verilog/tools/ls/BUILD
> Fix missing public visiblity for language server binary.

- .github/bin/smoke-test.sh
- verilog/tools/kythe/kythe_facts_extractor.cc
found in  [sv-tests](https://chipsalliance.github.io/sv-tests-results/)
These are mere stop-gap 'fixes' and logging while we debug the
underlying root-causes.
TODO: drill down to the particular code-snippete triggering it,
and fix properly.
> Work around some kythe indexer issues

- verilog/tools/ls/verilog_ls.cc
> Remove unused return value.

- common/lsp/BUILD
- common/lsp/json-rpc-dispatcher.cc
This will help identify issues in the protocol handling.
> Add diagnostic logging in RPC dispatcher.

- common/util/file_util.cc
Reading large generated files showed that GetContent() was super slow.
With this, a 245MiB file reading from a local filesystem is
sped up from 11 seconds -> 0.045 seconds.
> Switch from idiomatic to performant way to read a file.

- verilog/tools/kythe/BUILD
- verilog/tools/kythe/kythe_facts.cc
- verilog/tools/kythe/kythe_facts.h
- verilog/tools/kythe/kythe_facts_extractor.cc
- verilog/tools/kythe/kythe_facts_extractor.h
> Move more Kythe indexing artifacts into flat_hash_set.

- verilog/tools/kythe/verilog_kythe_extractor.cc
For performance testing, not having to worry about the
output is useful.
> Provide a 'none' debugging output option for Kythe facts.

- verilog/tools/kythe/kythe_facts_extractor.cc
> Give set insert a chance to be faster by using emplace().

- verilog/tools/ls/verible-lsp-adapter.cc
While we only have somewhat poor error description from yacc, provide
at least what we know from the rejected token.
> Language Server: Provide more detailed error message on syntax error.

- verilog/analysis/symbol_table.cc
Print the new node to be added.
Issues: #1002
> Make reallocation check in symbol-table more useful.

- .github/bin/smoke-test.sh
While we currently only count crash-failures, having a count
of non-zero exit codes will help improvement incentives long-term
as well as noticing failures that are non-crashes.
> Print out non-zero exit code count of tools.

- verilog/formatting/BUILD
> Fix missing dependencies in tree_unwrapper.

- verilog/formatting/tree_unwrapper.cc
Implement it as a macro to be ready for potential ABSL logging.
> Prepare LogBug() to be more logging implementation agnostic.

- WORKSPACE
> Switch to new ABSL lts version.

- .github/bin/smoke-test.sh
- verilog/analysis/symbol_table.cc
> symbol-table: Skip bind statement for now to avoid crashes.

- common/analysis/file_analyzer_test.cc
- verilog/analysis/verilog_analyzer.cc
> Fix a couple of typos.

- verilog/preprocessor/verilog_preprocess.cc
- verilog/preprocessor/verilog_preprocess.h
- verilog/preprocessor/verilog_preprocess_test.cc
> Implement `undef

- .github/bin/verify-kythe-extraction.sh
> Make it simple to see the logs in case kythe verification test fails.

- verilog/formatting/BUILD
> Fix missing dependency.

- .github/bin/smoke-test.sh
> smoke-test: Document less failures for project tool in ibex.

- .github/bin/smoke-test.sh
> Project on current opentitan produces slightly more errors.

- .github/bin/smoke-test.sh
Also add some 'grace' range that is allowed before the smoke-test
makes this an error. This is because we catch the 'live' upstream
project to run the tools overs, so there might be new conditions
that come up, but that should not necessarily result in immediate
smoke test failure.
> Update the expected number of non-zero codes in smoke test.

- common/formatting/BUILD
- common/util/BUILD
- verilog/tools/lint/README.md
> Fix some build dependencies.

- common/analysis/line_linter.cc
- common/analysis/syntax_tree_linter.cc
- common/analysis/text_structure_linter.cc
- common/analysis/token_stream_linter.cc
- verilog/analysis/verilog_linter_configuration.cc
> Use container.reserve() if we know the size.

- .github/bin/smoke-test.sh
The bug has been fixed in one of recent PRs.
Closes #1010
> Remove bug #1010 from smoke test.

- .github/bin/generate-coverage-html.sh
If the build has not been done yet, print out what to do.
> Provide a helpful message how to start creating coverage.

- .github/bin/build-and-test.sh
- WORKSPACE
This should have unreachable code places fixed
https://github.com/google/re2/issues/384
> Update RE2 to latest.

- verilog/formatting/formatter_test.cc
> Add another fuzzing example triggering #1386

- verilog/formatting/formatter_test.cc
- verilog/formatting/tree_unwrapper.cc
> Fix Use After Free in MacroCallReshaper.

- WORKSPACE
- third_party/proto/kythe/BUILD
- third_party/proto/kythe/README.md
- third_party/proto/kythe/analysis.proto
- third_party/proto/kythe/storage.proto
- verilog/tools/kythe/BUILD
- verilog/tools/kythe/filelist_parser.py
- verilog/tools/kythe/filelist_parser_test.py
- verilog/tools/kythe/verilog_kythe_kzip_writer.py
Definition of Kythe kzips can be found at https://kythe.io/docs/kythe-kzip.html
This is required for Kythe indexing.
> Add tool for producing Kythe kzips based on System Verilog filelists

- .github/workflows/verible-ci.yml
Needs to be debugged separately. Disable for now to not shadow
other potential 'real' issues.
> Disable kythe CI for now as it started failing w/o apparent reason.

- verilog/analysis/BUILD
- verilog/analysis/flow_tree.cc
- verilog/analysis/flow_tree.h
- verilog/analysis/flow_tree_test.cc
- verilog/tools/preprocessor/verilog_preprocessor.cc
> Narrow dependencies to needed headers/libs.

- shell.nix
> No need to pin an old nix version, just use whatever user is using.

- .github/bin/run-clang-format.sh
These, we'd like to keep as-is as much as possible.
> Exclude third-party code from being format-checked.

- .github/bin/run-clang-format.sh
> Fix formatting script.

- common/formatting/state_node.cc
Add a break after a LOG(FATAL) in a switch/case statement.
> Don't assume LOG(FATAL) makes rest of code unreachable.

- common/analysis/lint_waiver.cc
- common/formatting/align.cc
- common/formatting/token_partition_tree.cc
- common/strings/patch.cc
- common/text/text_structure.cc
- common/util/tree_operations.h
> In CHECK_{EQ,LT,GT}: use the same signed-ness.

- verilog/analysis/BUILD
- verilog/analysis/verilog_filelist.cc
- verilog/analysis/verilog_filelist.h
- verilog/analysis/verilog_filelist_test.cc
This is a preparation to use them in other tools that previously assembled files just from a file list in a file, but now might merge them from that file list and the command line.
> Provide a FileList::Append() method to concatenate.

- common/analysis/lint_waiver.cc
- common/formatting/layout_optimizer.cc
- common/strings/obfuscator.cc
- common/text/concrete_syntax_tree.h
In c++20, this will be deprecated.
> Don't implicitly capture [this] with [=]

- .github/bin/build-and-test.sh
- .github/workflows/verible-ci.yml
- WORKSPACE
- common/util/BUILD
- common/util/init_command_line.cc
- common/util/logging.cc
- common/util/logging.h
- doc/formatter.md
- verilog/formatting/tree_unwrapper.cc
This is essentially glog, but now officially in absl.
> Use absl logging.

- common/util/BUILD
- common/util/logging.h
... only define our own VLOG-ing #ifndef VLOG
> Prepare VLOG macros to exist at some point.

- verilog/analysis/verilog_project_test.cc
> Remove unnecessary using declaration.

- common/analysis/BUILD
- common/analysis/file_analyzer.cc
- common/analysis/file_analyzer.h
- verilog/analysis/verilog_analyzer.cc
... instead of inheritance.
The only downside is that this requires the slightly ugly `RelinquishTextStructure()`. Maybe you have an idea.
> Change file analzyer to be a composition with TextStructure.

- .github/bin/smoke-test.sh
Avoid unnecessary network wait time.
> Smoke tests: download projects parallel to compiling them.

- verilog/tools/preprocessor/README.md
- verilog/tools/preprocessor/verilog_preprocessor.cc
- verilog/tools/preprocessor/verilog_preprocessor_test.sh
Fix the unit test to actually fail on failures (there were a bunch of `exit 0` in there.)
Update documentation slightly and include in README.
> Update the preprocessor command to 'preprocess'.

- WORKSPACE
Hasn't been updated in a while.
> Update Windows flex and bison.

- .github/workflows/verible-ci.yml
We mixed two different versions.
> Use cachev3 everywhere.

- verilog/formatting/formatter_test.cc
Same situation as in #1580. Added test to cover that case.
Fixes #1207
> Add more struct tests with comments

- WORKSPACE
(makes it possible to compile with c++20)
> Update protobuf to latest 21.12.

- verilog/parser/verilog.y
- verilog/parser/verilog_parser_unittest.cc
> Parse `default_nettype trireg

- verilog/analysis/BUILD
- verilog/analysis/verilog_filelist.h
- verilog/tools/project/project_tool.cc
- verilog/tools/project/project_tool_test.sh
This allows to get the files, +define+ and +include+ also from the command line.
> Make use of AppendFileListFromCommandline()

- verilog/tools/ls/verible-verilog-ls_test.sh
Since now the functional tests moved to verilog-language-server_test, the shellscript test can be reduced to a simple round-trip test. This removes a lot of hard-to-understand spaghetti-json and simplifies it a lot.
> Simplify language server shellscript test.

- verilog/parser/verilog.y
It looks like newer compiler start warning about it:
https://github.com/chipsalliance/verible/actions/runs/4012371146/jobs/6890758390#step:7:196
> Don't use std::move through using alias, be explicit.

- .github/workflows/verible-ci.yml
> Build a vsix release right in the CI.

- .github/workflows/verible-ci.yml
- verilog/formatting/tree_unwrapper.cc
Current container broke recently.
Issues: #1663
> Usa a different container to run the CI

- .github/workflows/verible-ci.yml
- verilog/formatting/formatter_test.cc
Should be recognized and properly formatted.
Relevant in the context of #1628
> Document slightly uncommon assignment inside attributes.

- verilog/tools/ls/BUILD
- verilog/tools/ls/autoexpand_test.cc
While at it, add needed, remove unneeded dependency in  BUILD file.
> Fix some trailing whitespace.

- common/text/concrete_syntax_tree.h
- common/text/concrete_syntax_tree_test.cc
> Reduce the assumption that SymbolPtr is unique_ptr<>

- .github/bin/build-and-test.sh
- .github/workflows/verible-ci.yml
Assuming that these will be the most accurate about complaining about problems.
> Use latest available compier for c++2x CI tests.

- common/parser/bison_parser_adapter.h
- common/parser/parse.h
- common/parser/parser_param.h
If there is ever a need for these, they can be re-added, but right now they are just unnecessary.
> Remove unused functions (some getters in parser).

- WORKSPACE
> Update protobuf to 22.0

- .clang-tidy
- common/analysis/matcher/core_matchers_test.cc
- common/analysis/matcher/matcher_builders.h
- common/analysis/matcher/matcher_builders_test.cc
- verilog/CST/verilog_matchers.cc
- verilog/CST/verilog_matchers.h
First step: make PathMatchBuilder a constexpr to build a consexpr matcher.
> Create path matchers as constexpr.

- verilog/tools/ls/autoexpand.cc
- verilog/tools/ls/autoexpand_test.cc
Module sorting in AUTO expansion does not handle transitive dependencies between modules. This fix makes `DependsOn` recursively traverse all dependencies.
> Fix transitive dependencies in AUTO expansions

- .github/bin/run-clang-tidy.sh
Previously, we discarded the whole list of files when there was a single clang-tidy complaint in any of them.
Now, only exclude the files from the cache that had issues, but keep all the rest. That way it is possible to incrementally fix all the clang-tidy complatins without having to reprocess all the files that didn't have any issues.
clang-tidy is very expensive: running it over all verible files takes about 3-4 core hours. This will help reduce duplicate work.
> Remember all files in the clang-tidy cache that were clean.

- .github/bin/run-clang-tidy.sh
- .github/workflows/verible-ci.yml
- shell.nix
With it, also fix the missing slash at the end of the `$(pwd)`, which
we also want to remove to have pure relative paths.
> Better document the path canonicalization expression.

- verilog/tools/kythe/indexing_facts_tree_extractor.cc
- verilog/tools/kythe/indexing_facts_tree_extractor_test.cc
Preferred style is to use pointers when a value is mutable.
> Fix use of non-const reference parameters.

- common/strings/range_test.cc
- common/util/range_test.cc
- verilog/formatting/token_annotator_test.cc
... make sure we don't warn at that particular situation.
> clang-tidy is able to find some situations that we want to test.

- .github/bin/run-clang-tidy-cached.cc
The paths of source files reported are not always relative to the project root, but some are prefixed with the bazel root or the current directory.
Canonicalize them so that files are always reported the same way.
Also: better quote variables in the 'shellscript' compiler invocation line; update and refine some comments.
> Canonicalize paths emitted from clang-tidy.

- common/lsp/lsp-protocol-enums.h
- verilog/tools/ls/document-symbol-filler.cc
- verilog/tools/ls/verible-lsp-adapter.cc
- verilog/tools/ls/verilog-language-server_test.cc
> Fix naming of LSP enum names.

- verilog/tools/ls/autoexpand_test.cc
- Tests header port sorting in AUTO expansion
- Refactors AUTO expand testing
- Adds another AUTO kind expansion test
Handles two of the three issues found in https://github.com/chipsalliance/verible/pull/1774 (see comments there).
> Improve test coverage of AUTO expansion

- .github/bin/run-clang-tidy-cached.cc
If the compilation DB was re-created, it might contain changes that improve the outcome, e.g. an include directory reference that didn't work before and made clang-tidy fail on a particular *.cc file (typically due to BUILD) changes.
Similarly if there are changes in the WORKSPACE file since last time a file was looked at.
Check timestamps of compile_commands.json and WORKSPACE to decide if a file that otherwise is unchanged but generated messges last time (i.e. file size != 0) shall be reprocessed.
> clang-tidy: reprocesses troublesome files if older than build env.

- .github/bin/check-potential-problems.sh
- .github/workflows/verible-ci.yml
- common/text/text_structure.h
Just a simple shell script running at CI time.
> CI: Test for unintended use of problematic symbols/names/includes.

- .github/workflows/verible-ci.yml
Use that to choose modern compiler.
> smoke-test-analyzer: slang compile needs c++20

- common/lsp/BUILD
- common/lsp/lsp-file-utils.cc
- common/lsp/lsp-file-utils.h
- verilog/tools/ls/BUILD
- verilog/tools/ls/lsp-parse-buffer.cc
- verilog/tools/ls/symbol-table-handler.cc
- verilog/tools/ls/verilog-language-server.cc
> lsp-file-utils has no needed notion of verilog; move to common.

- .github/workflows/verible-ci.yml
- verilog/tools/ls/README.md
This run requires a personal access token to be added as secret
> CI: publish VSCode extension automatically

- verilog/tools/ls/autoexpand.cc
- verilog/tools/ls/autoexpand_test.cc
1.  Match `AUTO_TEMPLATE` by instance name regex
The instance name regex in `AUTO_TEMPLATE` has been ignored up until this patch.
Now it is actually being used and considered for matching the correct template
to a given instance. The way it works is straightforward: if a template matches
an instance by type, the instance's name is checked against the template's
regex. If it matches, the template is selected. Otherwise, the next template
that matches by type is considered.
2.  Replace `@` in `AUTO_TEMPLATE` with module instance name
This change makes it so that the symbol `@` in signal names in `AUTO_TEMPLATE`
is replaced with the name of the instance matched to a given template.
> Match `AUTO_TEMPLATE` by instance name regex

- verilog/tools/ls/autoexpand.cc
> Use explicit `nullopt` in `autoexpand.cc` 

- verilog/tools/ls/autoexpand.cc
- verilog/tools/ls/autoexpand_test.cc
If a generated wire or port is connected to multiple instance ports, its width
is taken as the maximum of widths of all connected ports. This only works if the
dimensions are given as numbers. Otherwise, the fallback is to just use the
first relevant dimensions.
> Make generated signal width the max of connected signal widths

- verilog/analysis/checkers/undersized_binary_literal_rule.cc
- verilog/analysis/checkers/undersized_binary_literal_rule_test.cc
Fixes https://github.com/chipsalliance/verible/issues/314
> undersized-binary-literal: suggest inferred size

- common/text/text_structure.cc
- verilog/tools/ls/BUILD
- verilog/tools/ls/symbol-table-handler.cc
We already have verible::IsSubRange(), which we can use.
> Simplify string_view contain test.

- verilog/tools/ls/verilog-language-server_test.cc
PR 1884 solved a crash when the user asked the VerilogLanguageServer to format a buffer with syntax errors. This test checks we don't go back on this incorrect behaviour
The test doesn't assume anything for the response, it just checks the Language Server doesn't crash
> Add test for PR 1884

- .github/bin/error-log-analyzer.py
- .github/bin/smoke-test.sh
Don't do different things for the log analyzer and otherwise.
> Simplify smoke test log generation.

- verilog/tools/ls/vscode/package.json
> Include 'SystemVerilog' in the package description.

- verilog/parser/verilog.y
> Remove trailing whitespace.

- .github/bin/error-log-analyzer.py
- .github/bin/smoke-test.sh
Also update some slightly changed error
expectations (some up, some down), as some of the projects changed.
> Add caliptra-rtl to smoke tests.

- verilog/analysis/checkers/always_comb_blocking_rule.cc
- verilog/analysis/checkers/always_comb_blocking_rule_test.cc
Not a great deal as the manual fix involves removing one character, but might make the user experience better.
> Add autofix for always_comb_blocking rule

- WORKSPACE
Be on latest for #1962 to test against.
> Bump protobuf.

- shell.nix
Provide examples in the shell.nix how to switch.
Issues #1952
> Make it easier to play with different compilers.

- common/lsp/message-stream-splitter.cc
- common/lsp/message-stream-splitter_test.cc
The previous code was assuming that the last header was the Content-Length header, which happened to be the case for the tested editors, but of course is not an assumption valid in all cases.
Issues: #1987
> Make LSP header parsing more robust.

- verilog/tools/ls/README.md
Updates the documentation for enabling LSP compatibility with vim.
> [LSP] README: update vim editor configuration options

- common/text/BUILD
- common/text/text_structure_test.cc
- common/text/tree_builder_test_util.cc
- common/text/tree_utils_test.cc
- verilog/CST/BUILD
- verilog/CST/macro.cc
- verilog/CST/seq_block.cc
- verilog/CST/type.cc
- verilog/tools/kythe/BUILD
- verilog/tools/kythe/indexing_facts_tree_extractor.cc
common/util/casts.h and common/util/logging.h have been missed in some files.
> Fix some IWYU issues.

- .github/workflows/verible-ci.yml
> Disable smoke-test analyzer for now

- .github/workflows/verible-ci.yml
New versions for get-time and cancel-workflow actions.
> Update github actions.

- common/formatting/unwrapped_line.cc
- verilog/formatting/formatter_test.cc
I recently see the same problem as #1538 .
I push a test to reproduce #1538 and see CI, then push the fix commit later.
> Fix #1538 (local disabling is ignored).

- verilog/analysis/checkers/BUILD
- verilog/analysis/checkers/suspicious_semicolon_rule.cc
- verilog/analysis/checkers/suspicious_semicolon_rule_test.cc
- verilog/analysis/verilog_linter_configuration_test.cc
Found some more opportunities to add needed includes.
> Complete suspicious_semicolon_rule_test includes.

- README.md
> Document the range of working bazel versions (>=5 && < 7).

- verilog/tools/ls/autoexpand.cc
> autoexpand: fix weak ordering.

- verilog/tools/ls/verible-verilog-ls.cc
> Log the command line the language server sees for easier debugging.

- .github/workflows/verible-ci.yml
Hopefully it helps to solve #2140, if not then it will not hurt to update the Windows runner to a newer version.
> Updated Windows to 2022 in CI

- .github/bin/check-potential-problems.sh
Also make sure that rules_python() is not accidentally re-introduced due its non-hermeticity.
> Litmus test: Update std::string_view explanation.

- .github/bin/smoke-test.sh
Also update some expectations since other upstream projects changed.
> Add opl3_fpga to smoke tests.

- .github/bin/run-clang-tidy-cached.cc
.. it resutlts in noisy output in the CI.
> clang-tidy-cached: don't output progress updates if not isatty()

- verilog/tools/preprocessor/README.md
> Update Verible Proprocessor README Documentation for +incdir+ flag

- .github/workflows/verible-ci.yml
Release and GH pages need this recently required configuration change.
Fixes #2226
> CI: Set wriite permissions.

- verilog/parser/verilog_parser_unittest.cc
Added interconnect syntax test as requested by PR #2188.
> [LINT] Add interconnect unit test, PR #2188

- common/util/file_util_test.cc
This will uncover if systems that handle newlines specially, work.
> Test that various newline characters roundtrip to files properly.

- verilog/tools/ls/symbol-table-handler_test.cc
Looks like some copy/pasted leftover from some older code not needed anymore ?
> Fix some statements without effect in test.

- verible/verilog/tools/lint/lint_tool_test.sh
Working towards replacing patch on Mac which recently started to ship a broken patch utility.
> Make it possible to set patch utility via environment variable.

- verible/common/formatting/layout-optimizer.cc
- verible/common/lsp/lsp-file-utils.cc
- verible/verilog/analysis/verilog-linter.cc
- verible/verilog/tools/ls/symbol-table-handler.cc
> Annotate parts that can be updated after next absl bump

- .github/bin/check-potential-problems.sh
- verible/common/util/BUILD
We're only using std::string_view
> Fix stray absl string_view dependency.

- .github/bin/smoke-test.sh
- shell.nix
Also prepare shell.nix to have minimum bazel 7.
> Update smoke test expectations.

- verible/verilog/tools/ls/symbol-table-handler_test.cc
Previously, this was based on __FUNCTION__, but it is compiler dependent on what that would be.
> Create directory name based on test name.
